### ISSUE TITLE
[calib2] issue with calibrant tooltip

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1003]
```
ERROR:pyFAI-calib2.UNCAUGHT:'ascii' codec can't decode byte 0xcf in position 51: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyFAI/gui/calibration/ExperimentTask.py", line 211, in __calibrantChanged
    self._calibrantPreview.setCalibrant(settings.calibrantModel().calibrant())
  File "/usr/lib/python2.7/dist-packages/pyFAI/gui/widgets/CalibrantPreview.py", line 65, in setCalibrant
    self.__updateToolTip()
  File "/usr/lib/python2.7/dist-packages/pyFAI/gui/widgets/CalibrantPreview.py", line 123, in __updateToolTip
    toolTip = "\n".join(toolTip)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 51: ordinal not in range(128)
```

**Comment by vallsv** [comment]
It looks like it is a Python2 error.
But it could be fixed.
