### ISSUE TITLE
[gui] OpenCL selector...

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1047]
![pyqt5_opencl](https://user-images.githubusercontent.com/1018880/49996803-3dae3280-ff90-11e8-96b2-90f3b08c2948.png)

**Comment by kif** [comment]
Followed by:
```
update labels
replace labels
INFO:pyFAI.gui.diffmap_widget:in configure_diffraction
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyFAI/gui/widgets/WorkerConfigurator.py", line 427, in selectOpenClDevice
    self.opencl_label.setDevice(self._openclDevice)
  File "/usr/lib/python2.7/dist-packages/pyFAI/gui/widgets/OpenClDeviceLabel.py", line 121, in setDevice
    self.__updateDisplay()
  File "/usr/lib/python2.7/dist-packages/pyFAI/gui/widgets/OpenClDeviceLabel.py", line 75, in __updateDisplay
    deviceName, platformName = None
TypeError: 'NoneType' object is not iterable
```

**Comment by vallsv** [comment]
python2

**Comment by kif** [comment]
On Fri, 14 Dec 2018 02:13:26 -0800
Valentin Valls <notifications@github.com> wrote:

> python2

Then it is a packaging issue as it was run from a debian installed package

**Comment by kif** [comment]
The same in python3 ...
```
lintaillefer:/mnt/data/ID13/diffmap % python3 /usr/bin/diff_map
INFO:pyFAI.method_registry:Degrading method from (pseudo,histogram,*) -> (bbox,histogram,*)
INFO:pyFAI.method_registry:Degrading method from (full,histogram,*) -> (pseudo,histogram,*)
update labels
replace labels
INFO:pyFAI.gui.diffmap_widget:in configure_diffraction
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1737, resource id: 20177358, major code: 40 (TranslateCoords), minor code: 0
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyFAI/gui/widgets/WorkerConfigurator.py", line 422, in selectOpenClDevice
    dialog = OpenClDeviceDialog(self)
  File "/usr/lib/python3/dist-packages/pyFAI/gui/dialog/OpenClDeviceDialog.py", line 56, in __init__
    model = self.__createModel()
  File "/usr/lib/python3/dist-packages/pyFAI/gui/dialog/OpenClDeviceDialog.py", line 118, in __createModel
    self.__availableIds[(platformId, deviceId)] = model.rowCount()
TypeError: unhashable type: 'QStandardItem'
Aborted
```

**Comment by vallsv** [comment]
I get it...

**Comment by vallsv** [comment]
BTW you should add comment on the PR. It is updated now.

**Comment by vallsv** [comment]
Fixed on the master
