### ISSUE TITLE
[diff_map]

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1049]
running in python3 there is a string conversion error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/pyFAI/gui/diffmap_widget.py", line 447, in process
    self.radial_data = diffmap.init_ai()
  File "/usr/lib/python3/dist-packages/pyFAI/diffmap.py", line 385, in init_ai
    self.makeHDF5(rewrite=False)
  File "/usr/lib/python3/dist-packages/pyFAI/diffmap.py", line 320, in makeHDF5
    processgrp["program"] = numpy.array([numpy.str_(i) for i in sys.argv])
  File "/usr/lib/python3/dist-packages/h5py/_hl/group.py", line 291, in __setitem__
    ds = self.create_dataset(None, data=obj, dtype=base.guess_dtype(obj))
  File "/usr/lib/python3/dist-packages/h5py/_hl/group.py", line 106, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/usr/lib/python3/dist-packages/h5py/_hl/dataset.py", line 100, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1530, in h5py.h5t.py_create (/build/h5py-gWjLYu/h5py-2.7.1/h5py/h5t.c:17861)
  File "h5py/h5t.pyx", line 1552, in h5py.h5t.py_create (/build/h5py-gWjLYu/h5py-2.7.1/h5py/h5t.c:17681)
  File "h5py/h5t.pyx", line 1613, in h5py.h5t.py_create (/build/h5py-gWjLYu/h5py-2.7.1/h5py/h5t.c:17640)
TypeError: No conversion path for dtype: dtype('<U17')
```

**Comment by vallsv** [comment]
It's not the way to store unicode strings `numpy.array([numpy.str_(i) for i in sys.argv])`.
It means `sys.argv` constains unicode entries, i guess.

**Comment by vallsv** [comment]
This should work
```
dtype = h5py.special_dtype(vlen=six.text_type)
numpy.array([numpy.str_(i) for i in sys.argv], dtype=dtype)
```

**Comment by vallsv** [comment]
Hmmm, but it's not obvious. I dont know the text encoding of `sys.argv` in python2 is known.

**Comment by vallsv** [comment]
Fixed on the master
