### ISSUE TITLE
Problem to compute solid angle from Worker

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#1063]
```
Traceback (most recent call last):
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/worker.py", line 426, in process
    integrated_result = self.ai.integrate1d(**kwarg)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/azimuthalIntegrator.py", line 1022, in _integrate1d_legacy
    solidangle = self.solidAngleArray(shape, correctSolidAngle)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/geometry.py", line 1105, in solidAngleArray
    shape, dtype=numpy.float32)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 1808, in fromfunction
    return function(*args,**kwargs)
TypeError: diffSolidAngle() takes exactly 3 arguments (2 given)
ERROR:pyFAI.worker:error in integration do_2d: False
```

**Comment by vallsv** [comment]
```
Traceback (most recent call last):
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/worker.py", line 426, in process
    integrated_result = self.ai.integrate1d(**kwarg)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/azimuthalIntegrator.py", line 1333, in _integrate1d_legacy
    pos0 = self.array_from_unit(shape, "center", unit, scale=False)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/geometry.py", line 978, in array_from_unit
    out = Geometry.__dict__[meth_name](self, shape)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/geometry.py", line 511, in twoThetaArray
    dtype=numpy.float32)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 1808, in fromfunction
    return function(*args,**kwargs)
TypeError: tth() takes at least 3 arguments (2 given)
```
