### ISSUE TITLE
[calib2] Issue when switching to integration tab

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1064]
```
INFO:pyFAI.geometryRefinement:Constrained Least square 1.10277500456e-08 --> 3.81474020822e-09
[  9.03438762e-01   1.43770792e-01   1.27668151e-01   1.06102371e-03
   3.41853551e-04  -1.01865380e-10] FixedParameters({'wavelength'}) [(0.0, 10.0), (-1.72, 2.58), (-1.72, 2.58), (-3.141592653589793, 3.141592653589793), (-3.141592653589793, 3.141592653589793), (-3.141592653589793, 3.141592653589793)] 3.81474020822e-09
INFO:pyFAI.geometryRefinement:maxdelta on dist: 0.904059461578 --> 0.903438761579 
INFO:pyFAI.massif:Image size is (1679, 1475)
INFO:pyFAI.massif:Binning size is [1, 1]
INFO:pyFAI.massif:Labeling found 1608 massifs.
INFO:pyFAI.azimuthalIntegrator:AI.integrate1d: Resetting integrator because init
ERROR:silx.gui.widgets.ThreadPoolPushButton:Error while executing callable pyFAI.gui.calibration.IntegrationTask.run.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/silx/gui/widgets/ThreadPoolPushButton.py", line 56, in run
    result = self.__callable(*self.__args, **self.__kwargs)
  File "/usr/lib/python3/dist-packages/pyFAI/gui/calibration/IntegrationTask.py", line 190, in run
    maskData[self.__mask == 0] = float("NaN")
IndexError: in the future, 0-d boolean arrays will be interpreted as a valid boolean index
ERROR:pyFAI-calib2.UNCAUGHT:'IntegrationProcess' object has no attribute '_IntegrationProcess__ringAngles'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyFAI/gui/calibration/IntegrationTask.py", line 887, in __integratingFinished
    self.__updateGUIWithIntegrationResult(self.__integrationProcess)
  File "/usr/lib/python3/dist-packages/pyFAI/gui/calibration/IntegrationTask.py", line 898, in __updateGUIWithIntegrationResult
    self._plot.setIntegrationProcess(integrationProcess)
  File "/usr/lib/python3/dist-packages/pyFAI/gui/calibration/IntegrationTask.py", line 666, in setIntegrationProcess
    self.__availableRingAngles = integrationProcess.ringAngles()
  File "/usr/lib/python3/dist-packages/pyFAI/gui/calibration/IntegrationTask.py", line 228, in ringAngles
    return self.__ringAngles
AttributeError: 'IntegrationProcess' object has no attribute '_IntegrationProcess__ringAngles'
```

**Comment by vallsv** [comment]
Without context, i dont know

**Comment by vallsv** [comment]
I guess the mask was corrupted, according to the first error message

**Comment by vallsv** [comment]
Or the image, according to the code
```
maskData = numpy.ones(shape=self.__image.shape, dtype=numpy.float32)
maskData[self.__mask == 0] = float("NaN")
```

**Comment by kif** [comment]
I have a patch to be validated before PR.

**Comment by kif** [comment]
the issue is when no mask is defined ... the detector always provides a mask

**Comment by vallsv** [comment]
I found other  small problems, i will fix all this things in a single PR
