### ISSUE TITLE
[Integrate] Backward compatibility issue

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1068]
I found that the .azimint.json is read at start up which is great (and expected).
Nevertheless in some "old fashioned" json files it crashed the detector window.

Here is the content of the JSON file:
```
{
    "poni1": 0.225406, 
    "dist": 0.3, 
    "poni2": 0.2115772, 
    "chi_discontinuity_at_0": false, 
    "do_mask": false, 
    "do_dark": false, 
    "do_azimuthal_range": false, 
    "do_flat": false, 
    "do_2D": false, 
    "azimuth_range_min": null, 
    "poni": "/home/jerome/workspace/pyFAI/test/testimages/Pilatus6M.poni", 
    "splineFile": "", 
    "wavelength": null, 
    "pixel2": 0.000172, 
    "polarization_factor": 0.0, 
    "radial_range_min": null, 
    "pixel1": 0.000172, 
    "nbpt_azim": null, 
    "do_solid_angle": true, 
    "do_radial_range": false, 
    "do_poisson": false, 
    "rot1": 0.0, 
    "azimuth_range_max": null, 
    "rot3": 0.0, 
    "rot2": 0.0, 
    "delta_dummy": null, 
    "flat_field": "", 
    "nbpt_rad": 500, 
    "dark_current": "", 
    "do_polarization": false, 
    "mask_file": "", 
    "detector": "detector", 
    "unit": "2th_deg", 
    "radial_range_max": null, 
    "val_dummy": null, 
    "do_dummy": false
}
```
Once the file loaded, opening the "detector" widget crashes the application with:
```
jerome@patagonia:~/workspace/pyFAI$ pyFAI-integrate 
INFO:pyFAI.method_registry:Degrading method from (pseudo,histogram,*) -> (bbox,histogram,*)
INFO:pyFAI.method_registry:Degrading method from (full,histogram,*) -> (pseudo,histogram,*)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyFAI/gui/widgets/WorkerConfigurator.py", line 397, in selectDetector
    popup.setDetector(self.__detector)
  File "/usr/lib/python3/dist-packages/pyFAI/gui/calibration/DetectorSelectorDrop.py", line 294, in setDetector
    self.__selectCustomDetector(self.__detector)
  File "/usr/lib/python3/dist-packages/pyFAI/gui/calibration/DetectorSelectorDrop.py", line 395, in __selectCustomDetector
    self.__detectorWidth.setValue(detector.max_shape[0])
TypeError: 'NoneType' object is not subscriptable
Abandon
```

**Comment by vallsv** [comment]
The problem is the `Detector` class. I expect a size, while it was not mandatory. Easy to fix.

**Comment by kif** [comment]
On Tue, 18 Dec 2018 05:40:30 -0800
Valentin Valls <notifications@github.com> wrote:

> The problem is the `Detector` class. I expect a size, while it was not mandatory. Easy to fix.

Great !

-- 
Jérôme Kieffer
tel +33 476 882 445
