### ISSUE TITLE
[opencl] Error with OpenCL 1D integration

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#1095]
Error with `full csr opencl target=None`
```
Traceback (most recent call last):
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/widgets/ThreadPoolPushButton.py", line 56, in run
    result = self.__callable(*self.__args, **self.__kwargs)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/tasks/IntegrationTask.py", line 205, in run
    polarization_factor=self.__polarizationFactor)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/azimuthalIntegrator.py", line 1253, in _integrate1d_legacy
    profile=profile)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/opencl/azim_csr.py", line 157, in __init__
    self.send_buffer(self._indptr, "indptr")
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/opencl/azim_csr.py", line 273, in send_buffer
    if (data.dtype == dest_type) or (data.dtype.itemsize > dest_type.itemsize):
AttributeError: 'pyFAI.ext.splitPixelFullCSR._memoryviewslice' object has no attribute 'dtype'
```

**Comment by kif** [comment]
On Mon, 14 Jan 2019 08:16:38 -0800
Valentin Valls <notifications@github.com> wrote:

> Error with `full csr opencl target=None`
> ```
> Traceback (most recent call last):
>   File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/widgets/ThreadPoolPushButton.py", line 56, in run
>     result = self.__callable(*self.__args, **self.__kwargs)
>   File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/tasks/IntegrationTask.py", line 205, in run
>     polarization_factor=self.__polarizationFactor)
>   File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/azimuthalIntegrator.py", line 1253, in _integrate1d_legacy
>     profile=profile)
>   File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/opencl/azim_csr.py", line 157, in __init__
>     self.send_buffer(self._indptr, "indptr")
>   File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/opencl/azim_csr.py", line 273, in send_buffer
>     if (data.dtype == dest_type) or (data.dtype.itemsize > dest_type.itemsize):
> AttributeError: 'pyFAI.ext.splitPixelFullCSR._memoryviewslice' object has no attribute 'dtype'
> ```

Looks like a numpy.asarray missing at the output of the function... I'll have a look.
