### ISSUE TITLE
[pyFAI-integrate] Detector not transmitted to worker

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1097]
in pyFAI-integrate

What I did: load the "Pilatus6M.poni", then force the detector to Pilatus6M and integrate an image (of the same detector).
The error message is
```
WARNING:pyFAI.gui.widgets.WorkerConfigurator:json key 'detector' unused
Traceback (most recent call last):
  File "/home/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7/pyFAI/worker.py", line 389, in process
    integrated_result = self.ai.integrate1d(**kwarg)
  File "/home/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7/pyFAI/azimuthalIntegrator.py", line 1023, in _integrate1d_legacy
    solidangle = self.solidAngleArray(shape, correctSolidAngle)
  File "/home/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7/pyFAI/geometry.py", line 1104, in solidAngleArray
    shape, dtype=numpy.float32)
  File "/usr/lib/python3/dist-packages/numpy/core/numeric.py", line 2028, in fromfunction
    return function(*args, **kwargs)
  File "/home/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7/pyFAI/geometry.py", line 1077, in diffSolidAngle
    cosa = self._cached_array["cos_incidence"] = self.cos_incidence(d1, d2)
  File "/home/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7/pyFAI/geometry.py", line 1000, in cos_incidence
    p1, p2, p3 = self._calc_cartesian_positions(d1, d2)
  File "/home/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7/pyFAI/geometry.py", line 230, in _calc_cartesian_positions
    p1, p2, p3 = self.detector.calc_cartesian_positions(d1, d2)
  File "/home/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7/pyFAI/detectors/_common.py", line 621, in calc_cartesian_positions
    p1 = (self._pixel1 * (dY + d1c))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7/pyFAI/gui/IntegrationDialog.py", line 116, in __batchProcess
    self.proceed()
  File "/home/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7/pyFAI/gui/IntegrationDialog.py", line 224, in proceed
    metadata=metadata)
  File "/home/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7/pyFAI/worker.py", line 408, in process
    logger.error("\n".join(err2))
TypeError: sequence item 8: expected str instance, Method found
Aborted
```

**Comment by vallsv** [comment]
We can read that a field was not read, i guess it explain things
`WARNING:pyFAI.gui.widgets.WorkerConfigurator:json key 'detector' unused`
