### ISSUE TITLE
[calib2] Error while rafinement

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#1117]
Using Soleil Synchrotron DiffAbs data
```
ERROR:pyFAI-calib2.UNCAUGHT:index 5 is out of bounds for axis 0 with size 5
Traceback (most recent call last):
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/tasks/GeometryTask.py", line 999, in __initGeometry
    self.__initGeometryFromPeaks()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/tasks/GeometryTask.py", line 965, in __initGeometryFromPeaks
    calibration.init(peaks, "massif", constraints)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/helper/RingCalibration.py", line 237, in init
    self.__init(peaks, method, constraintsModel=constraintsModel)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/helper/RingCalibration.py", line 214, in __init
    rms = geoRef.refine(1000000)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/helper/RingCalibration.py", line 122, in refine
    deltaS = self.__geoRef.refine2_wavelength(maxiter, self.__fixed)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/geometryRefinement.py", line 401, in refine2_wavelength
    iprint=(logger.getEffectiveLevel() <= logging.INFO))
  File "/home/valls/.local/lib/python3.5/site-packages/scipy/optimize/slsqp.py", line 208, in fmin_slsqp
    constraints=cons, **opts)
  File "/home/valls/.local/lib/python3.5/site-packages/scipy/optimize/slsqp.py", line 379, in _minimize_slsqp
    fx = func(x)
  File "/home/valls/.local/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 293, in function_wrapper
    return function(*(wrapper_args + args))
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/geometryRefinement.py", line 289, in residu2_wavelength
    t = self.residu1_wavelength(param, d1, d2, rings)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/geometryRefinement.py", line 274, in residu1_wavelength
    return self.tth(d1, d2, param) - self.calc_2th(rings, param[6] * 1e-10)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/geometryRefinement.py", line 268, in calc_2th
    return numpy.array(ary, dtype=numpy.float64)[rings]
IndexError: index 5 is out of bounds for axis 0 with size 5
```

**Comment by vallsv** [comment]
@kif think about fixing that using an auto constraint on the wavelength.

**Comment by vallsv** [comment]
It have to be catch by the GUI anyway as it create inconsistencies.

**Comment by vallsv** [comment]
My polishing branch fix the GUI side by catching the exception in geometryRefinement and aborting the minimization.

**Comment by vallsv** [comment]
Easy to reproduce by using LaB6 + energy=1KeV for example

**Comment by vallsv** [comment]
```
ERROR:pyFAI.calibrant:Not d-spacing for calibrant: LaB6 Calibrant at wavelength 1.2398419739640718e-09
ERROR:pyFAI.calibrant:Not d-spacing for calibrant: LaB6 Calibrant at wavelength 1.2398419739640718e-09
ERROR:pyFAI.gui.helper.RingCalibration:Error while refining the geometry
Traceback (most recent call last):
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/helper/RingCalibration.py", line 128, in refine
    deltaS = self.__geoRef.refine2(maxiter, self.__fixed)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/geometryRefinement.py", line 343, in refine2
    iprint=(logger.getEffectiveLevel() <= logging.INFO))
  File "/home/valls/.local/lib/python3.5/site-packages/scipy/optimize/slsqp.py", line 208, in fmin_slsqp
    constraints=cons, **opts)
  File "/home/valls/.local/lib/python3.5/site-packages/scipy/optimize/slsqp.py", line 399, in _minimize_slsqp
    fx = func(x)
  File "/home/valls/.local/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 300, in function_wrapper
    return function(*(wrapper_args + args))
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/geometryRefinement.py", line 279, in residu2
    t = self.residu1(param, d1, d2, rings)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/geometryRefinement.py", line 271, in residu1
    return self.tth(d1, d2, param) - self.calc_2th(rings, self.wavelength)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/geometryRefinement.py", line 268, in calc_2th
    return numpy.array(ary, dtype=numpy.float64)[rings]
IndexError: index 0 is out of bounds for axis 0 with size 0
ERROR:pyFAI.calibrant:Not d-spacing for calibrant: LaB6 Calibrant at wavelength 1.2398419739640718e-09
ERROR:pyFAI-calib2.UNCAUGHT:index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/tasks/GeometryTask.py", line 782, in __initGeometry
    self.__initGeometryFromPeaks()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/tasks/GeometryTask.py", line 740, in __initGeometryFromPeaks
    calibration = self.__getCalibration()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/tasks/GeometryTask.py", line 714, in __getCalibration
    self.__calibration = self.__createCalibration()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/tasks/GeometryTask.py", line 707, in __createCalibration
    method="massif")
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/helper/RingCalibration.py", line 148, in __init__
    self.__init(peaks, method)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/helper/RingCalibration.py", line 206, in __init
    score = geoRef.chi2()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/helper/RingCalibration.py", line 103, in chi2
    chi2 = self.__geoRef.chi2(param)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/geometryRefinement.py", line 490, in chi2
    self.data[:, 0], self.data[:, 1], self.data[:, 2])
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/geometryRefinement.py", line 279, in residu2
    t = self.residu1(param, d1, d2, rings)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/geometryRefinement.py", line 271, in residu1
    return self.tth(d1, d2, param) - self.calc_2th(rings, self.wavelength)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/geometryRefinement.py", line 268, in calc_2th
    return numpy.array(ary, dtype=numpy.float64)[rings]
IndexError: index 0 is out of bounds for axis 0 with size 0
```
