### ISSUE TITLE
[calin2] Error while using OpenCL-CSR-bounding box

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#1148]
I was using the data from ID15.
```
WARNING:pyFAI.opencl.azim_csr:Please upgrade to silx v0.10+
WARNING:pyFAI.opencl.azim_csr:Please upgrade to silx v0.10+
ERROR:pyFAI-calib2.UNCAUGHT:boolean index did not match indexed array along dimension 0; dimension is 360 but corresponding boolean dimension is 368640
Traceback (most recent call last):
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/tasks/IntegrationTask.py", line 942, in __integratingFinished
    self.__updateGUIWithIntegrationResult(self.__integrationProcess)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/tasks/IntegrationTask.py", line 953, in __updateGUIWithIntegrationResult
    self._plot.setIntegrationProcess(integrationProcess)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/tasks/IntegrationTask.py", line 740, in setIntegrationProcess
    result2d_intensity[result2d.count == 0] = float("NaN")
IndexError: boolean index did not match indexed array along dimension 0; dimension is 360 but corresponding boolean dimension is 368640
```

**Comment by vallsv** [comment]
Could be cause the axes are not the same between 2d data integration and 2d mask integration
