### ISSUE TITLE
[calib2] Can't save npt

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#1206]
```
ERROR:pyFAI.gui.tasks.PeakPickingTask:Backtrace
Traceback (most recent call last):
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/tasks/PeakPickingTask.py", line 1147, in __savePeaksAsFile
    controlPoints = model_transform.createControlPoints(self.model())
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/helper/model_transform.py", line 60, in createControlPoints
    controlPoints.append(points=points, ring=ringNumber)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/control_points.py", line 127, in append
    gpt = PointGroup(points, ring, annotate, plot)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/control_points.py", line 499, in __init__
    if points:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by kif** [comment]
Those are supposed to be a list, not a numpy array ... would it make sense to accept numpy arrays ?

There is a simple fix:
```
diff --git a/pyFAI/control_points.py b/pyFAI/control_points.py
index 1abe2d8f..b87eb207 100644
--- a/pyFAI/control_points.py
+++ b/pyFAI/control_points.py
@@ -38,7 +38,7 @@ __author__ = "Jérôme Kieffer"
 __contact__ = "Jerome.Kieffer@ESRF.eu"
 __license__ = "MIT"
 __copyright__ = "European Synchrotron Radiation Facility, Grenoble, France"
-__date__ = "06/03/2018"
+__date__ = "26/04/2019"
 __status__ = "development"
 __docformat__ = 'restructuredtext'
 
@@ -496,8 +496,8 @@ class PointGroup(object):
         :param plot: reference to the matplotlib plot
         :param force_label: allows to enforce the label
         """
-        if points:
-            self.points = points
+        if points is not None:
+            self.points = [i for i in points]
         else:
             self.points = []
         if force_label:
```
