### ISSUE TITLE
[test] Problem with cl scripts with histogram2d tests

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#1219]
```
ERROR: test_histogram2d (pyFAI.opencl.test.test_ocl_histo.TestOclHistogram)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/opencl/test/test_ocl_histo.py", line 145, in test_histogram2d
    integrator = OCL_Histogram2d(tth, chi, *npt, devicetype="cpu")
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/opencl/azim_hist.py", line 1344, in __init__
    self.compile_kernels()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/opencl/azim_hist.py", line 924, in compile_kernels
    OpenclProcessing.compile_kernels(self, kernels, compile_options)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/opencl/processing.py", line 262, in compile_kernels
    self.program = pyopencl.Program(self.ctx, kernel_src).build(options=compile_options)
  File "/home/valls/.local/lib/python3.5/site-packages/pyopencl/__init__.py", line 490, in build
    options_bytes=options_bytes, source=self._source)
  File "/home/valls/.local/lib/python3.5/site-packages/pyopencl/__init__.py", line 534, in _build_and_catch_errors
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz' on 'AMD Accelerated Parallel Processing' at 0x1a70750>:

"/tmp/OCLNLW3QZ.cl", line 96: warning: variable "ah" was declared but never
          referenced
      float ah = a.s0;
            ^

"/tmp/OCLNLW3QZ.cl", line 97: warning: variable "al" was declared but never
          referenced
      float al  = a.s1;
            ^

"/tmp/OCLNLW3QZ.cl", line 1002: error: no instance of overloaded function
          "atomic_cmpxchg" matches the argument list
            argument types are: (volatile __global ulong *, ulong, ulong)
         current.u64  = atomic_cmpxchg( (volatile __global unsigned long *)addr,
                        ^

"/tmp/OCLNLW3QZ.cl", line 73: warning: function "compensated_mul" was declared
          but never referenced
  static inline float2 compensated_mul(float2 a, float2 b)
                       ^

"/tmp/OCLNLW3QZ.cl", line 86: warning: function "compensated_inv" was declared
          but never referenced
  static inline float2 compensated_inv(float2 a)
                       ^

"/tmp/OCLNLW3QZ.cl", line 94: warning: function "compensated_div" was declared
          but never referenced
  static inline float2 compensated_div(float2 a, float2 b)
                       ^

"/tmp/OCLNLW3QZ.cl", line 106: warning: function "comp_dot2" was declared but
          never referenced
  static inline float2 comp_dot2(float2 a, float2 b)
                       ^

"/tmp/OCLNLW3QZ.cl", line 112: warning: function "comp_dot3" was declared but
          never referenced
  static inline float2 comp_dot3(float3 a, float3 b)
                       ^

"/tmp/OCLNLW3QZ.cl", line 118: warning: function "comp_dot4" was declared but
          never referenced
  static inline float2 comp_dot4(float4 a, float4 b)
                       ^

"/tmp/OCLNLW3QZ.cl", line 125: warning: function "comp_dot8" was declared but
          never referenced
  static inline float2 comp_dot8(float8 a, float8 b)
                       ^

"/tmp/OCLNLW3QZ.cl", line 135: warning: function "comp_dot16" was declared but
          never referenced
  static inline float2 comp_dot16(float16 a, float16 b)
                       ^

1 error detected in the compilation of "/tmp/OCLNLW3QZ.cl".
Frontend phase failed compilation.

(options: -D NBINS=10800 -D NIMAGE=94965 -D WORKGROUP_SIZE=32 -I /home/valls/.local/lib/python3.5/site-packages/pyopencl/cl)
(source saved as /tmp/tmpfd6d7dpy.cl)

Stderr:
INFO:silx.opencl.processing:6.182MB are needed on device: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz,  which has 16782.250MB
INFO:silx.opencl.processing:Compiling file ['pyfai:openCL/kahan.cl', 'pyfai:openCL/preprocess.cl', 'pyfai:openCL/ocl_histo.cl'] with options -D NBINS=10800  -D NIMAGE=94965 -D WORKGROUP_SIZE=32
```

**Comment by kif** [comment]
After some investigations, this is a bug in AMD's driver which claims that it supports 64-bit atomic operation but actually doesn't. As this driver no more maintained (the latest version is from jessie-backports, dropped in stretch and buster), maybe we won't put a lot of effort in fixing this bug.

Nota: I managed to reproduce the bug with driver 1912.5 (sse2,avx) 
https://packages.debian.org/jessie/amd-opencl-icd

**Comment by vallsv** [comment]
Debugged with @kif. This CPU AMD driver from 2015 was buggy. It was exposing `cl_khr_int64_base_atomics` without supporting it.

Relative to  #1201

**Comment by kif** [comment]
Maybe there is a "simple" while not that clean workaround...
