### ISSUE TITLE
[calib2] Bug when moving mouse on Moving mouse fit screen without geometry

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#1258]
```
ERROR:pyFAI-calib2.UNCAUGHT:ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
Traceback (most recent call last):
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/tasks/GeometryTask.py", line 715, in __mouseMoved
    self.__statusBar.setValues(x, y, value, None, None)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/tasks/GeometryTask.py", line 124, in setValues
    if not numpy.isnan(tth):
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by vallsv** [comment]
Fixed by 1b2676710eff06b052239e604925083b99ab88f3
