### ISSUE TITLE
[pyFAI-calib2] issue with calibration (probably the display of the ring after the fit)

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1366]
Context: calibration of a 3D detector (i.e. not flat) loaded from a Nexus file where binning (2x2)  is also applied which would explain the broadcasting error.
```
ERROR:pyFAI-calib2.UNCAUGHT:operands could not be broadcast together with shapes (3008000,3) (12032000,3) 
Traceback (most recent call last):
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/pyFAI/gui/tasks/GeometryTask.py", line 972, in __geometryCustomed
    state.update(calibration)
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/pyFAI/gui/tasks/GeometryTask.py", line 220, in update
    self.__poni = calibration.getPoni()
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/pyFAI/gui/helper/RingCalibration.py", line 389, in getPoni
    solidAngle = self.__geoRef.solidAngleArray(shape=self.__image.shape)
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/pyFAI/geometry.py", line 1150, in solidAngleArray
    shape, dtype=numpy.float32)
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/numpy/core/numeric.py", line 1809, in fromfunction
    return function(*args, **kwargs)
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/pyFAI/geometry.py", line 1122, in diffSolidAngle
    cosa = self._cached_array["cos_incidence"] = self.cos_incidence(d1, d2)
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/pyFAI/geometry.py", line 1078, in cos_incidence
    return (t * orth).sum(axis=-1).reshape(d1.shape)
ValueError: operands could not be broadcast together with shapes (3008000,3) (12032000,3) 
```

Example files and test case by email

**Comment by kif** [comment]
The calibration with the CLI worked like a charm, I didn't use it for a year.

**Comment by kif** [comment]
I managed to reproduce the bug without the GUI

**Comment by kif** [comment]
The detector config does not contain the binning information

**Comment by vallsv** [comment]
So the created detector object do not fit the data? That's just that?
That's something which should be anyway protected in both applications.

**Comment by kif** [comment]
My bad, the binning has to be stored inside the NexusDetector, not outside. Finally I am not sure this is a bug.

**Comment by vallsv** [comment]
The application should be anyway resilient.

Could it be because the guess binning is not called, or not available for the nexus detector? Maybe it is pointless for nexus description, ii dont really remember.
Cause usually we don't really have to care about the binning.

**Comment by kif** [comment]
The guess-binning could be called, except that where it fails, I am not sure about the availability of the image.

**Comment by kif** [comment]
In the CLI, the traceback is:
```
Traceback (most recent call last):
  File "/opt/VirtualEnv/py37/bin/pyFAI-calib", line 8, in <module>
    sys.exit(main())
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/pyFAI/app/calib.py", line 62, in main
    c.gui_peakPicker()
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/pyFAI/gui/cli_calibration.py", line 1501, in gui_peakPicker
    self.set_data(self.peakPicker.finish(self.pointfile))
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/pyFAI/gui/cli_calibration.py", line 1321, in set_data
    self.refine()
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/pyFAI/gui/cli_calibration.py", line 1598, in refine
    AbstractCalibration.refine(self)
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/pyFAI/gui/cli_calibration.py", line 748, in refine
    dsa = self.geoRef.solidAngleArray(self.peakPicker.shape)
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/pyFAI/geometry.py", line 1150, in solidAngleArray
    shape, dtype=numpy.float32)
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/numpy/core/numeric.py", line 1809, in fromfunction
    return function(*args, **kwargs)
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/pyFAI/geometry.py", line 1122, in diffSolidAngle
    cosa = self._cached_array["cos_incidence"] = self.cos_incidence(d1, d2)
  File "/opt/VirtualEnv/py37/lib/python3.7/site-packages/pyFAI/geometry.py", line 1078, in cos_incidence
    return (t * orth).sum(axis=-1).reshape(d1.shape)
ValueError: operands could not be broadcast together with shapes (3008000,3) (12032000,3) 
```

**Comment by vallsv** [comment]
For the GUI, `guess_binning` is supposed to return True in case the data match the detector, else i am pretty sure the GUI will complain and will request to fix the detector of the input image.

**Comment by kif** [comment]
The `guess_binning` returns actually `True`.

**Comment by vallsv** [comment]
Yes, but the code is from the `Detector` class, maybe in the case of `NexusDetector` there is special things to do, or attributes are not synchronized.

For example if you think the binning should always come from the detector description, it could always return False if detector size and image are the same.

**Comment by kif** [comment]
I think I found the bug: Geometry.cos_incidence has 90% of the code hidden if the detector is flat (which is usually the case).
This test case is the first time we have both binning and 3D detector.

If the detector is not planar it calculates the normal of every single pixel to calculate the actual solid angle.

Except that here the detector is binned and one needs to take into account that we need to regroup the pixels.

**Comment by kif** [comment]
That's it: when we first calculate the coordinates of the center of the pixels, the answer is correct:
https://github.com/silx-kit/pyFAI/blob/master/pyFAI/geometry.py#L1050
```
            # Calculate the sample-pixel vector (center of pixel) and norm it
            z, y, x = self.calc_pos_zyx(d0=None, d1=d1, d2=d2, corners=False)
```
But a few lines later, we calculate the normal of the pixel, the size is the unbinned one.
https://github.com/silx-kit/pyFAI/blob/master/pyFAI/geometry.py#L1059
```
            # extract the 4 corners of each pixel and calculate the cross product of the diagonal to get the normal
            z, y, x = self.calc_pos_zyx(d0=None, d1=d1, d2=d2, corners=True)
```
So the bug is clearly on my side

**Comment by vallsv** [comment]
All is on your side now anyway ;-)
Nice catch.

**Comment by kif** [comment]
This implies that one needs to bin and unbin 3D detectors (those are 4D arrays).
I'll get an aspirin first !

**Comment by vallsv** [comment]
^_^
