### ISSUE TITLE
pyFAI-calib2 with Eiger 4M

### ISSUE THREAD

**Issue by RGBYCP** [silx-kit/pyFAI#1429]
I noticed pyFAI-calib2 suggests for an Eiger 4M 2167 x 2070 px. On the Dectris website it says 2068 x 2162
My measured AgBe file has 2162 x 2068 pixel. 
I create a mask and when I enter the last menu of pyFAI I get the following error below.
I also noticed that the mask that is automatically created does not cover completely the gaps of the Eiger used. 
I think the reason could be the discrepancy in the pixels.
I configured a manual detector with 2162x2068 pixel and the error message disappears. 

Error message:
Traceback (most recent call last):
  File "/mxn/groups/pub/sw/pkg/GCC-7.3.0-2.30-OpenMPI-3.1.1/Python-3.6.6-pyfai-0.19.0/lib/python3.6/site-packages/pyFAI/gui/tasks/IntegrationTask.py", line 237, in run
    polarization_factor=self.__polarizationFactor)
  File "/mxn/groups/pub/sw/pkg/GCC-7.3.0-2.30-OpenMPI-3.1.1/Python-3.6.6-pyfai-0.19.0/lib/python3.6/site-packages/pyFAI/utils/decorators.py", line 86, in wrapper
    return func(*args, **kwargs)
  File "/mxn/groups/pub/sw/pkg/GCC-7.3.0-2.30-OpenMPI-3.1.1/Python-3.6.6-pyfai-0.19.0/lib/python3.6/site-packages/pyFAI/azimuthalIntegrator.py", line 2219, in _integrate2d_legacy
    unit=unit, split=split)
  File "/mxn/groups/pub/sw/pkg/GCC-7.3.0-2.30-OpenMPI-3.1.1/Python-3.6.6-pyfai-0.19.0/lib/python3.6/site-packages/pyFAI/azimuthalIntegrator.py", line 898, in setup_CSR
    assert mask.shape == shape
AssertionError:

**Comment by kif** [comment]
On Sat, 14 Nov 2020 10:01:59 -0800
RGBYCP <notifications@github.com> wrote:

> I noticed pyFAI-calib2 suggests for an Eiger 4M 2167 x 2070 px. On the Dectris website it says 2068 x 2162
> My measured AgBe file has 2162 x 2068 pixel. 
> I create a mask and when I enter the last menu of pyFAI I get the following error below.
> I also noticed that the mask that is automatically created does not cover completely the gaps of the Eiger used. 
> I think the reason could be the discrepancy in the pixels.
> I configured a manual detector with 2162x2068 pixel and the error message disappears. 

You are probably using an Eiger2, not and Eiger(1) ... They don't have the same shape.

The github master version already includes the support for this detector:
https://github.com/silx-kit/pyFAI/blob/master/pyFAI/detectors/_dectris.py#L290
but no release include it yet. 

Beside this, the fully manual detector definition should work (without any mention to the Eiger).

**Comment by RGBYCP** [comment]
That is right. In my PyFAI version is only Eiger listed, I could not see Eiger2 in the list of detectors.
I can say, I did not have this error with the mask at the end when manually defining the Eiger2 detector.
Thank you for your explanation.
