### ISSUE TITLE
CSR/LUT with fullsplit povides empty sparse matrices ...

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1600]
Spotted on deabin10 with elder version of cython. 
The bug is that the matrix is empty, not the contiguity of the matrix.

```
kieffer@hyperion:~/workspace/pyFAI$ python3 run_tests.py -x pyFAI.test.test_sparse.TestSparseIntegrate2d.test_sparse_fullsplit -v
WARNING:py.warnings:/usr/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)

WARNING:py.warnings:/usr/lib/python3/dist-packages/h5py/_hl/base.py:19: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import (Mapping, MutableMapping, KeysView,

INFO:root:Generating grammar tables from /usr/lib/python3.7/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python3.7/lib2to3/PatternGrammar.txt
INFO:pyFAI.setup:Use setuptools with cython
INFO:pyFAI.setup:Use setuptools.setup
WARNING:run_tests:Building pyFAI to /users/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7
INFO:root:Generating grammar tables from /usr/lib/python3.7/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python3.7/lib2to3/PatternGrammar.txt
INFO:pyFAI.setup:Use setuptools with cython
INFO:pyFAI.setup:Install requires: numpy numpy>=1.16.2
running build
running build_py
running build_ext
WARNING:run_tests:Patched sys.path, added: '/users/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7'
WARNING:run_tests:Test pyFAI 0.21.0-dev2 from /users/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7/pyFAI
INFO:pyFAI.method_registry:Degrading method from Method(dim=1, split='pseudo', algo='histogram', impl='*', target=None) -> Method(dim=1, split='bbox', algo='histogram', impl='*', target=None)
INFO:pyFAI.geometry:Unable to parse /tmp/pyFAI_testdata_kieffer/Pilatus1M.poni as JSON file, defaulting to PoniParser
test_sparse_fullsplit (pyFAI.test.test_sparse.TestSparseIntegrate2d) ... fullSplit2D_engine 3.0071765e-317 0.19220125675201416 -3.1367719173431396 3.140857219696045
0.00038440255932837886 0.017437859754051505
CSR
INFO:pyFAI.azimuthalIntegrator:AI.integrate2d_ng: Resetting Cython integrator because of first initialization
full
FullSplitIntegrator 0.0 0.19220125675201416 -3.1367719173431396 3.140857219696045
3.1408575941154027 -3.1367719173431396 0.00038440255932837886 0.017437859754051505
Freshly built integrator <pyFAI.ext.splitPixelFullCSR.FullSplitCSR_2d object at 0x1df8448> dict_keys([IntegrationMethod(2d int, full split, CSR, cython)])
IntegrationMethod(2d int, full split, CSR, cython)
ERROR:pyFAI.test.test_sparse:Numerical values are odd (R=3.0)... please refine this test!
LUT
INFO:pyFAI.azimuthalIntegrator:AI.integrate2d_ng: Resetting Cython integrator because of first initialization
403 full
FullSplitIntegrator 0.0 0.19220125675201416 -3.1367719173431396 3.140857219696045
[('idx', '<i4'), ('coef', '<f4')] (180000, 0) (0, 8)
[]
(array([], dtype=float32), array([], dtype=int32), array([0, 0, 0, ..., 0, 0, 0], dtype=int32))
ERROR

======================================================================
ERROR: test_sparse_fullsplit (pyFAI.test.test_sparse.TestSparseIntegrate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7/pyFAI/test/test_sparse.py", line 193, in test_sparse_fullsplit
    obt = self.integrate(method=("full", m, "cython"))
  File "/users/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7/pyFAI/test/test_sparse.py", line 153, in integrate
    delta_dummy=1)
  File "/users/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7/pyFAI/azimuthalIntegrator.py", line 2269, in integrate2d_ng
    scale=False)
  File "/users/kieffer/workspace/pyFAI/build/lib.linux-x86_64-3.7/pyFAI/azimuthalIntegrator.py", line 414, in setup_LUT
    chiDiscAtPi=self.chiDiscAtPi)
  File "pyFAI/ext/splitPixelFullLUT.pyx", line 171, in pyFAI.ext.splitPixelFullLUT.HistoLUT2dFullSplit.__init__
    LutIntegrator.__init__(self, lut, self.pos.shape[0], empty or 0.0)
  File "pyFAI/ext/LUT_common.pxi", line 60, in pyFAI.ext.splitPixelFullLUT.LutIntegrator.__init__
    lut_t[:, ::1] lut,
ValueError: Buffer and memoryview are not contiguous in the same dimension.

----------------------------------------------------------------------
Ran 1 test in 0.580s

FAILED (errors=1)
```

**Comment by kif** [comment]
Bug introduced by #1599 where the numerical outcome of the test was not validated.

**Comment by kif** [comment]
The result of the test is wrong in newer version of cython too, it just silences the bug !
