### ISSUE TITLE
0.21.2 AssertionError: mask size

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#1656]
Hello while running the test without the opencl, I got this error message

```
======================================================================
FAIL: test_write_h5_overwrite_mode (pyFAI.test.test_integrate_app.TestIntegrateApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyfai-0.21.2+dfsg1/build/lib.linux-x86_64-3.10/pyFAI/test/test_integrate_app.py", line 292, in test_write_h5_overwrite_mode
    pyFAI.app.integrate.integrate_shell(options, [file1])
  File "/tmp/pyfai-0.21.2+dfsg1/build/lib.linux-x86_64-3.10/pyFAI/app/integrate.py", line 753, in integrate_shell
    result = process(filenames, output, config, monitor_name, observer, options.write_mode)
  File "/tmp/pyfai-0.21.2+dfsg1/build/lib.linux-x86_64-3.10/pyFAI/app/integrate.py", line 701, in process
    result = worker.process(data=data_info.data,
  File "/tmp/pyfai-0.21.2+dfsg1/build/lib.linux-x86_64-3.10/pyFAI/worker.py", line 405, in process
    raise err
  File "/tmp/pyfai-0.21.2+dfsg1/build/lib.linux-x86_64-3.10/pyFAI/worker.py", line 380, in process
    integrated_result = self._processor(**kwarg)
  File "/tmp/pyfai-0.21.2+dfsg1/build/lib.linux-x86_64-3.10/pyFAI/azimuthalIntegrator.py", line 1510, in integrate1d_ng
    intpl = integr(weights=data, variance=variance,
  File "pyFAI/ext/splitBBox.pyx", line 334, in pyFAI.ext.splitBBox.histoBBox1d_engine
    assert mask.size == size, "mask size"
AssertionError: mask size
```

**Comment by kif** [comment]
Issue fixed in v0.21.3
