### ISSUE TITLE
Non equivalence of geometry engines.

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1667]
Test failed with random geometry on windows:

FAIL: test_corner_array (pyFAI.test.test_geometry.TestFastPath) (data={'dist': 0.11039952869837454, 'poni1': -0.38423040535163044, 'poni2': 0.4051022810084228, 'rot1': 1.2554278759473345, 'rot2': 0.8567242666283486, 'rot3': 0.013005462038307783, 'wavelength': 1e-10, 'detector': 'Pilatus100k'}, space=r_m)
Test pyFAI.geometry.corner_array with full detectors
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\pyfai\build\lib.win-amd64-3.7\pyFAI\test\test_geometry.py", line 362, in test_corner_array
    self.assertLess(cnt_delta_a, count_a, "data:%s, space: %s cnt_delta_a: %s" % (data, space, cnt_delta_a))
AssertionError: 44 not less than 17 : data:{'dist': 0.11039952869837454, 'poni1': -0.38423040535163044, 'poni2': 0.4051022810084228, 'rot1': 1.2554278759473345, 'rot2': 0.8567242666283486, 'rot3': 0.013005462038307783, 'wavelength': 1e-10, 'detector': 'Pilatus100k'}, space: r_m cnt_delta_a: 44

**Comment by kif** [comment]
unable to reproduce the bug on windows py39

**Comment by kif** [comment]
I get 24µ uncertainty on this geometry:
```
Detector Pilatus 100k	 PixelSize= 1.720e-04, 1.720e-04 m
Wavelength= 1.000000e-10m
SampleDetDist= 1.103995e-01m	PONI= -3.842304e-01, 4.051023e-01m	rot1=1.255428  rot2= 0.856724  rot3= 0.013005 rad
DirectBeamDist= 543.483mm	Center: x=387.908, y=153.956 pix	Tilt=78.280 deg  tiltPlanRotation= 129.485 deg
```
Same numerical value between win_py37 & lin_py39

**Comment by kif** [comment]
Another one:
```
FAIL: test_corner_array (pyFAI.test.test_geometry.TestFastPath.test_corner_array) (data={'dist': 0.021399832882248886, 'poni1': -0.019660632387274446, 'poni2': 0.0602874093444602, 'rot1': -0.3594355186242809, 'rot2': 1.1441614774818238, 'rot3': 1.3586226684750962, 'wavelength': 1e-10, 'detector': 'Pilatus100k'}, space=r_m)
Test pyFAI.geometry.corner_array with full detectors
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pyFAI/pyFAI/build/lib/python3.11/site-packages/pyFAI/test/test_geometry.py", line 365, in test_corner_array
    self.assertLess(cnt_delta_a, count_a, "data:%s, space: %s cnt_delta_a: %s" % (data, space, cnt_delta_a))
AssertionError: 28 not less than 17 : data:{'dist': 0.021399832882248886, 'poni1': -0.019660632387274446, 'poni2': 0.0602874093444602, 'rot1': -0.3594355186242809, 'rot2': 1.1441614774818238, 'rot3': 1.3586226684750962, 'wavelength': 1e-10, 'detector': 'Pilatus100k'}, space: r_m cnt_delta_a: 28

======================================================================
FAIL: test_corner_array (pyFAI.test.test_geometry.TestFastPath.test_corner_array) (data={'dist': 0.021399832882248886, 'poni1': -0.019660632387274446, 'poni2': 0.0602874093444602, 'rot1': -0.3594355186242809, 'rot2': 1.1441614774818238, 'rot3': 1.3586226684750962, 'wavelength': 1e-10, 'detector': 'Pilatus100k'}, space=2th_rad)
Test pyFAI.geometry.corner_array with full detectors
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pyFAI/pyFAI/build/lib/python3.11/site-packages/pyFAI/test/test_geometry.py", line 365, in test_corner_array
    self.assertLess(cnt_delta_a, count_a, "data:%s, space: %s cnt_delta_a: %s" % (data, space, cnt_delta_a))
AssertionError: 28 not less than 17 : data:{'dist': 0.021399832882248886, 'poni1': -0.019660632387274446, 'poni2': 0.0602874093444602, 'rot1': -0.3594355186242809, 'rot2': 1.1441614774818238, 'rot3': 1.3586226684750962, 'wavelength': 1e-10, 'detector': 'Pilatus100k'}, space: 2th_rad cnt_delta_a: 28

======================================================================
FAIL: test_corner_array (pyFAI.test.test_geometry.TestFastPath.test_corner_array) (data={'dist': 0.021399832882248886, 'poni1': -0.019660632387274446, 'poni2': 0.0602874093444602, 'rot1': -0.3594355186242809, 'rot2': 1.1441614774818238, 'rot3': 1.3586226684750962, 'wavelength': 1e-10, 'detector': 'Pilatus100k'}, space=q_A^-1)
Test pyFAI.geometry.corner_array with full detectors
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pyFAI/pyFAI/build/lib/python3.11/site-packages/pyFAI/test/test_geometry.py", line 365, in test_corner_array
    self.assertLess(cnt_delta_a, count_a, "data:%s, space: %s cnt_delta_a: %s" % (data, space, cnt_delta_a))
AssertionError: 28 not less than 17 : data:{'dist': 0.021399832882248886, 'poni1': -0.019660632387274446, 'poni2': 0.0602874093444602, 'rot1': -0.3594355186242809, 'rot2': 1.1441614774818238, 'rot3': 1.3586226684750962, 'wavelength': 1e-10, 'detector': 'Pilatus100k'}, space: q_A^-1 cnt_delta_a: 28
```
