### ISSUE TITLE
BUG: pyFAI-calib2 cannot be started

### ISSUE THREAD

**Issue by st3107** [silx-kit/pyFAI#1743]
I encountered a bug when running the `pyFAI-calib2` in the git bash on windows. Here is what I did.

```
$ pyfai-calib2 example_data/Ni.tiff
INFO:numexpr.utils:NumExpr defaulting to 4 threads.
WARNING:silx.DEPRECATION:module C:\Users\simon\miniconda3\envs\pdfstream\lib\site-packages\silx\gui\plot\matplotlib\__init__.py is deprecated since silx version 0.14.0. Use 'silx.gui.utils.matplotlib' instead.
  File "C:\Users\simon\miniconda3\envs\pdfstream\lib\site-packages\silx\gui\plot\matplotlib\__init__.py", line 32, in <module>
    deprecated_warning(type_='module',
WARNING:silx.opencl.common:Unable to import pyOpenCl. Please install it from: https://pypi.org/project/pyopencl
INFO:pyFAI.method_registry:Degrading method from Method(dim=1, split='pseudo', algo='histogram', impl='*', target=None) -> Method(dim=1, split='bbox', algo='histogram', impl='*', target=None)
ERROR:pyFAI-calib2.UNCAUGHT:__init__() missing 1 required positional argument: 'plot'
Traceback (most recent call last):
  File "C:\Users\simon\miniconda3\envs\pdfstream\Scripts\pyfai-calib2-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\simon\miniconda3\envs\pdfstream\lib\site-packages\pyFAI\app\calib2.py", line 594, in main
    window = CalibrationWindow(context)
  File "C:\Users\simon\miniconda3\envs\pdfstream\lib\site-packages\pyFAI\gui\CalibrationWindow.py", line 152, in __init__
    self.__tasks = self.createTasks()
  File "C:\Users\simon\miniconda3\envs\pdfstream\lib\site-packages\pyFAI\gui\CalibrationWindow.py", line 259, in createTasks
    ExperimentTask(),
  File "C:\Users\simon\miniconda3\envs\pdfstream\lib\site-packages\pyFAI\gui\tasks\AbstractCalibrationTask.py", line 46, in __init__
    self._initGui()
  File "C:\Users\simon\miniconda3\envs\pdfstream\lib\site-packages\pyFAI\gui\tasks\ExperimentTask.py", line 70, in _initGui
    self.__plot = self.__createPlot(parent=self._imageHolder)
  File "C:\Users\simon\miniconda3\envs\pdfstream\lib\site-packages\pyFAI\gui\tasks\ExperimentTask.py", line 96, in __createPlot
    plot = silx.gui.plot.PlotWidget(parent=parent)
  File "C:\Users\simon\miniconda3\envs\pdfstream\lib\site-packages\silx\gui\plot\PlotWidget.py", line 391, in __init__
    self._backend = self.__getBackendClass(backend)(self, self)
  File "C:\Users\simon\miniconda3\envs\pdfstream\lib\site-packages\silx\gui\plot\backends\BackendMatplotlib.py", line 1339, in __init__
    FigureCanvasQTAgg.__init__(self, self.fig)
  File "C:\Users\simon\miniconda3\envs\pdfstream\lib\site-packages\matplotlib\backends\backend_qt.py", line 209, in __init__
    super().__init__(figure=figure)
  File "C:\Users\simon\miniconda3\envs\pdfstream\lib\site-packages\matplotlib\backend_bases.py", line 1656, in __init__
    super().__init__()  # Typically the GUI widget init (if any).
TypeError: __init__() missing 1 required positional argument: 'plot'
```

This bug is related to the GUI backend. When the `FigureCanvasQTAgg` is initialized, it tried to do the `super().__init__()` for the GUI widget class in matpotlib backend. However, this needs a `plot` argument but there is no such value in the code.

I first suspect that it is because I didn't use the correct matplotlib backend and thus I set the backend using the environment variable.

``export MPLBACKEND=Qt5Agg``

However, this doesn't solve the problem and the bug is still there. Thus, I post this issue asking for a solution.

Below is my conda environment.

```
$ conda list
# packages in environment at C:\Users\simon\miniconda3\envs\pyfai:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.9.24            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.5            py39h1f6ef14_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
debugpy                   1.6.3            py39h415ef7b_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.1.0              pyhd8ed1ab_0    conda-forge
fabio                     0.14.0           py39h5d4886f_0    conda-forge
fonttools                 4.37.4           py39ha55989b_0    conda-forge
freetype                  2.12.1               h546665d_0    conda-forge
glymur                    0.11.7             pyhd8ed1ab_0    conda-forge
h5py                      3.7.0           nompi_py39h7fe8f52_101    conda-forge
hdf5                      1.12.2          nompi_h2a0e4a3_100    conda-forge
hdf5plugin                3.3.1            py39hf79b81a_1    conda-forge
icu                       68.2                 h0e60522_0    conda-forge
importlib-metadata        4.11.4           py39hcbf5309_0    conda-forge
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
ipykernel                 6.16.0             pyh025b116_0    conda-forge
ipython                   8.5.0              pyh08f2357_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
jupyter_client            7.3.5              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py39hcbf5309_0    conda-forge
khronos-opencl-icd-loader 2022.09.23           h64bf75a_0    conda-forge
kiwisolver                1.4.4            py39h2e07f2f_0    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.83.1               h789b8ee_0    conda-forge
libdeflate                1.14                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
libpng                    1.6.38               h19919ed_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.39.3               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h680486a_3    conda-forge
libtiff                   4.4.0                h8e97e67_4    conda-forge
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.10.2               h99b13fb_1    conda-forge
libxslt                   1.1.35               h34f844d_0    conda-forge
libzlib                   1.2.12               hcfcfb64_3    conda-forge
lxml                      4.9.1            py39hb82d6ee_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mako                      1.2.3              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py39hb82d6ee_1    conda-forge
matplotlib                3.6.0            py39hcbf5309_0    conda-forge
matplotlib-base           3.6.0            py39haf65ace_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
mkl-service               2.4.0            py39h6b0492b_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
numexpr                   2.8.3            py39hb80d3ca_0
numpy                     1.23.3           py39h9061af7_0    conda-forge
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openssl                   1.1.1q               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0            py39hcef8f5f_2    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.2              pyhd8ed1ab_1    conda-forge
prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
psutil                    5.9.2            py39ha55989b_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyfai                     0.21.3               hd8ed1ab_0    conda-forge
pyfai-base                0.21.3           py39h2e25243_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyopencl                  2022.2.3         py39hdc8ea75_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py39hb0d2dfa_4    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
python                    3.9.13          h9a09f29_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytools                   2022.1.12          pyhd8ed1ab_0    conda-forge
pywin32                   303              py39hb82d6ee_0    conda-forge
pyzmq                     24.0.1           py39hea35a22_0    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtconsole                 5.3.2              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.3.2              pyha770c72_0    conda-forge
qtpy                      2.2.0              pyhd8ed1ab_0    conda-forge
scipy                     1.9.1            py39h316f440_0    conda-forge
setuptools                65.4.0             pyhd8ed1ab_0    conda-forge
silx                      1.0.0                hd8ed1ab_1    conda-forge
silx-base                 1.0.0            py39h2e25243_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.39.3               hcfcfb64_0    conda-forge
stack_data                0.5.1              pyhd8ed1ab_0    conda-forge
tbb                       2021.6.0             h91493d7_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tornado                   6.2              py39hb82d6ee_0    conda-forge
traitlets                 5.4.0              pyhd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022d                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py39hb82d6ee_1    conda-forge
vc                        14.2                 hb210afc_7    conda-forge
vs2015_runtime            14.29.30139          h890b9b1_7    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               hcfcfb64_3    conda-forge
zstd                      1.5.2                h7755175_4    conda-forge
```

**Comment by kif** [comment]
Hi,
I believe you hit this bug from silx: 
https://github.com/silx-kit/silx/issues/3684

Until the new release of silx is available, the easiest is to downgrade the version of matplotlib (to the latest version earlier than 3.6) or to patch silx with the very simple patch provided by Thomas at https://github.com/silx-kit/silx/commit/e40f5aa3cbf74a51e9520d46d4538ed36faca0a3

Cheers,

Jerome

**Comment by st3107** [comment]
@kif Thank you. I downgraded the matpotlib and now the pyFAI is working.

**Comment by kif** [comment]
See also: https://github.com/silx-kit/silx/issues/3689
The packaging of `silx` is ongoing, but many things has changed with the deprecation of `numpy.distutils` and making a new release is not that easy anymore. Sorry for the delay.
