### ISSUE TITLE
3 tests are broken on `armhf` reported on debian

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1754]
```
======================================================================
FAIL: test_count_csr (pyFAI.test.test_histogram.TestHistogram2d)
Test that the pixel count and the total intensity is conserved
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyFAI/test/test_histogram.py", line 339, in test_count_csr
    self.assertTrue(delta == 0, msg="check all pixels were counted")
AssertionError: False is not true : check all pixels were counted

======================================================================
FAIL: test_numpy_vs_cython_vs_csr_2d (pyFAI.test.test_histogram.TestHistogram2d)
Compare numpy histogram with cython simple implementation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyFAI/test/test_histogram.py", line 373, in test_numpy_vs_cython_vs_csr_2d
    self.assertTrue(delta_max <= self.err_max_cnt, "pixel count difference numpy/csr : max delta=%s" % delta_max)
AssertionError: False is not true : pixel count difference numpy/csr : max delta=8.0

======================================================================
FAIL: test_2d_nosplit (pyFAI.test.test_csr.TestCSR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyFAI/test/test_csr.py", line 195, in test_2d_nosplit
    self.assertLess(error.mean(), 1e-3, "img are almost the same")
AssertionError: 244.15215998872887 not less than 0.001 : img are almost the same
```

**Comment by kif** [comment]
@picca

**Comment by kif** [comment]
I have the impression those 3 tests passe on my tinkerboard, armhf, 32bits running armbian/debian11 ... 
```
jerome@tinkerboard:~/workspace/pyFAI$ python3 run_tests.py -x
INFO:root:Generating grammar tables from /usr/lib/python3.9/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python3.9/lib2to3/PatternGrammar.txt
INFO:pyFAI.setup:Use setuptools with cython
INFO:pyFAI.setup:Use setuptools.setup
WARNING:run_tests:Building pyFAI to /home/jerome/workspace/pyFAI/build/lib.linux-armv7l-3.9
INFO:root:Generating grammar tables from /usr/lib/python3.9/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python3.9/lib2to3/PatternGrammar.txt
INFO:pyFAI.setup:Use setuptools with cython
INFO:pyFAI.setup:Install requires: numpy numpy>=1.19.5
running build
running build_py
running build_ext
WARNING:run_tests:Patched sys.path, added: '/home/jerome/workspace/pyFAI/build/lib.linux-armv7l-3.9'
WARNING:run_tests:Test pyFAI 0.22.0-dev10 from /home/jerome/workspace/pyFAI/build/lib.linux-armv7l-3.9/pyFAI
WARNING:silx.opencl.common:The module pyOpenCL has been imported but can't be used here
WARNING:py.warnings:/home/jerome/workspace/pyFAI/build/lib.linux-armv7l-3.9/pyFAI/third_party/_local/transformations.py:1998: UserWarning: No module named 'pyFAI.third_party._local._transformations'
  warnings.warn(str(exc))

s..............s...s........................s....................................................................................................................................s............s.......s.s.................................................................................................................s...........................sssssssssssssssssssssssssssssss..............
======================================================================
SKIPPED: runTest (pyFAI.gui.test.SkipGuiTest)
----------------------------------------------------------------------
pyFAI.gui tests disabled (Skipped by command line)
======================================================================
SKIPPED: test_count_csr (pyFAI.test.test_histogram.TestHistogram2d)
Test that the pixel count and the total intensity is conserved
SKIPPED: test_numpy_vs_cython_vs_csr_2d (pyFAI.test.test_histogram.TestHistogram2d)
Compare numpy histogram with cython simple implementation
SKIPPED: test_2d_nosplit (pyFAI.test.test_csr.TestCSR)
----------------------------------------------------------------------
test unreliable on 32bits processor
======================================================================
SKIPPED: test_histo (pyFAI.test.test_azimuthal_integrator.TestIntergrationNextGeneration)
----------------------------------------------------------------------
Skipping TestIntergrationNextGeneration.test_histo as OpenCL method not available
======================================================================
SKIPPED: test_hexagonal_detector (pyFAI.test.test_detector.TestDetector)
----------------------------------------------------------------------
SplitPixel does not work (yet) with hexagonal pixels: pos.shape[0] == size
======================================================================
SKIPPED: test_sparse_fullsplit (pyFAI.test.test_sparse.TestSparseIntegrate2d)
----------------------------------------------------------------------
Fix this test
======================================================================
SKIPPED: test_opencl_csr (pyFAI.test.test_csr.TestCSR)
----------------------------------------------------------------------
Test on OpenCL disabled
======================================================================
SKIPPED: test_opencl (pyFAI.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
OpenCL not available
======================================================================
SKIPPED: test_add (pyFAI.opencl.test.test_addition.TestAddition)
tests the addition  kernel
SKIPPED: test_measurement (pyFAI.opencl.test.test_addition.TestAddition)
tests that all devices are working properly ...
SKIPPED: test_histogram1d (pyFAI.opencl.test.test_ocl_histo.TestOclHistogram)
tests the 1d histogram kernel
SKIPPED: test_histogram2d (pyFAI.opencl.test.test_ocl_histo.TestOclHistogram)
tests the 2D histogram kernel
SKIPPED: test_integrate_ng (pyFAI.opencl.test.test_ocl_azim_csr.TestOclAzimCSR)
tests the 1d histogram kernel, default block size
SKIPPED: test_integrate_ng_single (pyFAI.opencl.test.test_ocl_azim_csr.TestOclAzimCSR)
tests the 1d histogram kernel, default block size
SKIPPED: test_integrate_ng (pyFAI.opencl.test.test_ocl_azim_lut.TestOclAzimLUT)
tests the 1d histogram kernel
SKIPPED: test_azimuthal_peak_finder (pyFAI.opencl.test.test_peak_finder.TestOclPeakFinder)
test for peak picker with background calculate from an azimuthal sigma-clipping
SKIPPED: test_azimuthal_peak_finder_chauvenet (pyFAI.opencl.test.test_peak_finder.TestOclPeakFinder)
test for peak picker with background calculate from an azimuthal sigma-clipping
SKIPPED: test_azimuthal_peak_finder_single (pyFAI.opencl.test.test_peak_finder.TestOclPeakFinder)
test for peak picker with background calculate from an azimuthal sigma-clipping
SKIPPED: test_peakfinder (pyFAI.opencl.test.test_peak_finder.TestOclPeakFinder)
test for peakfinder
SKIPPED: test_simple_peak_finder (pyFAI.opencl.test.test_peak_finder.TestOclPeakFinder)
test for simple peak picker
----------------------------------------------------------------------
PyOpenCl is missing
======================================================================
SKIPPED: test_OpenCL_sigma_clip (pyFAI.opencl.test.test_openCL.TestMask)
SKIPPED: test_OpenCL_sparse (pyFAI.opencl.test.test_openCL.TestMask)
SKIPPED: test_histogram (pyFAI.opencl.test.test_openCL.TestMask)
SKIPPED: test_reference_book (pyFAI.opencl.test.test_openCL.TestSort)
SKIPPED: test_reference_file (pyFAI.opencl.test.test_openCL.TestSort)
SKIPPED: test_sort_all (pyFAI.opencl.test.test_openCL.TestSort)
SKIPPED: test_sort_horizontal (pyFAI.opencl.test.test_openCL.TestSort)
SKIPPED: test_sort_vertical (pyFAI.opencl.test.test_openCL.TestSort)
SKIPPED: test_dot16 (pyFAI.opencl.test.test_openCL.TestKahan)
SKIPPED: test_kahan (pyFAI.opencl.test.test_openCL.TestKahan)
SKIPPED: test_filter_hor (pyFAI.opencl.test.test_ocl_sort.TestOclSort)
SKIPPED: test_filter_vert (pyFAI.opencl.test.test_ocl_sort.TestOclSort)
SKIPPED: test_mean_hor (pyFAI.opencl.test.test_ocl_sort.TestOclSort)
SKIPPED: test_mean_vert (pyFAI.opencl.test.test_ocl_sort.TestOclSort)
SKIPPED: test_sigma_clip_hor (pyFAI.opencl.test.test_ocl_sort.TestOclSort)
SKIPPED: test_sigma_clip_vert (pyFAI.opencl.test.test_ocl_sort.TestOclSort)
SKIPPED: test_sort_hor (pyFAI.opencl.test.test_ocl_sort.TestOclSort)
SKIPPED: test_sort_vert (pyFAI.opencl.test.test_ocl_sort.TestOclSort)
----------------------------------------------------------------------
OpenCL is not available
======================================================================
SKIPPED: setUpClass (pyFAI.opencl.test.test_openCL.TestDoubleWord)
----------------------------------------------------------------------
OpenCL module (pyopencl) is not present or no device available
----------------------------------------------------------------------
Ran 386 tests in 491.079s

OK (skipped=40)
```

**Comment by kif** [comment]
A debian developer commented that this was linked to the change in the glibc on 32-bit OS ... recompiling glibc !

**Comment by kif** [comment]
Tested on arm32+debian testing pyFAI 0.21.3 tests:
```
======================================================================
FAIL: test_integrate_ng (pyFAI.opencl.test.test_ocl_azim_csr.TestOclAzimCSR)
tests the 1d histogram kernel, default block size
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyFAI/opencl/test/test_ocl_azim_csr.py", line 138, in test_integrate_ng
    self.integrate_ng(block_size=None)
  File "/usr/lib/python3/dist-packages/pyFAI/opencl/test/test_ocl_azim_csr.py", line 115, in integrate_ng
    self.assertLessEqual(delta.max(), 1, "counts are almost the same")
AssertionError: 30.0 not less than or equal to 1 : counts are almost the same

======================================================================
FAIL: test_integrate_ng_single (pyFAI.opencl.test.test_ocl_azim_csr.TestOclAzimCSR)
tests the 1d histogram kernel, default block size
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyFAI/opencl/test/test_ocl_azim_csr.py", line 145, in test_integrate_ng_single
    self.integrate_ng(block_size=1)
  File "/usr/lib/python3/dist-packages/pyFAI/opencl/test/test_ocl_azim_csr.py", line 115, in integrate_ng
    self.assertLessEqual(delta.max(), 1, "counts are almost the same")
AssertionError: 36.0 not less than or equal to 1 : counts are almost the same

----------------------------------------------------------------------
Ran 375 tests in 1202.562s
```

**Comment by kif** [comment]
Same board, same python (3.10) on the current master:
```
Ran 397 tests in 1148.708s

OK (skipped=19)
```

**Comment by kif** [comment]
Thus I believe the issue can be closed !
