### ISSUE TITLE
Error opening pyFAI-calib2 "No module named 'pyFAI.gui.widgets.ElidedLabel'"

### ISSUE THREAD

**Issue by kilir** [silx-kit/pyFAI#1775]
Hi,
I installed pyFAI according to
https://pyfai.readthedocs.io/en/0.21/operations/linux.html#installation-procedure-on-other-linux-distibution

`pyFAI-calib2` returns:

```
:~ $pyFAI-calib2
INFO:numexpr.utils:Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
WARNING:silx.DEPRECATION:module /home/rk/pyfai/lib/python3.10/site-packages/silx/gui/plot/matplotlib/__init__.py is deprecated since silx version 0.14.0. Use 'silx.gui.utils.matplotlib' instead.
  File "/home/rk/pyfai/lib/python3.10/site-packages/silx/gui/plot/matplotlib/__init__.py", line 31, in <module>
    deprecated_warning(type_='module',
INFO:pyFAI.method_registry:Degrading method from Method(dim=1, split='pseudo', algo='histogram', impl='*', target=None) -> Method(dim=1, split='bbox', algo='histogram', impl='*', target=None)
ERROR:pyFAI-calib2.UNCAUGHT:No module named 'pyFAI.gui.widgets.ElidedLabel'
Traceback (most recent call last):
  File "/home/rk/pyfai/bin/pyFAI-calib2", line 8, in <module>
    sys.exit(main())
  File "/home/rk/pyfai/lib/python3.10/site-packages/pyFAI/app/calib2.py", line 594, in main
    window = CalibrationWindow(context)
  File "/home/rk/pyfai/lib/python3.10/site-packages/pyFAI/gui/CalibrationWindow.py", line 152, in __init__
    self.__tasks = self.createTasks()
  File "/home/rk/pyfai/lib/python3.10/site-packages/pyFAI/gui/CalibrationWindow.py", line 259, in createTasks
    ExperimentTask(),
  File "/home/rk/pyfai/lib/python3.10/site-packages/pyFAI/gui/tasks/AbstractCalibrationTask.py", line 48, in __init__
    self._initGui()
  File "/home/rk/pyfai/lib/python3.10/site-packages/pyFAI/gui/tasks/ExperimentTask.py", line 55, in _initGui
    qt.loadUi(pyFAI.utils.get_ui_file("calibration-experiment.ui"), self)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/__init__.py", line 238, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/Loader/loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 1037, in parse
    actor(elem)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 828, in createUserInterface
    self.traverseWidgetTree(elem)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 264, in createWidget
    self.stack.push(self.setupObject(widget_class, parent, elem))
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 228, in setupObject
    obj = self.factory.createQObject(clsname, name, args, is_attribute)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/objcreator.py", line 100, in createQObject
    factory = self.findQObjectType(classname)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/objcreator.py", line 125, in findQObjectType
    w = module.search(classname)
  File "/home/rk/pyfai/lib/python3.10/site-packages/PyQt5/uic/Loader/qobjectcreator.py", line 113, in search
    module = __import__(mname, {}, {}, (cls,))
ModuleNotFoundError: No module named 'pyFAI.gui.widgets.ElidedLabel'

```

Other gui-parts e.g. `pyFAI-drawmask` work fine.

Any hint what I am missing would be highly appreciated. 

Cheers,
Rüdiger

**Comment by vallsv** [comment]
This component was moved from pyFAI to silx.

It means that there is a reference to the old pyFAI component inside the `.ui` files.

Not a big deal, but this have to be fixed.
