### ISSUE TITLE
bug in `sparsify-Bragg`

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1819]
```
INFO:pyFAI.method_registry:Degrading method from Method(dim=1, split='pseudo', algo='histogram', impl='*', target=None) -> Method(dim=1, split='bbox', algo='histogram', impl='*', target=None)
INFO:pyFAI.geometry.core:Unable to parse geometry.poni as JSON file, defaulting to PoniParser
INFO:silx.opencl.processing:395.371MB are needed on device: NVIDIA TITAN V,  which has 12652.839MB
INFO:silx.opencl.processing:Compiling file ['silx:opencl/doubleword.cl', 'pyfai:openCL/preprocess.cl', 'pyfai:openCL/memset.cl', 'pyfai:openCL/ocl_azim_CSR.cl', 'pyfai:openCL/sparsify.cl', 'pyfai:openCL/peakfinder.cl'] with options -D NBINS=500 -D NIMAGE=4475152
WARNING:py.warnings:/home/esrf/kieffer/.venv/py39_x86_64/lib/python3.9/site-packages/pyopencl/__init__.py:270: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  warn("Non-empty compiler output encountered. Set the "

Traceback (most recent call last):
  File "/home/esrf/kieffer/.venv/py39_x86_64/bin/sparsify-Bragg", line 8, in <module>
    sys.exit(main())
  File "/home/esrf/kieffer/.venv/py39_x86_64/lib/python3.9/site-packages/pyFAI/app/sparsify.py", line 493, in main
    res = process(options)
  File "/home/esrf/kieffer/.venv/py39_x86_64/lib/python3.9/site-packages/pyFAI/app/sparsify.py", line 472, in process
    cnt = sparsifyer.run()  #Running in main thread, not in its own
  File "/home/esrf/kieffer/.venv/py39_x86_64/lib/python3.9/site-packages/pyFAI/app/sparsify.py", line 183, in run
    if len(current.peaks):
TypeError: object of type 'NoneType' has no len()
```

Thanks Nico for the report.

**Comment by coquellen** [comment]
Thanks Jérome, 
I will give it a try soon :)
