### ISSUE TITLE
Implement 2D CSC integrator in Python

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1846]
Not that difficult ... only work

**Comment by kif** [comment]
```
ERROR: test_variance_2d (pyFAI.test.test_azimuthal_integrator.TestRange)
This test checks that the variance is actually calculated and positive
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\pyfai\venv_test\lib\site-packages\scipy\sparse\_compressed.py", line 96, in __init__
    minor_dim = self.indices.max() + 1
  File "C:\projects\pyfai\venv_test\lib\site-packages\numpy\core\_methods.py", line 41, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\projects\pyfai\venv_test\lib\site-packages\pyFAI\test\test_azimuthal_integrator.py", line 655, in test_variance_2d
    res = self.ai.integrate2d_ng(self.img, 10, 20, variance=variance, error_model=error_model, method=m)
  File "C:\projects\pyfai\venv_test\lib\site-packages\pyFAI\azimuthalIntegrator.py", line 2314, in integrate2d_ng
    cython_integr = self.setup_sparse_integrator(shape, npt, mask,
  File "C:\projects\pyfai\venv_test\lib\site-packages\pyFAI\azimuthalIntegrator.py", line 523, in setup_sparse_integrator
    return splitBBoxCSC.HistoBBox2d(pos0, dpos0, pos1, dpos1,
  File "splitBBoxCSC.pyx", line 187, in pyFAI.ext.splitBBoxCSC.HistoBBox2d.__init__
  File "C:\projects\pyfai\venv_test\lib\site-packages\scipy\sparse\_compressed.py", line 98, in __init__
    raise ValueError('unable to infer matrix dimensions') from e
ValueError: unable to infer matrix dimensions
```
