### ISSUE TITLE
pyfai-calib2 does not work with installed pyside6

### ISSUE THREAD

**Issue by tjalb** [silx-kit/pyFAI#1852]
I'm using a Mac m1 with Python 3.10. In my Python environment I had pyside6 installed and got the following error message when running pyfai-calib2:

```
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute and QSGRendererInterface::OpenGLRhi using QQuickWindow::setGraphicsApi before constructing QGuiApplication.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
ERROR:pyFAI-calib2.UNCAUGHT:'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
Traceback (most recent call last):
  File "/opt/homebrew/bin/pyfai-calib2", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/pyFAI/app/calib2.py", line 594, in main
    window = CalibrationWindow(context)
  File "/opt/homebrew/lib/python3.10/site-packages/pyFAI/gui/CalibrationWindow.py", line 152, in __init__
    self.__tasks = self.createTasks()
  File "/opt/homebrew/lib/python3.10/site-packages/pyFAI/gui/CalibrationWindow.py", line 259, in createTasks
    ExperimentTask(),
  File "/opt/homebrew/lib/python3.10/site-packages/pyFAI/gui/tasks/AbstractCalibrationTask.py", line 48, in __init__
    self._initGui()
  File "/opt/homebrew/lib/python3.10/site-packages/pyFAI/gui/tasks/ExperimentTask.py", line 55, in _initGui
    qt.loadUi(pyFAI.utils.get_ui_file("calibration-experiment.ui"), self)
  File "/opt/homebrew/lib/python3.10/site-packages/silx/gui/qt/_pyside_dynamic.py", line 232, in loadUi
    widget = loader.load(uifile)
  File "/opt/homebrew/lib/python3.10/site-packages/silx/gui/qt/_pyside_dynamic.py", line 166, in load
    self._parse_custom_widgets(uifile)
  File "/opt/homebrew/lib/python3.10/site-packages/silx/gui/qt/_pyside_dynamic.py", line 154, in _parse_custom_widgets
    for custom_widget in custom_widgets.getchildren():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

After uninstalling pyside6 pyfai-calib2 works. But this is not a good solution.

**Comment by kif** [comment]
I did manage to reproduce the bug in macmini + Python3.10

**Comment by kif** [comment]
Bug also reproduced under linux ... there are many other problems on pyside6.

**Comment by kif** [comment]
Apparently on python 3.11 linux, but not 3.10

**Comment by kif** [comment]
Apparently on python 3.11 linux, but not 3.10

**Comment by kif** [comment]
Apparently on python 3.11 linux, it is failing. but not on 3.10.
There is a change in the behavour of signal/slots between PyQt5 and PySide6:
```
ERROR: test_remove (pyFAI.gui.test.test_model.TestListModel.test_remove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/kieffer/workspace-400/pyFAI/build/lib/python3.11/site-packages/pyFAI/gui/test/test_model.py", line 90, in test_remove
    listModel.append(DataModel())
  File "/users/kieffer/workspace-400/pyFAI/build/lib/python3.11/site-packages/pyFAI/gui/model/ListModel.py", line 201, in append
    self.__fireStructureChange(event)
  File "/users/kieffer/workspace-400/pyFAI/build/lib/python3.11/site-packages/pyFAI/gui/model/ListModel.py", line 219, in __fireStructureChange
    self.changed[ChangeListEvent].emit(changeListEvent)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
IndexError: Signature "changed(PyObject)" not found for signal: "changed". Available candidates: "changed()", "changed()"
```

**Comment by kif** [comment]
@vallsv  do you have an idea on how to fix this ? i.e. make it compatible with both PyQt5 and PySide6 ?
