### ISSUE TITLE
[2023.5.0] [armel] ERROR: test_detector_instanciate (pyFAI.test.test_detector.TestDetector.test_detector_instanciate)

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#1912]
Hello Jerome, I got this error with mipsel, :))

```
======================================================================
ERROR: test_detector_instanciate (pyFAI.test.test_detector.TestDetector.test_detector_instanciate)
this method try to instantiate all the detectors
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_pyfai/build/pyFAI/test/test_detector.py", line 60, in test_detector_instanciate
    first = detector_factory(name, config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_pyfai/build/pyFAI/detectors/_common.py", line 179, in factory
    raise err
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_pyfai/build/pyFAI/detectors/_common.py", line 175, in factory
    detector = detectorClass(**config)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_pyfai/build/pyFAI/detectors/_hexagonal.py", line 134, in __init__
    HexDetector.__init__(self, pitch=pitch, pixel1=pixel1, pixel2=pixel2, max_shape=max_shape)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_pyfai/build/pyFAI/detectors/_hexagonal.py", line 94, in __init__
    self.set_pixel_corners(self.build_pixel_coordinates(self.max_shape, self.pitch))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_pyfai/build/pyFAI/detectors/_hexagonal.py", line 84, in build_pixel_coordinates
    return ary*pitch
           ~~~^~~~~~
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 268. MiB for an array with shape (476, 4096, 6, 3) and data type float64
```

the full log is here

https://buildd.debian.org/status/fetch.php?pkg=pyfai&arch=mipsel&ver=2023.5.0%2Bdfsg1-3&stamp=1689683665&raw=0

I am already running these test with the --low-mem command line. So maybe this test should be skipes in low-mem

Cheers

fred

**Comment by picca** [comment]
another one

```
======================================================================
ERROR: setUpClass (pyFAI.test.test_histogram.TestHistogram2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_pyfai/build/pyFAI/test/test_histogram.py", line 259, in setUpClass
    integrator = HistoBBox2d(tth, None, chi, delta_pos1=None,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "splitBBoxCSR.pyx", line 183, in pyFAI.ext.splitBBoxCSR.HistoBBox2d.__init__
  File "sparse_builder.pxi", line 870, in pyFAI.ext.sparse_builder.SparseBuilder.to_csr
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 360. MiB for an array with shape (94371840,) and data type int32
```

I do not know if the expected size is real or due to a bug somewhere else...

**Comment by kif** [comment]
How much memory does this computer have ?
I can try to save bit but not much !
