### ISSUE TITLE
[2023.5.0][i386] ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#1915]
A test run in autopkgtest, with network access.

```
489s ======================================================================
489s ERROR: test_guess_polarization (pyFAI.test.test_azimuthal_integrator.TestFlatimage.test_guess_polarization)
489s ----------------------------------------------------------------------
489s Traceback (most recent call last):
489s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_azimuthal_integrator.py", line 356, in test_guess_polarization
489s     self.assertLess(abs(ai.guess_polarization(img)-0.5), 0.1)
489s                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
489s   File "/usr/lib/python3/dist-packages/pyFAI/azimuthalIntegrator.py", line 3512, in guess_polarization
489s     bin_idx = valid_rings[numpy.where(nbpix.max() == nbpix)[0][-1]]
489s                                       ^^^^^^^^^^^
489s   File "/usr/lib/python3/dist-packages/numpy/core/_methods.py", line 41, in _amax
489s     return umr_maximum(a, axis, None, out, keepdims, initial, where)
489s            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
489s ValueError: zero-size array to reduction operation maximum which has no identity
489s 
489s ======================================================================
489s FAIL: test_variance_2d (pyFAI.test.test_azimuthal_integrator.TestRange.test_variance_2d)
489s This test checks that the variance is actually calculated and positive
489s ----------------------------------------------------------------------
489s Traceback (most recent call last):
489s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_azimuthal_integrator.py", line 659, in test_variance_2d
489s     self.assertGreater(v.max(), 0, f"max variance is strictly positive with {res.method}")
489s AssertionError: 0.0 not greater than 0 : max variance is strictly positive with IntegrationMethod(2d int, no split, CSR, cython)
489s 

```
https://ci.debian.net/data/autopkgtest/testing/i386/p/pyfai/36183529/log.gz

**Comment by kif** [comment]
I am able to reproduce the bug in a i386/debian docker:
```
TestOptions: WITH_QT_TEST=False WITH_OPENCL_TEST=True WITH_GL_TEST=True TEST_LOW_MEM=False TEST_IS32_BIT=True
INFO:numexpr.utils:Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:pyFAI.method_registry:Degrading method from Method(dim=1, split='pseudo', algo='histogram', impl='*', target=None) -> Method(dim=1, split='bbox', algo='histogram', impl='*', target=None)
DEBUG:matplotlib:matplotlib data path: /usr/share/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/root/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:CACHEDIR=/root/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /root/.cache/matplotlib/fontlist-v330.json
test_guess_polarization (pyFAI.test.test_azimuthal_integrator.TestFlatimage.test_guess_polarization) ... DEBUG:silx.utils.ExternalResources:ExternalResources.getfile('Eiger4M.edf')
DEBUG:fabio.openimage:Attempting to open /tmp/pyFAI_testdata_root/Eiger4M.edf
DEBUG:fabio.openimage:Attempting to read frame None from /tmp/pyFAI_testdata_root/Eiger4M.edf with reader EdfImage
DEBUG:silx.utils.ExternalResources:ExternalResources.getfile('Eiger4M.poni')
INFO:pyFAI.geometry.core:Unable to parse /tmp/pyFAI_testdata_root/Eiger4M.poni as JSON file, defaulting to PoniParser
INFO:pyFAI.azimuthalIntegrator:AI.integrate2d_ng: Resetting Cython integrator because of first initialization
WARNING:pyFAI.ext.sparse_builder:Sparse matrix is empty. Expect errors or non-sense results! SparseBuilder in mode: block, blocksize: 8, nbin: 618840, total size: 0
ERROR

======================================================================
ERROR: test_guess_polarization (pyFAI.test.test_azimuthal_integrator.TestFlatimage.test_guess_polarization)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyFAI/build/lib/python3/dist-packages/pyFAI/test/test_azimuthal_integrator.py", line 356, in test_guess_polarization
    self.assertLess(abs(ai.guess_polarization(img) - 0.5), 0.1)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pyFAI/build/lib/python3/dist-packages/pyFAI/azimuthalIntegrator.py", line 3512, in guess_polarization
    bin_idx = valid_rings[numpy.where(nbpix.max() == nbpix)[0][-1]]
                                      ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numpy/core/_methods.py", line 41, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-size array to reduction operation maximum which has no identity

----------------------------------------------------------------------
Ran 1 test in 2.267s

FAILED (errors=1)

```
