### ISSUE TITLE
[2023.5.0][amd64] flaky test

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#1916]
On the Debian architecture, the CI pass or not depending on who knows... I will put here all the test involved in the failures.

```
385s ======================================================================
385s FAIL: test (pyFAI.test.test_error_model.TestErrorModel.test)
385s ----------------------------------------------------------------------
385s Traceback (most recent call last):
385s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_error_model.py", line 120, in test
385s     self.assertGreaterEqual(cormap(ref.__getattribute__(array), res.__getattribute__(array)), epsilon, f"array {array} matches for {k} vs numpy")
385s AssertionError: 0.0003204024116651927 not greater than or equal to 0.002 : array sum_variance matches for ('poisson', 'cython', 'integrate') vs numpy
385s 
```

**Comment by picca** [comment]
```
460s ======================================================================
460s FAIL: test (pyFAI.test.test_error_model.TestErrorModel.test)
460s ----------------------------------------------------------------------
460s Traceback (most recent call last):
460s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_error_model.py", line 120, in test
460s     self.assertGreaterEqual(cormap(ref.__getattribute__(array), res.__getattribute__(array)), epsilon, f"array {array} matches for {k} vs numpy")
460s AssertionError: 7.819951862310543e-05 not greater than or equal to 0.002 : array sum_normalization matches for ('poisson', 'cython', 'integrate') vs numpy
460s 
460s ----------------------------------------------------------------------
```

**Comment by picca** [comment]
```
507s ======================================================================
507s FAIL: test_guess_bins (pyFAI.test.test_azimuthal_integrator.TestFlatimage.test_guess_bins)
507s This test can be rather noisy on 32bits platforms !!!
507s ----------------------------------------------------------------------
507s Traceback (most recent call last):
507s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_azimuthal_integrator.py", line 347, in test_guess_bins
507s     self.assertEqual(res, 240, "the number of bins found is correct (240)")
507s AssertionError: 237 != 240 : the number of bins found is correct (240)
507s 
507s ----------------------------------------------------------------------
```

**Comment by picca** [comment]
```
340s ======================================================================
340s ERROR: test_guess_polarization (pyFAI.test.test_azimuthal_integrator.TestFlatimage.test_guess_polarization)
340s ----------------------------------------------------------------------
340s Traceback (most recent call last):
340s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_azimuthal_integrator.py", line 356, in test_guess_polarization
340s     self.assertLess(abs(ai.guess_polarization(img)-0.5), 0.1)
340s                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
340s   File "/usr/lib/python3/dist-packages/pyFAI/azimuthalIntegrator.py", line 3512, in guess_polarization
340s     bin_idx = valid_rings[numpy.where(nbpix.max() == nbpix)[0][-1]]
340s                                       ^^^^^^^^^^^
340s   File "/usr/lib/python3/dist-packages/numpy/core/_methods.py", line 41, in _amax
340s     return umr_maximum(a, axis, None, out, keepdims, initial, where)
340s            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
340s ValueError: zero-size array to reduction operation maximum which has no identity
340s 
340s ======================================================================
340s FAIL: test_count_csr (pyFAI.test.test_histogram.TestHistogram2d.test_count_csr)
340s Test that the pixel count and the total intensity is conserved
340s ----------------------------------------------------------------------
340s Traceback (most recent call last):
340s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_histogram.py", line 336, in test_count_csr
340s     self.assertTrue(delta == 0, msg="check all pixels were counted")
340s AssertionError: False is not true : check all pixels were counted
340s 
340s ======================================================================
340s FAIL: test_numpy_vs_cython_vs_csr_2d (pyFAI.test.test_histogram.TestHistogram2d.test_numpy_vs_cython_vs_csr_2d)
340s Compare numpy histogram with cython simple implementation
340s ----------------------------------------------------------------------
340s Traceback (most recent call last):
340s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_histogram.py", line 370, in test_numpy_vs_cython_vs_csr_2d
340s     self.assertTrue(delta_max <= self.err_max_cnt, "pixel count difference numpy/csr : max delta=%s" % delta_max)
340s AssertionError: False is not true : pixel count difference numpy/csr : max delta=8.0
340s 
340s ======================================================================
340s FAIL: test_variance_2d (pyFAI.test.test_azimuthal_integrator.TestRange.test_variance_2d)
340s This test checks that the variance is actually calculated and positive
340s ----------------------------------------------------------------------
340s Traceback (most recent call last):
340s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_azimuthal_integrator.py", line 659, in test_variance_2d
340s     self.assertGreater(v.max(), 0, f"max variance is strictly positive with {res.method}")
340s AssertionError: 0.0 not greater than 0 : max variance is strictly positive with IntegrationMethod(2d int, no split, CSR, cython)
340s 
340s ======================================================================
340s FAIL: test_2d_nosplit (pyFAI.test.test_csr.TestCSR.test_2d_nosplit)
340s ----------------------------------------------------------------------
340s Traceback (most recent call last):
340s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_csr.py", line 203, in test_2d_nosplit
340s     self.assertLess(error.mean(), 1e-3, "img are almost the same")
340s AssertionError: 244.15198 not less than 0.001 : img are almost the same
340s 
340s ----------------------------------------------------------------------
```

**Comment by picca** [comment]
```
585s ======================================================================
585s ERROR: test_guess_polarization (pyFAI.test.test_azimuthal_integrator.TestFlatimage.test_guess_polarization)
585s ----------------------------------------------------------------------
585s Traceback (most recent call last):
585s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_azimuthal_integrator.py", line 356, in test_guess_polarization
585s     self.assertLess(abs(ai.guess_polarization(img)-0.5), 0.1)
585s                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
585s   File "/usr/lib/python3/dist-packages/pyFAI/azimuthalIntegrator.py", line 3512, in guess_polarization
585s     bin_idx = valid_rings[numpy.where(nbpix.max() == nbpix)[0][-1]]
585s                                       ^^^^^^^^^^^
585s   File "/usr/lib/python3/dist-packages/numpy/core/_methods.py", line 41, in _amax
585s     return umr_maximum(a, axis, None, out, keepdims, initial, where)
585s            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
585s ValueError: zero-size array to reduction operation maximum which has no identity
585s 
585s ======================================================================
585s FAIL: test_count_csr (pyFAI.test.test_histogram.TestHistogram2d.test_count_csr)
585s Test that the pixel count and the total intensity is conserved
585s ----------------------------------------------------------------------
585s Traceback (most recent call last):
585s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_histogram.py", line 336, in test_count_csr
585s     self.assertTrue(delta == 0, msg="check all pixels were counted")
585s AssertionError: False is not true : check all pixels were counted
585s 
585s ======================================================================
585s FAIL: test_numpy_vs_cython_vs_csr_2d (pyFAI.test.test_histogram.TestHistogram2d.test_numpy_vs_cython_vs_csr_2d)
585s Compare numpy histogram with cython simple implementation
585s ----------------------------------------------------------------------
585s Traceback (most recent call last):
585s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_histogram.py", line 370, in test_numpy_vs_cython_vs_csr_2d
585s     self.assertTrue(delta_max <= self.err_max_cnt, "pixel count difference numpy/csr : max delta=%s" % delta_max)
585s AssertionError: False is not true : pixel count difference numpy/csr : max delta=8.0
585s 
585s ======================================================================
585s FAIL: test_variance_2d (pyFAI.test.test_azimuthal_integrator.TestRange.test_variance_2d)
585s This test checks that the variance is actually calculated and positive
585s ----------------------------------------------------------------------
585s Traceback (most recent call last):
585s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_azimuthal_integrator.py", line 659, in test_variance_2d
585s     self.assertGreater(v.max(), 0, f"max variance is strictly positive with {res.method}")
585s AssertionError: 0.0 not greater than 0 : max variance is strictly positive with IntegrationMethod(2d int, no split, CSR, cython)
585s 
585s ======================================================================
585s FAIL: test_2d_nosplit (pyFAI.test.test_csr.TestCSR.test_2d_nosplit)
585s ----------------------------------------------------------------------
585s Traceback (most recent call last):
585s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_csr.py", line 203, in test_2d_nosplit
585s     self.assertLess(error.mean(), 1e-3, "img are almost the same")
585s AssertionError: 244.15198 not less than 0.001 : img are almost the same
585s 
585s ----------------------------------------------------------------------
```

**Comment by picca** [comment]
```
408s ======================================================================
408s ERROR: test_guess_polarization (pyFAI.test.test_azimuthal_integrator.TestFlatimage.test_guess_polarization)
408s ----------------------------------------------------------------------
408s Traceback (most recent call last):
408s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_azimuthal_integrator.py", line 356, in test_guess_polarization
408s     self.assertLess(abs(ai.guess_polarization(img)-0.5), 0.1)
408s                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
408s   File "/usr/lib/python3/dist-packages/pyFAI/azimuthalIntegrator.py", line 3512, in guess_polarization
408s     bin_idx = valid_rings[numpy.where(nbpix.max() == nbpix)[0][-1]]
408s                                       ^^^^^^^^^^^
408s   File "/usr/lib/python3/dist-packages/numpy/core/_methods.py", line 41, in _amax
408s     return umr_maximum(a, axis, None, out, keepdims, initial, where)
408s            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
408s ValueError: zero-size array to reduction operation maximum which has no identity
408s 
408s ======================================================================
408s FAIL: test_count_csr (pyFAI.test.test_histogram.TestHistogram2d.test_count_csr)
408s Test that the pixel count and the total intensity is conserved
408s ----------------------------------------------------------------------
408s Traceback (most recent call last):
408s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_histogram.py", line 336, in test_count_csr
408s     self.assertTrue(delta == 0, msg="check all pixels were counted")
408s AssertionError: False is not true : check all pixels were counted
408s 
408s ======================================================================
408s FAIL: test_numpy_vs_cython_vs_csr_2d (pyFAI.test.test_histogram.TestHistogram2d.test_numpy_vs_cython_vs_csr_2d)
408s Compare numpy histogram with cython simple implementation
408s ----------------------------------------------------------------------
408s Traceback (most recent call last):
408s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_histogram.py", line 370, in test_numpy_vs_cython_vs_csr_2d
408s     self.assertTrue(delta_max <= self.err_max_cnt, "pixel count difference numpy/csr : max delta=%s" % delta_max)
408s AssertionError: False is not true : pixel count difference numpy/csr : max delta=8.0
408s 
408s ======================================================================
408s FAIL: test_variance_2d (pyFAI.test.test_azimuthal_integrator.TestRange.test_variance_2d)
408s This test checks that the variance is actually calculated and positive
408s ----------------------------------------------------------------------
408s Traceback (most recent call last):
408s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_azimuthal_integrator.py", line 659, in test_variance_2d
408s     self.assertGreater(v.max(), 0, f"max variance is strictly positive with {res.method}")
408s AssertionError: 0.0 not greater than 0 : max variance is strictly positive with IntegrationMethod(2d int, no split, CSR, cython)
408s 
408s ======================================================================
408s FAIL: test_2d_nosplit (pyFAI.test.test_csr.TestCSR.test_2d_nosplit)
408s ----------------------------------------------------------------------
408s Traceback (most recent call last):
408s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_csr.py", line 203, in test_2d_nosplit
408s     self.assertLess(error.mean(), 1e-3, "img are almost the same")
408s AssertionError: 244.15198 not less than 0.001 : img are almost the same
408s 
408s ----------------------------------------------------------------------
```

**Comment by picca** [comment]
```
382s ======================================================================
382s ERROR: test_guess_polarization (pyFAI.test.test_azimuthal_integrator.TestFlatimage.test_guess_polarization)
382s ----------------------------------------------------------------------
382s Traceback (most recent call last):
382s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_azimuthal_integrator.py", line 356, in test_guess_polarization
382s     self.assertLess(abs(ai.guess_polarization(img)-0.5), 0.1)
382s                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
382s   File "/usr/lib/python3/dist-packages/pyFAI/azimuthalIntegrator.py", line 3512, in guess_polarization
382s     bin_idx = valid_rings[numpy.where(nbpix.max() == nbpix)[0][-1]]
382s                                       ^^^^^^^^^^^
382s   File "/usr/lib/python3/dist-packages/numpy/core/_methods.py", line 41, in _amax
382s     return umr_maximum(a, axis, None, out, keepdims, initial, where)
382s            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
382s ValueError: zero-size array to reduction operation maximum which has no identity
382s 
382s ======================================================================
382s FAIL: test_count_csr (pyFAI.test.test_histogram.TestHistogram2d.test_count_csr)
382s Test that the pixel count and the total intensity is conserved
382s ----------------------------------------------------------------------
382s Traceback (most recent call last):
382s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_histogram.py", line 336, in test_count_csr
382s     self.assertTrue(delta == 0, msg="check all pixels were counted")
382s AssertionError: False is not true : check all pixels were counted
382s 
382s ======================================================================
382s FAIL: test_numpy_vs_cython_vs_csr_2d (pyFAI.test.test_histogram.TestHistogram2d.test_numpy_vs_cython_vs_csr_2d)
382s Compare numpy histogram with cython simple implementation
382s ----------------------------------------------------------------------
382s Traceback (most recent call last):
382s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_histogram.py", line 370, in test_numpy_vs_cython_vs_csr_2d
382s     self.assertTrue(delta_max <= self.err_max_cnt, "pixel count difference numpy/csr : max delta=%s" % delta_max)
382s AssertionError: False is not true : pixel count difference numpy/csr : max delta=8.0
382s 
382s ======================================================================
382s FAIL: test_variance_2d (pyFAI.test.test_azimuthal_integrator.TestRange.test_variance_2d)
382s This test checks that the variance is actually calculated and positive
382s ----------------------------------------------------------------------
382s Traceback (most recent call last):
382s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_azimuthal_integrator.py", line 659, in test_variance_2d
382s     self.assertGreater(v.max(), 0, f"max variance is strictly positive with {res.method}")
382s AssertionError: 0.0 not greater than 0 : max variance is strictly positive with IntegrationMethod(2d int, no split, CSR, cython)
382s 
382s ======================================================================
382s FAIL: test_2d_nosplit (pyFAI.test.test_csr.TestCSR.test_2d_nosplit)
382s ----------------------------------------------------------------------
382s Traceback (most recent call last):
382s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_csr.py", line 203, in test_2d_nosplit
382s     self.assertLess(error.mean(), 1e-3, "img are almost the same")
382s AssertionError: 244.15198 not less than 0.001 : img are almost the same
382s 
382s ----------------------------------------------------------------------
```

**Comment by picca** [comment]
```
358s ======================================================================
358s ERROR: test_guess_polarization (pyFAI.test.test_azimuthal_integrator.TestFlatimage.test_guess_polarization)
358s ----------------------------------------------------------------------
358s Traceback (most recent call last):
358s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_azimuthal_integrator.py", line 356, in test_guess_polarization
358s     self.assertLess(abs(ai.guess_polarization(img)-0.5), 0.1)
358s                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
358s   File "/usr/lib/python3/dist-packages/pyFAI/azimuthalIntegrator.py", line 3512, in guess_polarization
358s     bin_idx = valid_rings[numpy.where(nbpix.max() == nbpix)[0][-1]]
358s                                       ^^^^^^^^^^^
358s   File "/usr/lib/python3/dist-packages/numpy/core/_methods.py", line 41, in _amax
358s     return umr_maximum(a, axis, None, out, keepdims, initial, where)
358s            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
358s ValueError: zero-size array to reduction operation maximum which has no identity
358s 
358s ======================================================================
358s FAIL: test_count_csr (pyFAI.test.test_histogram.TestHistogram2d.test_count_csr)
358s Test that the pixel count and the total intensity is conserved
358s ----------------------------------------------------------------------
358s Traceback (most recent call last):
358s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_histogram.py", line 336, in test_count_csr
358s     self.assertTrue(delta == 0, msg="check all pixels were counted")
358s AssertionError: False is not true : check all pixels were counted
358s 
358s ======================================================================
358s FAIL: test_numpy_vs_cython_vs_csr_2d (pyFAI.test.test_histogram.TestHistogram2d.test_numpy_vs_cython_vs_csr_2d)
358s Compare numpy histogram with cython simple implementation
358s ----------------------------------------------------------------------
358s Traceback (most recent call last):
358s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_histogram.py", line 370, in test_numpy_vs_cython_vs_csr_2d
358s     self.assertTrue(delta_max <= self.err_max_cnt, "pixel count difference numpy/csr : max delta=%s" % delta_max)
358s AssertionError: False is not true : pixel count difference numpy/csr : max delta=8.0
358s 
358s ======================================================================
358s FAIL: test_variance_2d (pyFAI.test.test_azimuthal_integrator.TestRange.test_variance_2d)
358s This test checks that the variance is actually calculated and positive
358s ----------------------------------------------------------------------
358s Traceback (most recent call last):
358s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_azimuthal_integrator.py", line 659, in test_variance_2d
358s     self.assertGreater(v.max(), 0, f"max variance is strictly positive with {res.method}")
358s AssertionError: 0.0 not greater than 0 : max variance is strictly positive with IntegrationMethod(2d int, no split, CSR, cython)
358s 
358s ======================================================================
358s FAIL: test_2d_nosplit (pyFAI.test.test_csr.TestCSR.test_2d_nosplit)
358s ----------------------------------------------------------------------
358s Traceback (most recent call last):
358s   File "/usr/lib/python3/dist-packages/pyFAI/test/test_csr.py", line 203, in test_2d_nosplit
358s     self.assertLess(error.mean(), 1e-3, "img are almost the same")
358s AssertionError: 244.15198 not less than 0.001 : img are almost the same
358s 
358s ----------------------------------------------------------------------
```

**Comment by picca** [comment]
I am wondering if this is not a network issue during the test. It downloads the test images. And if something goes wrong ?

for example this test

```
    def test_guess_polarization(self):
	img = fabio.open(UtilsTest.getimage("Eiger4M.edf")).data
	ai = AzimuthalIntegrator.sload(UtilsTest.getimage("Eiger4M.poni"))
        self.assertLess(abs(ai.guess_polarization(img)-0.5), 0.1)
```

**Comment by kif** [comment]
Could be ... 
Since then, I changed the RNG to be random but predictable.
