### ISSUE TITLE
Expose number of corner per pixel in detector

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1957]
There is a regression related to the azimuthal angle calculation with hexagonal pixels ...

```
======================================================================
ERROR: test_hexagonal_detector (pyFAI.test.test_detector.TestDetector.test_hexagonal_detector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/kieffer/workspace-400/pyFAI/build/lib/python3.11/site-packages/pyFAI/test/test_detector.py", line 365, in test_hexagonal_detector
    ai.integrate2d(img, 500, method=("bbox", "histogram", "cython"))
  File "/users/kieffer/workspace-400/pyFAI/build/lib/python3.11/site-packages/pyFAI/azimuthalIntegrator.py", line 2439, in integrate2d_ng
    dpos1 = self.array_from_unit(shape, "delta", azimuth_unit, scale=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/kieffer/workspace-400/pyFAI/build/lib/python3.11/site-packages/pyFAI/geometry/core.py", line 1097, in array_from_unit
    out = self.delta_array(shape, unit, scale=scale)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/kieffer/workspace-400/pyFAI/build/lib/python3.11/site-packages/pyFAI/geometry/core.py", line 938, in delta_array
    corners = self.corner_array(shape, unit=unit, scale=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/kieffer/workspace-400/pyFAI/build/lib/python3.11/site-packages/pyFAI/geometry/core.py", line 791, in corner_array
    corners[..., 1] = chi
    ~~~~~~~^^^^^^^^
ValueError: could not broadcast input array from shape (476,512,6) into shape (476,512,4)
```

**Comment by kif** [comment]
Also implement an area property which provides the area of a pixel, the formula differs for squares and hexagons.

**Comment by Deadr4x** [comment]
Hello would this be good as my first issue? I would like to contribute.

**Comment by kif** [comment]
Yes, it is fairly easy ... I would do it with a attribute at the class level, 4 in general and 6 for hexagonal detectors.
Just just take care that dumping the detector to Nexus and restoring from this file handles this parameter properly.
