### ISSUE TITLE
Validate Python 3.12

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#1961]
Released up today ....

**Comment by kif** [comment]
Installation into a vitural-env:
* h5py not yet packaged, thus built from sources
* fabio not yet packages, thus built from sources
* silx not yet packages, thus built from sources -> crashes since it still refers to `distutils`

**Comment by kif** [comment]
`silx` can be installed from the `main` branch.
`pyFAI` can be built using `pip install .` or `python -m build -w` but the development tools (`run_tests.py` and `bootstrap.py` are apparently not working).

**Comment by kif** [comment]
Test are running but 4 are failing:
```
======================================================================
ERROR: test_copy (pyFAI.test.test_calibrant.TestCalibrant.test_copy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/kieffer/.venv/py312/lib/python3.12/site-packages/pyFAI/test/test_calibrant.py", line 163, in test_copy
    self.assertNotEquals(c1, c2)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TestCalibrant' object has no attribute 'assertNotEquals'. Did you mean: 'assertNotEqual'?

======================================================================
ERROR: test_not_same_dspace (pyFAI.test.test_calibrant.TestCalibrant.test_not_same_dspace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/kieffer/.venv/py312/lib/python3.12/site-packages/pyFAI/test/test_calibrant.py", line 149, in test_not_same_dspace
    self.assertNotEquals(c1, c2)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TestCalibrant' object has no attribute 'assertNotEquals'. Did you mean: 'assertNotEqual'?

======================================================================
ERROR: test_not_same_wavelength (pyFAI.test.test_calibrant.TestCalibrant.test_not_same_wavelength)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/kieffer/.venv/py312/lib/python3.12/site-packages/pyFAI/test/test_calibrant.py", line 155, in test_not_same_wavelength
    self.assertNotEquals(c1, c2)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TestCalibrant' object has no attribute 'assertNotEquals'. Did you mean: 'assertNotEqual'?

======================================================================
ERROR: test_import_all_modules (pyFAI.test.test_bug_regression.TestBugRegression.test_import_all_modules)
Try to import every single module in the package
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/kieffer/.venv/py312/lib/python3.12/site-packages/pyFAI/test/test_bug_regression.py", line 290, in test_import_all_modules
    raise err
  File "/users/kieffer/.venv/py312/lib/python3.12/site-packages/pyFAI/test/test_bug_regression.py", line 275, in test_import_all_modules
    load_source(fqn, path)
  File "/users/kieffer/.venv/py312/lib/python3.12/site-packages/pyFAI/test/test_bug_regression.py", line 80, in load_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/users/kieffer/.venv/py312/lib/python3.12/site-packages/pyFAI/gui/utils/ProxyAction.py", line 30, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```
