### ISSUE TITLE
bug in `diff_map` application

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#2071]
```
% diff_map -o test.h5 
[...]

Traceback (most recent call last):
  File "/users/kieffer/.venv/py312/bin/diff_map", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/users/kieffer/.venv/py312/lib/python3.12/site-packages/pyFAI/app/diff_map.py", line 74, in main
    window.set_config(config)
  File "/users/kieffer/.venv/py312/lib/python3.12/site-packages/pyFAI/gui/diffmap_widget.py", line 401, in set_config
    value(dico[key])
TypeError: setText(self, a0: Optional[str]): argument 1 has unexpected type 'tuple'
```

**Comment by kif** [comment]
same (more or less) with `diff_tomo` tool
