### ISSUE TITLE
Compatibility with numpy2 ....

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#2099]
At least:

```
(py311) kieffer@mac13:~/workspace/pyFAI$ ruff check src/pyFAI --select NPY201
src/pyFAI/azimuthalIntegrator.py:2952:21: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/azimuthalIntegrator.py:3029:27: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/azimuthalIntegrator.py:3043:31: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/detectors/_common.py:848:38: NPY201 [*] `np.string_` will be removed in NumPy 2.0. Use `numpy.bytes_` instead.
src/pyFAI/diffmap.py:380:39: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/diffmap.py:389:77: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/diffmap.py:399:39: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/diffmap.py:408:77: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/goniometer.py:96:35: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/goniometer.py:187:35: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/goniometer.py:234:42: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/goniometer.py:334:35: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/goniometer.py:359:42: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/gui/diffmap_widget.py:560:46: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/io/sparse_frame.py:118:25: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/massif.py:283:48: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/opencl/peak_finder.py:1135:25: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/opencl/test/test_ocl_sort.py:55:19: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/opencl/test/test_ocl_sort.py:73:23: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/test/test_preproc.py:75:23: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/test/test_utils.py:108:48: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
src/pyFAI/test/test_utils_mathutil.py:147:16: NPY201 [*] `np.NaN` will be removed in NumPy 2.0. Use `numpy.nan` instead.
```

**Comment by kif** [comment]
Things are slightly more complicated than expected ...
- [X] Check the Python code
- [X] `h5py` is compatible with `numpy2`
- [X] `FabIO` is compatible with `numpy2`
- [ ] `pythran` is compatible with `numpy2`
- [ ] `SciPy`  is compatible with `numpy2`
- [ ] All other libraries are  compatible with `numpy2`  
- [ ] tests are all passing

**Comment by kif** [comment]
https://github.com/inducer/pyopencl/issues/719

**Comment by kif** [comment]
Here are the broken tests:
```
======================================================================
ERROR: test_local_max (pyFAI.test.test_blob_detection.TestBlobDetection.test_local_max)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/test/test_blob_detection.py", line 81, in test_local_max
    self.assertTrue(numpy.alltrue(_blob.local_max(bd.dogs, bd.cur_mask, False) ==
                    ^^^^^^^^^^^^^
  File "/home/kieffer/.venv/py311_nightly/lib/python3.11/site-packages/numpy/__init__.py", line 410, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'alltrue'

======================================================================
ERROR: test_histogram (pyFAI.opencl.test.test_openCL.TestMask.test_histogram)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/opencl/test/test_openCL.py", line 123, in test_histogram
    res = ai.integrate1d_ng(data, self.N, method=method, unit="2th_deg")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/azimuthalIntegrator.py", line 1458, in integrate1d_ng
    integr = method.class_funct_ng.klass(pos0,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/opencl/azim_hist.py", line 155, in __init__
    self.wdim_bins = (self.bins + self.BLOCK_SIZE - 1) & ~(self.BLOCK_SIZE - 1),
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
OverflowError: Python integer -32 out of bounds for uint32

======================================================================
ERROR: test_histogram1d (pyFAI.opencl.test.test_ocl_histo.TestOclHistogram.test_histogram1d)
tests the 1d histogram kernel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/opencl/test/test_ocl_histo.py", line 98, in test_histogram1d
    integrator = OCL_Histogram1d(tth, npt, ctx=self.ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/opencl/azim_hist.py", line 155, in __init__
    self.wdim_bins = (self.bins + self.BLOCK_SIZE - 1) & ~(self.BLOCK_SIZE - 1),
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
OverflowError: Python integer -32 out of bounds for uint32

Stderr:
WARNING:pyFAI.DEPRECATION:Function integrate1d_legacy is deprecated since pyFAI version 0.20. Use 'integrate1d_ng' instead.
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/opencl/test/test_ocl_histo.py", line 97, in test_histogram1d
    ref = self.ai.integrate1d_legacy(data, npt, unit="2th_deg", method="numpy")

======================================================================
ERROR: test_histogram2d (pyFAI.opencl.test.test_ocl_histo.TestOclHistogram.test_histogram2d)
tests the 2D histogram kernel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/opencl/test/test_ocl_histo.py", line 170, in test_histogram2d
    integrator = OCL_Histogram2d(tth, chi, *npt, empty=dummy, profile=1)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/opencl/azim_hist.py", line 685, in __init__
    OCL_Histogram1d.__init__(self,
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/opencl/azim_hist.py", line 155, in __init__
    self.wdim_bins = (self.bins + self.BLOCK_SIZE - 1) & ~(self.BLOCK_SIZE - 1),
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
OverflowError: Python integer -32 out of bounds for uint32

======================================================================
FAIL: test_then_set_data (pyFAI.gui.test.test_calibration.TestCalibration.test_then_set_data)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieffer/.venv/py311_nightly/lib/python3.11/site-packages/silx/gui/utils/testutils.py", line 193, in tearDown
    raise AssertionError("Exception occured in Qt thread:\n" + messages)
AssertionError: Exception occured in Qt thread:
Traceback (most recent call last):
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/gui/widgets/CalibrantPreview.py", line 162, in paintEvent
    pixmap = self.__getPixmap(size=pixmapRect.width())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/gui/widgets/CalibrantPreview.py", line 138, in __getPixmap
    qimage = imageutils.convertArrayToQImage(rgbImage)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/gui/utils/imageutils.py", line 52, in convertArrayToQImage
    image = numpy.array(image, copy=False, order='C', dtype=numpy.uint8)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unable to avoid copy while creating a new array.
Traceback (most recent call last):
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/gui/tasks/MaskTask.py", line 295, in __widgetShow
    self.__updateWidgetFromModel()
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/gui/tasks/MaskTask.py", line 319, in __updateWidgetFromModel
    self.__maskPanel.setSelectionMask(mask)
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/gui/tasks/MaskTask.py", line 125, in setSelectionMask
    result = super(_MaskToolsWidget, self).setSelectionMask(mask, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kieffer/.venv/py311_nightly/lib/python3.11/site-packages/silx/gui/plot/MaskToolsWidget.py", line 337, in setSelectionMask
    mask = numpy.array(mask, copy=False, dtype=numpy.uint8)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.

Stderr:
WARNING:pyFAI.detectors._common:guess_binning is not implemented for FReLoN detectors!                 and image size (2, 2) is wrong, expected (2048, 2048)!
WARNING:pyFAI.detectors._common:guess_binning is not implemented for FReLoN detectors!                 and image size (2, 2) is wrong, expected (2048, 2048)!
WARNING:pyFAI.detectors._common:guess_binning is not implemented for FReLoN detectors!                 and image size (2, 2) is wrong, expected (2048, 2048)!
WARNING:pyFAI.detectors._common:guess_binning is not implemented for FReLoN detectors!                 and image size (2, 2) is wrong, expected (2048, 2048)!
WARNING:pyFAI.calibrant:This is an unlikely wavelength (in meter): 60.0
WARNING:pyFAI.calibrant:This is an unlikely wavelength (in meter): 60.0
ERROR:pyFAI.calibrant:Not d-spacing for calibrant: LaB6 Calibrant at wavelength 60.0

======================================================================
FAIL: test_with_set_data (pyFAI.gui.test.test_calibration.TestCalibration.test_with_set_data)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieffer/.venv/py311_nightly/lib/python3.11/site-packages/silx/gui/utils/testutils.py", line 193, in tearDown
    raise AssertionError("Exception occured in Qt thread:\n" + messages)
AssertionError: Exception occured in Qt thread:
Traceback (most recent call last):
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/gui/widgets/CalibrantPreview.py", line 162, in paintEvent
    pixmap = self.__getPixmap(size=pixmapRect.width())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/gui/widgets/CalibrantPreview.py", line 138, in __getPixmap
    qimage = imageutils.convertArrayToQImage(rgbImage)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/gui/utils/imageutils.py", line 52, in convertArrayToQImage
    image = numpy.array(image, copy=False, order='C', dtype=numpy.uint8)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unable to avoid copy while creating a new array.
Traceback (most recent call last):
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/gui/tasks/MaskTask.py", line 295, in __widgetShow
    self.__updateWidgetFromModel()
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/gui/tasks/MaskTask.py", line 319, in __updateWidgetFromModel
    self.__maskPanel.setSelectionMask(mask)
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/gui/tasks/MaskTask.py", line 125, in setSelectionMask
    result = super(_MaskToolsWidget, self).setSelectionMask(mask, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kieffer/.venv/py311_nightly/lib/python3.11/site-packages/silx/gui/plot/MaskToolsWidget.py", line 337, in setSelectionMask
    mask = numpy.array(mask, copy=False, dtype=numpy.uint8)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.

Stderr:
WARNING:pyFAI.detectors._common:guess_binning is not implemented for FReLoN detectors!                 and image size (2, 2) is wrong, expected (2048, 2048)!
WARNING:pyFAI.detectors._common:guess_binning is not implemented for FReLoN detectors!                 and image size (2, 2) is wrong, expected (2048, 2048)!
WARNING:pyFAI.calibrant:This is an unlikely wavelength (in meter): 60.0
WARNING:pyFAI.calibrant:This is an unlikely wavelength (in meter): 60.0
ERROR:pyFAI.calibrant:Not d-spacing for calibrant: LaB6 Calibrant at wavelength 60.0

FAILED (failures=2, errors=29, skipped=16)

**Comment by kif** [comment]
For the remaining bugs ... 
https://github.com/silx-kit/silx/pull/4082/files
thanks @t20100 for the inspiration.

**Comment by kif** [comment]
With the patched version of silx ...
```
======================================================================
FAIL: test_with_set_data (pyFAI.gui.test.test_calibration.TestCalibration.test_with_set_data)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieffer/.venv/py311_nightly/lib/python3.11/site-packages/silx/gui/utils/testutils.py", line 193, in tearDown
    raise AssertionError("Exception occured in Qt thread:\n" + messages)
AssertionError: Exception occured in Qt thread:
Traceback (most recent call last):
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/gui/widgets/CalibrantPreview.py", line 162, in paintEvent
    pixmap = self.__getPixmap(size=pixmapRect.width())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/gui/widgets/CalibrantPreview.py", line 138, in __getPixmap
    qimage = imageutils.convertArrayToQImage(rgbImage)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kieffer/workspace/pyFAI/build/lib/python3/dist-packages/pyFAI/gui/utils/imageutils.py", line 52, in convertArrayToQImage
    image = numpy.array(image, copy=False, order='C', dtype=numpy.uint8)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unable to avoid copy while creating a new array.
```
