### ISSUE TITLE
Regression related to modification made in ring extraction ...

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#2104]
The image calibrated is a Lambda detector 750k CdTe.
```
INFO:pyFAI.detectors._common:dynamic_mask makes sense only when dummy is defined !
ERROR:pyFAI-calib2.UNCAUGHT:index 801864 is out of bounds for axis 0 with size 801864
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyFAI/gui/tasks/GeometryTask.py", line 883, in __initGeometry
    self.__initGeometryFromPeaks(useFittedGeometry=True)
  File "/usr/lib/python3/dist-packages/pyFAI/gui/tasks/GeometryTask.py", line 849, in __initGeometryFromPeaks
    calibration.init(peaks, "massif", initialGeometry, constraints)
  File "/usr/lib/python3/dist-packages/pyFAI/gui/helper/RingCalibration.py", line 269, in init
    self.__init(peaks, method, geometry, constraintsModel=constraintsModel)
  File "/usr/lib/python3/dist-packages/pyFAI/gui/helper/RingCalibration.py", line 257, in __init
    peakPicker = PeakPicker(data=self.__image,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pyFAI/gui/peak_picker.py", line 127, in __init__
    min_valid = view[numpy.where(flat_mask == False)].min()
                ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 801864 is out of bounds for axis 0 with size 801864
```

**Comment by kif** [comment]
The detector shape is 516x1556 while the image is 516x1554. It is a CdTe sensor, apparently some pixels where disabled with the change of sensor ...

**Comment by kif** [comment]
the difference of shape explains the issue
