### ISSUE TITLE
diffmap: mismatch between default nbpt_rad and nbpt_rad from .json file

### ISSUE THREAD

**Issue by EdgarGF93** [silx-kit/pyFAI#2119]
pyFAI-diffmap --config /home/edgar1993a/work/pilx_test/.diffmap.json

```
Exception in thread process:
Traceback (most recent call last):
  File "/users/edgar1993a/anaconda3/envs/condapy311/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/users/edgar1993a/anaconda3/envs/condapy311/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/edgar1993a/py311/lib/python3.11/site-packages/pyFAI/gui/diffmap_widget.py", line 495, in process
    diffmap.process_one_file(fn.path, callback=lambda fn, idx:self.progressbarChanged.emit(i, diffmap._idx))
  File "/home/edgar1993a/py311/lib/python3.11/site-packages/pyFAI/diffmap.py", line 553, in process_one_file
    self.process_one_frame(fimg.data)
  File "/home/edgar1993a/py311/lib/python3.11/site-packages/pyFAI/diffmap.py", line 605, in process_one_frame
    self.dataset[pos.slow, pos.fast, ...] = res.intensity
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/edgar1993a/py311/lib/python3.11/site-packages/h5py/_hl/dataset.py", line 997, in __setitem__
    mspace = h5s.create_simple(selection.expand_shape(mshape))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/edgar1993a/py311/lib/python3.11/site-packages/h5py/_hl/selections.py", line 264, in expand_shape
    raise TypeError("Can't broadcast %s -> %s" % (source_shape, self.array_shape))  # array shape
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't broadcast (2000,) -> (1000,)
```

**Comment by EdgarGF93** [comment]
it's in
[diffmap](https://github.com/silx-kit/pyFAI/blob/f22eea324606c764ff691c002ba11a17df7b8513/src/pyFAI/diffmap.py#L419)

self.nbpt_rad is still the default (1000)

**Comment by EdgarGF93** [comment]
go to #2118
