### ISSUE TITLE
Silx 2.1.0 breaks pyFAI.opencl.ocl

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/pyFAI#2145]
```
pip install pyFAI

python -c "from silx.opencl import ocl"
python -c "from pyFAI.opencl import ocl"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'ocl' from 'pyFAI.opencl' (/usr/local/lib/python3.11/site-packages/pyFAI/opencl/__init__.py)
```

```
pip install "silx!=2.1.0"

python -c "from silx.opencl import ocl"
python -c "from pyFAI.opencl import ocl"
```

```
pip install pyopencl

python -c "import pyopencl;print(pyopencl.get_platforms())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR
```

**Comment by woutdenolf** [comment]
The original error I got in our CI

```
/usr/local/lib/python3.11/site-packages/ewoksxrpd/tasks/worker.py:7: in <module>
    import pyFAI.worker
/usr/local/lib/python3.11/site-packages/pyFAI/worker.py:102: in <module>
    from .distortion import Distortion
/usr/local/lib/python3.11/site-packages/pyFAI/distortion.py:41: in <module>
    from .opencl import ocl
E   ImportError: cannot import name 'ocl' from 'pyFAI.opencl' (/usr/local/lib/python3.11/site-packages/pyFAI/opencl/__init__.py)
```

**Comment by woutdenolf** [comment]
Also happens when the system has an opencl platform

```
python -c "from pyFAI.opencl import ocl"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'ocl' from 'pyFAI.opencl' (.../lib/python3.8/site-packages/pyFAI/opencl/__init__.py)

python -c "import pyopencl;print(pyopencl.get_platforms())"
[<pyopencl.Platform 'NVIDIA CUDA' at 0x563d5cd08be0>]
```

**Comment by kif** [comment]
I believe this has been fixed in:
https://github.com/silx-kit/pyFAI/pull/2134/files
but not part of any release yet ...

**Comment by loichuder** [comment]
Yes, https://github.com/silx-kit/pyFAI/pull/2134/commits/f7bd001a4cedf85fbad5fe1ec4f369d8f8b5addc seems to fix the issue.

**Comment by kif** [comment]
This is fixed now, we are working on the release
