### ISSUE TITLE
Python CSC-engine fails to integrate for specific shapes: imxpad_s10 fails

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#2151]
Other detectors looks OK.
```
======================================================================
FAIL: test_weighted (pyFAI.test.test_azimuthal_integrator.TestUnweighted.test_weighted)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/kieffer/workspace-400/pyFAI/build/lib/python3.11/site-packages/pyFAI/test/test_azimuthal_integrator.py", line 765, in test_weighted
    raise err
  File "/users/kieffer/workspace-400/pyFAI/build/lib/python3.11/site-packages/pyFAI/test/test_azimuthal_integrator.py", line 762, in test_weighted
    res = self.ai.integrate2d(self.img, 10, method=method, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/kieffer/workspace-400/pyFAI/build/lib/python3.11/site-packages/pyFAI/azimuthalIntegrator.py", line 2327, in integrate2d_ng
    integr = method.class_funct_ng.klass(cython_integr.size,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/kieffer/workspace-400/pyFAI/build/lib/python3.11/site-packages/pyFAI/engines/CSC_engine.py", line 443, in __init__
    CSCIntegrator.__init__(self, image_size, bins, lut, empty)
  File "/users/kieffer/workspace-400/pyFAI/build/lib/python3.11/site-packages/pyFAI/engines/CSC_engine.py", line 77, in __init__
    self.set_matrix(*lut)
  File "/users/kieffer/workspace-400/pyFAI/build/lib/python3.11/site-packages/pyFAI/engines/CSC_engine.py", line 455, in set_matrix
    assert self.size == len(indptr) - 1
AssertionError
```

**Comment by kif** [comment]
Simplifies in 
```
import numpy,pyFAI
ai = pyFAI.load({"detector": "imxpad_s10"})
img=numpy.ones(ai.detector.shape);
res=ai.integrate2d(img,10,method=("full","csc","python"),unit="r_mm")
```

**Comment by kif** [comment]
The shape of the `indptr` is correct for splitting "no" or "bbox" but not "full", one line is missing. The bug is at the cython level which produces the CSC array.

**Comment by kif** [comment]
Scan for faulty detectors ...
```
import pyFAI
detectors = list(Detector.registry.keys())[1:]
done=set()
for d in detectors:
     ai = pyFAI.load({"detector": d})
     if str(ai.detector) in done:
         continue
     done.add(str(ai.detector))
     csc=ai.setup_sparse_integrator(ai.detector.shape, (10,36), split="full", algo="CSC",unit="r_mm")
     if csc.lut[-1].size != 1+numpy.prod(ai.detector.shape):
         print("problem with", d,ai.detector.shape, 1+numpy.prod(ai.detector.shape),csc.lut[-1].size)
     else: print("ok", d)
```

**Comment by kif** [comment]
Bugs were found for those detectors:
problem with pixirad1 (476, 512) 243713 365569
problem with pixirad2 (476, 1024) 487425 731137
problem with pixirad4 (476, 2048) 974849 1462273
problem with pixirad8 (476, 4096) 1949697 2924545

**Comment by kif** [comment]
More surprising, the shape is correct when it comes out of setup_sparse ...

**Comment by kif** [comment]
The bug comes from the fact the last line is masked out

**Comment by kif** [comment]
When specifying the mask, many more detector are misbehaving:
problem with imxpads10 (120, 80) 9601 9520
problem with imxpads70 (120, 560) 67201 66640
problem with imxpads70v (560, 120) 67201 67080
problem with imxpads140 (240, 560) 134401 133840
problem with xpad_flat (960, 560) 537601 537040
problem with cirpad (11200, 120) 1344001 1343880
problem with rayonix133 (2048, 2048) 4194305 4193313
problem with rayonixsx165 (4096, 4096) 16777217 16775214
problem with mar345 (3450, 3450) 11902501 11900818

They have all in common to have the last line masked out.
