### ISSUE TITLE
[peakfinder] fails saving link to input data (--save-source)

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#2197]
```
(py311_x86-64) kieffer@scisoft16:/scratch/kieffer/JF4M/raw$ peakfinder --save-source  --beamline ID29 --poni geometry.poni  -P 0.99 --error-model azimuthal --noise=500  -o '{basename}_spots.h5' lysozyme_100T-lysozyme_100T000?.h5 
INFO:pyFAI.geometry.core:Unable to parse geometry.poni as JSON file, defaulting to PoniParser
INFO:silx.opencl.processing:432.223MB are needed on device: NVIDIA L40S,  which has 47810.937MB
INFO:silx.opencl.processing:Compiling file ['silx:opencl/doubleword.cl', 'pyfai:openCL/preprocess.cl', 'pyfai:openCL/memset.cl', 'pyfai:openCL/ocl_azim_CSR.cl', 'pyfai:openCL/sparsify.cl', 'pyfai:openCL/peakfinder.cl'] with options -D NBINS=800 -D NIMAGE=4475152
    Peak-finder [■■                            ]  10%  lysozyme_100T-lysozyme_100T0000.h5 frame #1000:    3 peaks
Saving filename lysozyme_100T-lysozyme_100T0000_spots.h5
Exception in thread writer:                    ]  11%  lysozyme_100T-lysozyme_100T0001.h5 frame #0059:    2 peaks
Traceback (most recent call last):
  File "/home/esrf/kieffer/.conda/envs/python3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/esrf/kieffer/.venv/py311_x86-64/lib/python3.11/site-packages/pyFAI/app/peakfinder.py", line 215, in run
    self.save(filename,
  File "/home/esrf/kieffer/.venv/py311_x86-64/lib/python3.11/site-packages/pyFAI/io/spots.py", line 315, in save_spots_cxi
    datagrp[f"data_{j+1}"] = h5py.ExternalLink(file_src, ds.name)
                                                         ^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'name'

```

**Comment by kif** [comment]
I guess this is not too complicated to be addressed.

**Comment by EdgarGF93** [comment]
#2198
