### ISSUE TITLE
Ewoks does not execute integration with generic Detector

### ISSUE THREAD

**Issue by EdgarGF93** [silx-kit/pyFAI#2227]
Testing at ID13, pyFAI integration workflow with poni file using generic detector.
The poni file was generated with pyFAI-calib2, so the shape is correct. 
I would bet the problem is in the worker (ewoks integrate uses pyFAI worker)

```
# Nota: C-Order, 1 refers to the Y axis, 2 to the X axis
# Calibration done at Mon Jul  1 16:57:28 2024
poni_version: 2.1
Detector: Detector
Detector_config: {"pixel1": 9.999999999999996e-05, "pixel2": 9.999999999999996e-05, "max_shape": [576, 748], "orientation": 3}
Distance: 0.0
Poni1: -0.9999999999999997
Poni2: -0.4534043661362292
Rot1: -0.7203892792219219
Rot2: 0.9602593871292956
Rot3: 0.0

```

```
Traceback (most recent call last):
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/ewokscore/task.py", line 401, in execute
    self.run()
  File "/home/opid13/local/ewoks/ewoksxrpd/src/ewoksxrpd/tasks/integrate.py", line 411, in run
    result = worker.process(
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/pyFAI/worker.py", line 403, in process
    raise err
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/pyFAI/worker.py", line 378, in process
    integrated_result = self._processor(**kwarg)
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/pyFAI/azimuthalIntegrator.py", line 1161, in integrate1d_ng
    solidangle = self.solidAngleArray(shape, correctSolidAngle)
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/pyFAI/geometry/core.py", line 1257, in solidAngleArray
    dssa = numpy.fromfunction(self.diffSolidAngle,
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/numpy/core/numeric.py", line 1845, in fromfunction
    return function(*args, **kwargs)
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/pyFAI/geometry/core.py", line 1229, in diffSolidAngle
    cosa = self._cached_array["cos_incidence"] = self.cos_incidence(d1, d2)
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/pyFAI/geometry/core.py", line 1148, in cos_incidence
    p1, p2, p3 = self._calc_cartesian_positions(d1, d2)
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/pyFAI/geometry/core.py", line 309, in _calc_cartesian_positions
    p1, p2, p3 = self.detector.calc_cartesian_positions(d1, d2)
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/pyFAI/detectors/_common.py", line 739, in calc_cartesian_positions
    p1 = (self._pixel1 * (dY + d1c))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/ewoksjob/apps/ewoks.py", line 26, in new_celery_task
    return celery_task(self, *args, **kwargs)
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/ewoksjob/apps/ewoks.py", line 45, in new_celery_task
    return celery_task(*args, **kwargs)
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/ewoksjob/apps/ewoks.py", line 61, in execute_graph
    return ewoks.execute_graph(*args, **kwargs)
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/ewoks/bindings.py", line 78, in execute_graph
    result = mod.execute_graph(graph, execinfo=execinfo, **execute_options)
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/ewokscore/events/contexts.py", line 25, in wrapper
    return method(*args, execinfo=execinfo, **kw)
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/ewokscore/bindings.py", line 56, in execute_graph
    return sequential.execute_graph(taskgraph.graph, **execute_options)
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/ewokscore/graph/execute/sequential.py", line 122, in execute_graph
    task.execute(
  File "/home/opid13/.conda/envs/ewoksworker/lib/python3.9/site-packages/ewokscore/task.py", line 407, in execute
    raise RuntimeError(f"Task '{self.label}' failed") from e
RuntimeError: Task 'integrate' failed



```

**Comment by EdgarGF93** [comment]
After debugging, it is not the wrong pyFAI version, I still think the error is in the worker

**Comment by kif** [comment]
Well, the PONI-file is malformed with a distance on zero ... but apparently it is not linked.
It looks like the detector is not properly initialized since the pixel size is None. Could you check where your detector is initialized in your code, the options of the detector are probably not properly read/parsed.

**Comment by EdgarGF93** [comment]
It is related with pyFAI, but I'm not sure how to address it.
ewoksxrpd uses the class:
```

class EwoksWorker(pyFAI.worker.Worker):
    def __init__(self, integration_options: Mapping, worker_options: Mapping) -> None:
        super().__init__(**worker_options)

```

which updates the poni and integration parameters here:

```
        self.set_config(integration_options, consume_keys=True)

```

So, that set_config is the super() method from pyFAI.worker.Worker:


```

    def set_config(self, config, consume_keys=False):
        """
        Configure the working from the dictionary.

        :param dict config: Key-value configuration
        :param bool consume_keys: If true the keys from the dictionary will be
            consumed when used.
        """
        config = integration_config.normalize(config, inplace=consume_keys, do_raise=False)
        _init_ai(self.ai, config, consume_keys=True, read_maps=False)


```
The problem comes in integration_config.normalize:

```
def normalize(config, inplace=False, do_raise=False):
    """Normalize the configuration file to the one supported internally\
    (the last one).

    :param dict config: The configuration dictionary to read
    :param bool inplace: In true, the dictionary is edited inplace
    :param bool do_raise: raise ValueError if set. Else use logger.error
    :raise ValueError: If the configuration do not match & do_raise is set
    """
    if not inplace:
        config = config.copy()

    version = config.get("version", 1)
    if version == 1:
        # NOTE: Previous way to describe an integration process before pyFAI 0.17
        _patch_v1_to_v2(config)
    version = config["version"]
    if version == 2:
        _patch_v2_to_v3(config)


```

Since Ewoks uses a dictionary without "version" tag, it takes version as 1 here, and then  **_patch_v1_to_v2** removes the detector_config:

```
In [60]: integration_options_generic = {'poni_version': 2.1,
    ...:       'detector': 'Detector',
    ...:       'detector_config': {'pixel1': 9.999999999999999e-05,
    ...:        'pixel2': 9.999999999999999e-05,
    ...:        'max_shape': [576, 748],
    ...:        'orientation': 3},
    ...:       'dist': 0.16156348926909264,
    ...:       'poni1': 1.4999999999999998,
    ...:       'poni2': 1.4999999999999998,
    ...:       'rot1': 1.0822864853552985,
    ...:       'rot2': -0.41026007690779387,
    ...:       'rot3': 0.0,
    ...:       'wavelength': 1.0332016536100021e-10}

In [61]: 

In [61]: _patch_v1_to_v2(integration_options_generic)

In [62]: integration_options_generic
Out[62]: 
{'poni_version': 2.1,
 'detector_config': {'pixel1': None,
  'pixel2': None,
  'max_shape': None,
  'orientation': <Orientation.BottomRight: 3>},
 'dist': 0.16156348926909264,
 'poni1': 1.4999999999999998,
 'poni2': 1.4999999999999998,
 'rot1': 1.0822864853552985,
 'rot2': -0.41026007690779387,
 'rot3': 0.0,
 'wavelength': 1.0332016536100021e-10,
 'detector': 'Detector',
 'method': 'splitbbox',
 'version': 2,
 'application': 'pyfai-integrate'}


```

**Comment by EdgarGF93** [comment]
The problem is in the method _patch_v1_to_v2:

```
    value = config.pop("detector", None)
    if value:
        # NOTE: pixel1/pixel2/splineFile was not parsed here
        detector_name = value.lower()
        detector = detectors.detector_factory(detector_name)

        if detector_name == "detector":
            value = config.pop("pixel1", None)
            if value:
                detector.set_pixel1(value)
            value = config.pop("pixel2", None)
            if value:
                detector.set_pixel2(value)
        else:
            # Drop it as it was not really used
            _ = config.pop("pixel1", None)
            _ = config.pop("pixel2", None)

        splineFile = config.pop("splineFile", None)
        if splineFile:
            detector.set_splineFile(splineFile)
    else:
        if "shape" in config and "pixel1" in config and "pixel2" in config:
            max_shape = config["shape"]
            pixel1 = config["pixel1"]
            pixel2 = config["pixel2"]
            spline = config.get("splineFile")
            detector = detectors.Detector(pixel1, pixel2, splineFile=spline, max_shape=max_shape)
    if detector is not None:
        # Feed the detector as version2
        config["detector"] = detector.__class__.__name__
        config["detector_config"] = detector.get_config()


```

if the detector is generic, it creates the instance with detector_factory, and then at the bottom, it udpates the detector_config with get_config(), but the information is lost

**Comment by kif** [comment]
Are you able to reproduce the bug without this derivative class ?

**Comment by EdgarGF93** [comment]
Yes, but I don't have to use ewoks, you see here that the detector_configuration is lost anyway:

```
In [24]: from pyFAI.worker import Worker, _init_ai

In [25]: worker_generic = Worker()

In [26]: integration_options_generic = {'poni_version': 2.1,
    ...:       'detector': 'Detector',
    ...:       'detector_config': {'pixel1': 9.999999999999999e-05,
    ...:        'pixel2': 9.999999999999999e-05,
    ...:        'max_shape': [576, 748],
    ...:        'orientation': 3},
    ...:       'dist': 0.16156348926909264,
    ...:       'poni1': 1.4999999999999998,
    ...:       'poni2': 1.4999999999999998,
    ...:       'rot1': 1.0822864853552985,
    ...:       'rot2': -0.41026007690779387,
    ...:       'rot3': 0.0,
    ...:       'wavelength': 1.0332016536100021e-10}

In [27]: 

In [27]: worker_generic.set_config(integration_options_generic)

In [29]: worker_generic.ai.detector
Out[29]: Undefined detector
```
```
In [30]: integration_options_maxipix = {'poni_version': 2,
    ...:       'detector': 'Maxipix2x2',
    ...:       'detector_config': {},
    ...:       'dist': 0.029697341310368504,
    ...:       'poni1': 0.03075830660872356,
    ...:       'poni2': 0.008514191495847496,
    ...:       'rot1': 0.2993182762142924,
    ...:       'rot2': 0.11405876271088071,
    ...:       'rot3': -4.950942273187188e-07,
    ...:       'wavelength': 1.0332016449700598e-10}

In [31]: worker_maxipix = Worker()

In [32]: worker_maxipix.set_config(integration_options_maxipix)

In [33]: worker_maxipix.ai.detector
Out[33]: Detector Maxipix 2x2	 PixelSize= 5.500e-05, 5.500e-05 m

In [34]: worker_maxipix.ai.detector.shape
Out[34]: (516, 516)

In [35]: worker_generic.ai.detector.shape

In [36]: 



```

**Comment by kif** [comment]
You could already set `integration_options_generic["version"] = 3` and there is no bug.

**Comment by kif** [comment]
Even better:
```
v4 = {"poni": integration_options_generic.copy()}
normalize(v4)
```

Your error is that you mix poni information and worker configuration

**Comment by kif** [comment]
Example of JSON file produced by `pyFAI-integrate`, it contains the application and the version number :
```
{
    "application": "pyfai-integrate",
    "version": 3,
    "wavelength": 1e-10,
    "dist": 1.58323111834,
    "poni1": 0.0334170169115,
    "poni2": 0.0412277798782,
    "rot1": 0.00648735642526,
    "rot2": 0.00755810191106,
    "rot3": 4.12987220385e-08,
    "detector": "Detector",
    "detector_config": {
        "pixel1": 9.999999999999999e-05,
        "pixel2": 9.999999999999999e-05,
        "max_shape": [
            111,
            222
        ],
        "orientation": 3
    },
    "do_mask": false,
    "mask_file": "",
    "do_dark": false,
    "dark_current": null,
    "do_flat": false,
    "flat_field": null,
    "do_polarization": false,
    "polarization_factor": 0.0,
    "do_dummy": false,
    "val_dummy": null,
    "delta_dummy": null,
    "do_2D": false,
    "nbpt_rad": 123,
    "unit": "2th_deg",
    "do_radial_range": false,
    "radial_range_min": null,
    "radial_range_max": null,
    "do_azimuthal_range": false,
    "azimuth_range_min": null,
    "azimuth_range_max": null,
    "chi_discontinuity_at_0": false,
    "do_solid_angle": true,
    "error_model": null
}
```
