### ISSUE TITLE
pyfai-average is not anymore compatible with fabio 0.3

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#320]
Here is the unittest output
```
......................................................................................................................................................................................................../usr/lib/python2.7/dist-packages/sklearn/pls.py:7: DeprecationWarning: This module has been moved to cross_decomposition and will be removed in 0.16
  "removed in 0.16", DeprecationWarning)
WARNING: Not using BLAS, PCA calculation will be slower
WARNING: Not using BLAS/ATLAS, PCA calculation will be slower
Traceback (most recent call last):
  File "/home/valls/workspace/pyfai.git/scripts/pyFAI-average", line 133, in <module>
    main()
  File "/home/valls/workspace/pyfai.git/scripts/pyFAI-average", line 129, in main
    flats=flats, darks=darks, quantiles=quantiles)
  File "/home/valls/workspace/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/utils.py", line 660, in averageImages
    fabioclass = fabio.factory(fformat + "image")
AttributeError: 'module' object has no attribute 'factory'
..................Gtk-Message: Failed to load module "canberra-gtk-module"
.....
----------------------------------------------------------------------
Ran 223 tests in 95.601s

OK
```
The execution failed, but it was not cached.

**Comment by vallsv** [comment]
My branch use now popen to read stdout/err

**Comment by kif** [comment]
has been merged & fixed
