### ISSUE TITLE
pyopencl.LogicError: clGetPlatformIDs failed: platform not found khr

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#323]
Hello while playing with pyFAI 0.12.0.

I get this error message from blender (using python3)

read blend: /home/experiences/instrumentation/picca/cirpad.blend
WARNING:pyFAI.utils:Exception No module named 'fftw3': FFTw3 not available. Falling back on Scipy
Traceback (most recent call last):
  File "/home/experiences/instrumentation/picca/cirpad.blend/interface.py", line 5, in <module>
  File "/usr/lib/python3/dist-packages/pyFAI/__init__.py", line 49, in <module>
    from .azimuthalIntegrator import AzimuthalIntegrator
  File "/usr/lib/python3/dist-packages/pyFAI/azimuthalIntegrator.py", line 109, in <module>
    from .opencl import ocl
  File "/usr/lib/python3/dist-packages/pyFAI/opencl.py", line 177, in <module>
    class OpenCL(object):
  File "/usr/lib/python3/dist-packages/pyFAI/opencl.py", line 189, in OpenCL
    for idx, platform in enumerate(pyopencl.get_platforms()):
pyopencl.LogicError: clGetPlatformIDs failed: platform not found khr
Error: Python script fail, look in the console for now...

**Comment by kif** [comment]
On Mon, 27 Jun 2016 06:16:43 -0700
picca <notifications@github.com> wrote:

> Hello while playing with pyFAI 0.12.0.
> 
> I get this error message from blender (using python3)
> 
> read blend: /home/experiences/instrumentation/picca/cirpad.blend
> WARNING:pyFAI.utils:Exception No module named 'fftw3': FFTw3 not available. Falling back on Scipy
> Traceback (most recent call last):
>   File "/home/experiences/instrumentation/picca/cirpad.blend/interface.py", line 5, in <module>
>   File "/usr/lib/python3/dist-packages/pyFAI/__init__.py", line 49, in <module>
>     from .azimuthalIntegrator import AzimuthalIntegrator
>   File "/usr/lib/python3/dist-packages/pyFAI/azimuthalIntegrator.py", line 109, in <module>
>     from .opencl import ocl
>   File "/usr/lib/python3/dist-packages/pyFAI/opencl.py", line 177, in <module>
>     class OpenCL(object):
>   File "/usr/lib/python3/dist-packages/pyFAI/opencl.py", line 189, in OpenCL
>     for idx, platform in enumerate(pyopencl.get_platforms()):
> pyopencl.LogicError: clGetPlatformIDs failed: platform not found khr
> Error: Python script fail, look in the console for now...

Can you try to run clinfo ?
I suspect "mesa" ... or another OpenCL driver which crashes the python interperter. 

try to run in python or ipython:

import pyopencl
pyopencl.create_some_context()

and iterate manually over all option. Find the one which crashes python.
in /etc/OpenCL/vendors, comment out the first line of the culprite driver.

Cheers,

Jerome
