### ISSUE TITLE
2 bugs from BM1

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#39]
C:\Users\wouter\Documents\2013\B-station\2D-detector\PyFai\PyFAI_184_40keV>pyFAI
-integrate.py data1.tif
WARNING:root:Exception No module named fftw3: FFTw3 not available. Falling back
on Scipy
Dump!
Detector Detector        Spline= None    PixelSize= 7.500e-05, 7.500e-05 m
Wavelength= 3.099145e-11m
SampleDetDist= 1.836135e-01m    PONI= 6.178475e-03, 1.191257e-01m       rot1=0.0
00825  rot2= 0.010000  rot3= 0.000000 rad
DirectBeamDist= 183.623mm       Center: x=1586.324, y=106.862 pix       Tilt=0.5
75 deg  tiltPlanRotation= 94.714 deg
INFO:pyFAI.integrate_widget:Parameters for integration:
        dummy:  None
        error_model:    poisson
        delta_dummy:    None
        nbPt_azim:      360
        safe:   False
        filename:       None
        azimuth_range:  None
        polarization_factor:    None
        correctSolidAngle:      True
        nbPt_rad:       1200
        method: lut
        unit:   2th_deg
        radial_range:   None
INFO:pyFAI.azimuthalIntegrator:AI.integrate2d: Resetting integrator because init

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyFAI\integrate_widget.py", line 217, in p
roceed
    out.append(self.ai.integrate2d(**kwarg)[0])
  File "C:\Python27\lib\site-packages\pyFAI\azimuthalIntegrator.py", line 2419,
in integrate2d
    self._lut_integrator = self.setup_LUT(shape, nbPt, mask, radial_range, azimu
th_range, mask_checksum=mask_crc, unit=unit)
  File "C:\Python27\lib\site-packages\pyFAI\azimuthalIntegrator.py", line 962, i
n setup_LUT
    unit=unit)
  File "splitBBoxLUT.pyx", line 465, in splitBBoxLUT.HistoBBox2d.__init__ (src\s
plitBBoxLUT.c:8340)
OverflowError: size does not fit in an int
Dump!
Detector Detector        Spline= None    PixelSize= 7.500e-05, 7.500e-05 m
Wavelength= 3.099145e-11m
SampleDetDist= 1.836135e-01m    PONI= 6.178475e-03, 1.191257e-01m       rot1=0.0
00825  rot2= 0.010000  rot3= 0.000000 rad
DirectBeamDist= 183.623mm       Center: x=1586.324, y=106.862 pix       Tilt=0.5
75 deg  tiltPlanRotation= 94.714 deg
INFO:pyFAI.integrate_widget:Parameters for integration:
        dummy:  None
        error_model:    poisson
        delta_dummy:    None
        nbPt_azim:      36
        safe:   False
        filename:       None
        azimuth_range:  None
        polarization_factor:    None
        correctSolidAngle:      True
        nbPt_rad:       1200
        method: lut
        unit:   2th_deg
        radial_range:   None
INFO:pyFAI.azimuthalIntegrator:AI.integrate2d: Resetting integrator because init

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyFAI\integrate_widget.py", line 217, in p
roceed
    out.append(self.ai.integrate2d(**kwarg)[0])
  File "C:\Python27\lib\site-packages\pyFAI\azimuthalIntegrator.py", line 2654,
in integrate2d
    self.save2D(filename, I, bins_rad, bins_azim, sigma, unit, dark=dark, flat=f
lat, polarization_factor=polarization_factor)
  File "C:\Python27\lib\site-packages\pyFAI\azimuthalIntegrator.py", line 2806,
in save2D
    if dark:
ValueError: The truth value of an array with more than one element is ambiguous.
 Use a.any() or a.all()

C:\Users\wouter\Documents\2013\B-station\2D-detector\PyFai\PyFAI_184_40keV>

**Comment by vallsv** [comment]
Is that still up-to-date? It looks very old.
