### ISSUE TITLE
TypeError: diffSolidAngle() takes exactly 3 arguments (1 given)

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#399]
Hello,

everythings is in the title.

"--> /nfs/ruche-diffabs/diffabs-users/99160066/published-data/R34N1/R34N1_37/R34N1_37_03.poni"
"--> /nfs/ruche-diffabs/diffabs-users/99160066/published-data/R34N1/R34N1_37/R34N1_37_03.py"
Traceback (most recent call last):
  File "/nfs/ruche-diffabs/diffabs-users/99160066/published-data/R34N1/R34N1_37/R34N1_37_03.py", line 18, in <module>
    ai.integrate1d(img, N, filename=OUTPUT)
  File "/usr/lib/python2.7/dist-packages/pyFAI/azimuthalIntegrator.py", line 2193, in integrate1d
    solidangle = self.solidAngleArray(shape, correctSolidAngle)
  File "/usr/lib/python2.7/dist-packages/pyFAI/geometry.py", line 1129, in solidAngleArray
    shape, dtype=numpy.float32)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 1808, in fromfunction
    return function(*args,**kwargs)
TypeError: diffSolidAngle() takes exactly 3 arguments (1 given)

Cheers

Fred

**Comment by picca** [comment]
Ok, it seems that I gives to the integrate method an empty array.
img.ashape = ()

Could you check against this and print a user friendly error message, instead of this quite cryptic errors

thanks
