### ISSUE TITLE
Regression on unicode support 

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#457]
```
# 
## ERROR: test_coverage (pyFAI.test.test_utils_shell.TestUtilShell)

Traceback (most recent call last):
  File "/home/tester/pyFAI/build/lib.linux-x86_64-2.7/pyFAI/test/test_utils_shell.py", line 49, in test_coverage
    progressbar = ProgressBar("aaa", 15.1, 10)
  File "/home/tester/pyFAI/build/lib.linux-x86_64-2.7/pyFAI/utils/shell.py", line 84, in **init**
    _byte = codecs.encode(self.progress_char, encoding)
TypeError: must be string, not None

---
```

**Comment by vallsv** [comment]
I love python. Something which should takes 1 line, takes now 20 lines.

**Comment by kif** [comment]
shouln't this be closed with the merge of the PR ?

**Comment by vallsv** [comment]
Already done
