### ISSUE TITLE
Benchmark python3

### ISSUE THREAD

**Issue by t20100** [silx-kit/pyFAI#461]
pyFAI.benchmarks() failed on Python 3.5.2:
```
>>> pyFAI.benchmarks()
WARNING:test_openCL:OpenCL module (pyopencl) is not present, skip tests. No module named 'pyopencl'.
WARNING:test_ocl_sort:OpenCL module (pyopencl) is not present, skip tests. No module named 'pyopencl'.
Averaging over 10 repetitions (best of 1).
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tvincent/venv/py3env/lib/python3.5/site-packages/pyFAI/__init__.py", line 76, in benchmarks
    res = benchmark.run()
  File "/Users/tvincent/venv/py3env/lib/python3.5/site-packages/pyFAI/benchmark/__init__.py", line 571, in run_benchmark
    bench.init_curve()
  File "/Users/tvincent/venv/py3env/lib/python3.5/site-packages/pyFAI/benchmark/__init__.py", line 471, in init_curve
    self.ax.set_title(self.get_cpu() + " / " + self.get_gpu())
  File "/Users/tvincent/venv/py3env/lib/python3.5/site-packages/pyFAI/benchmark/__init__.py", line 150, in get_cpu
    self._cpu = old.replace("  ", " ")
TypeError: a bytes-like object is required, not 'str'
```

**Comment by vallsv** [comment]
It was not working at all on python 3.4 and 3.5 for other reason, then i do a big clean up of the code.
Here it is working.

I try:
```
python2.7 ./bootstrap.py pyFAI-benchmark
python3.4 ./bootstrap.py pyFAI-benchmark
python3.5 ./bootstrap.py pyFAI-benchmark

ipython3.5
> import pyFAI.benchmark
> pyFAI.benchmark.run()

ipython3.5
> import pyFAI
> pyFAI.benchmarks()
```

It was on Debian 8. Can you try again with my branch? Or the master if it is already merged?

**Comment by vallsv** [comment]
Oh, here, there is a problem at the end. I fix another thing

**Comment by vallsv** [comment]
It is MacOS dependant, i guess.

**Comment by kif** [comment]
I can reproduce the bug ... I'll send the patch tomorrow.

**Comment by t20100** [comment]
Do you need that I test it?

**Comment by kif** [comment]
It works (for this part under osx) but there are other bugs related th python3 ....

Working on processor: Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
Traceback (most recent call last):
  File "/usr/bin/pyFAI-benchmark", line 103, in <module>
    do_1d=options.onedim, do_2d=options.twodim, devices=devices)
  File "/usr/lib/python3/dist-packages/pyFAI/benchmark/__init__.py", line 593, in run_benchmark
    bench.bench_1d("splitBBox")
  File "/usr/lib/python3/dist-packages/pyFAI/benchmark/__init__.py", line 252, in bench_1d
    size = data.size / 1.0e6
UnboundLocalError: local variable 'data' referenced before assignment

**Comment by vallsv** [comment]
My PR fix that :-)

**Comment by kif** [comment]
On Mon, 07 Nov 2016 06:02:38 -0800
Valentin Valls <notifications@github.com> wrote:

> My PR fix that :-)
> 
I thought I accepted it and it was already applied ...

**Comment by vallsv** [comment]
Everything is merge, if you want to try again with a Mac

**Comment by kif** [comment]
I confirm it works on OSX
