### ISSUE TITLE
re-activate readthedocs ...

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#540]
There has been a piece of of code which was doing "python setup.py build" within the conf.py from sphinx which is gone.

**Comment by kif** [comment]
some debugging from RTD
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyfai/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyfai/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyfai/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 134, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyfai/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 129, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyfai/envs/latest/local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 65, in <module>
    from pyFAI._version import strictversion, version, __date__ as pyfai_date
ImportError: No module named pyFAI._version

Exception occurred:
  File "conf.py", line 65, in <module>
    from pyFAI._version import strictversion, version, __date__ as pyfai_date
ImportError: No module named pyFAI._version
The full traceback has been saved in /tmp/sphinx-err-BpeRFJ.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by kif** [comment]
apparently it works now.
