### ISSUE TITLE
Issue with h5py resource not found ... this affect ANY script

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#576]
```
lintaillefer:% pyFAI-calib2 
Traceback (most recent call last):
  File "/usr/bin/pyFAI-calib2", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: h5py
lintaillefer: % dpkg -l |grep h5py
ii  python-h5py                            2.6.0-1                              amd64        general-purpose Python interface to hdf5 (Python 2)
ii  python-h5py-dbg                        2.6.0-1                              amd64        debug extension for h5py (Python 2)
ii  python-h5py-doc                        2.6.0-1                              all          h5py documentation
ii  python3-h5py                           2.6.0-1                              amd64        general-purpose Python interface to hdf5 (Python 3)
ii  python3-h5py-dbg                       2.6.0-1                              amd64        debug extension for h5py (Python 3)
lintaillefer:kieffer/Soleil/gonio % pyFAI-calib 
Traceback (most recent call last):
  File "/usr/bin/pyFAI-calib", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: h5py
lintaillefer: % python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
lintaillefer: % which pyFAI-calib 
/usr/bin/pyFAI-calib
lintaillefer: % python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
```

**Comment by kif** [comment]
an upgrade to jessie-backports of pkg-resources does not help. 
this is on a debian8 system

**Comment by kif** [comment]
In python:
```
import pyFAI.app.calib2
pyFAI.app.calib2.main() 
```
works

**Comment by vallsv** [comment]
I found that on the web https://github.com/ContinuumIO/anaconda-issues/issues/320

If i only use h5py from Debian 8 package, pip is not able found h5py.

I will try to check, but maybe the only solution is to remove `h5py` from `setup.py` dependencies.

**Comment by vallsv** [comment]
Well, it is also the case for a lot of libraries, like `zmq` and more, then maybe it's a problem with the integration of pip with Debian 8.

**Comment by vallsv** [comment]
Sorry, `zmq` is named `pyzmq` in pip, then it is fine here

**Comment by vallsv** [comment]
I still have to ask Fred Picca if he have an idea. At least to understand why there is this problem.

**Comment by vallsv** [comment]
No real solution for Debian 8.

2 solutions
- Remove `h5py` dependency from the `setup.py`
- Remove `h5py` dependency from the `setup.py` only on Debian 8 system

The first one was applied on the master.
