### ISSUE TITLE
[anaconda2] Exception: No custom widget QuantityEdit found in customWidgets param of UiLoader

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#584]
Custom widgets from UI files looks to be unsupported in Anaconda 4.4.0 Python 2.7 PyQt 5.6.2

I use this in .ui files
```
  <customwidget>
   <class>QuantityEdit</class>
   <extends>QLineEdit</extends>
   <header>pyFAI.gui.calibration.QuantityEdit</header>
  </customwidget>
```

Here is version info
```
Python 2.7.13 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:17:26) [MSC v.
1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import PyQt5
>>> from PyQt5 import Qt
>>> Qt.qVersion()
'5.6.2'
```

Here is the exception backtrace
```
Traceback (most recent call last):
  File "c:\programdata\anaconda2\lib\site-packages\pyFAI\gui\_pyside_dynamic.py"
, line 112, in createWidget
    'UiLoader __init__.')
Exception: No custom widget QuantityEdit found in customWidgets param ofUiLoader
 __init__.
"Empty widget item in QGridLayout 'gridLayout_2'."
Traceback (most recent call last):
  File "c:\programdata\anaconda2\lib\site-packages\pyFAI\gui\_pyside_dynamic.py"
, line 112, in createWidget
    'UiLoader __init__.')
Exception: No custom widget DetectorSelector found in customWidgets param ofUiLo
ader __init__.
"Empty widget item in QGridLayout 'gridLayout_2'."
Traceback (most recent call last):
  File "c:\programdata\anaconda2\lib\site-packages\pyFAI\gui\_pyside_dynamic.py"
, line 112, in createWidget
    'UiLoader __init__.')
Exception: No custom widget CalibrantSelector found in customWidgets param ofUiL
oader __init__.
"Empty widget item in QGridLayout 'gridLayout_2'."

...
Traceback (most recent call last):
  File "c:\programdata\anaconda2\lib\runpy.py", line 174, in _run_module_as_main

    "__main__", fname, loader, pkg_name)
  File "c:\programdata\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\ProgramData\Anaconda2\Scripts\pyFAI-calib2.exe\__main__.py", line 9,
in <module>
  File "c:\programdata\anaconda2\lib\site-packages\pyFAI\app\calib2.py", line 38
4, in main
    widget = CalibrationWindow()
  File "c:\programdata\anaconda2\lib\site-packages\pyFAI\gui\calibration\Calibra
tionWindow.py", line 44, in __init__
    self.__tasks = self.createTasks()
  File "c:\programdata\anaconda2\lib\site-packages\pyFAI\gui\calibration\Calibra
tionWindow.py", line 64, in createTasks
    GeometryTask(),
  File "c:\programdata\anaconda2\lib\site-packages\pyFAI\gui\calibration\Geometr
yTask.py", line 227, in __init__
    self._fitButton.clicked.connect(self.__fitGeometry)
AttributeError: 'GeometryTask' object has no attribute '_fitButton'
```

**Comment by vallsv** [comment]
Old. No feedback. No body uses Anaconda here. There i close it.
