### ISSUE TITLE
[ci] flat != solidangle

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#604]
There is a lot of fails on this function. I have to relaunch tests too much times.
It would be very nice to do something. Is using greaterOrEqual makes sense?

```FAIL: test_cython (pyFAI.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pyFAI/test/test_preproc.py", line 128, in test_cython
    self.one_test(cython_preproc)
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/pyFAI/test/test_preproc.py", line 114, in one_test
    self.assertGreater(abs(numpy.round(res) - target).max(), 0, "flat != solidangle")
AssertionError: 0.0 not greater than 0 : flat != solidangle```

**Comment by kif** [comment]
I agree it is annoying. I already had a look and did not find a "valid" reason.
