### ISSUE TITLE
[colorbar] may be a bug in silx ?

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#615]
```
d2gpu2:~ % pyFAI-drawmask flatS70-livet02-02-846.edf
WARNING:silx.gui.plot.ColorBar:Log colormap with bound <= 1: changing bounds.
WARNING:silx.gui.plot.ColorBar:Log colormap with bound <= 1: changing bounds.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/silx/gui/plot/ColorBar.py", line 210, in _defaultColormapChanged
    self._syncWithDefaultColormap()
  File "/usr/lib/python2.7/dist-packages/silx/gui/plot/ColorBar.py", line 214, in _syncWithDefaultColormap
    self.setColormap(self._plot.getDefaultColormap())
  File "/usr/lib/python2.7/dist-packages/silx/gui/plot/ColorBar.py", line 153, in setColormap
    self.getColorScaleBar().setColormap(colormap)
  File "/usr/lib/python2.7/dist-packages/silx/gui/plot/ColorBar.py", line 372, in setColormap
    self.colorScale.setColormap(colormap)
  File "/usr/lib/python2.7/dist-packages/silx/gui/plot/ColorBar.py", line 494, in setColormap
    if colormap['vmin'] <= 0. or colormap['vmax'] <= 0.:
KeyError: 'vmin'
Your mask-file will be saved into flatS70-livet02-02-846-mask.edf
```

**Comment by vallsv** [comment]
That's a regression in silx. But i will fix pyFAI, it will be faster.
I create an issue on silx to make sure the next release of silx will be still compatible with pyFAI 0.13.1
