### ISSUE TITLE
[test] pyFAI.test.test_io.testHDF5Writer fail

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#626]
```
ERROR: test_writer (pyFAI.test.test_io.testHDF5Writer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/test/test_io.py", line 112, in test_writer
    writer.init({"nbpt_azim": shape[0], "nbpt_rad": shape[1]})
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/io.py", line 339, in init
    maxshape=(None,) + chunk[1:])
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/group.py", line 126, in require_dataset
    return self.create_dataset(name, *(shape, dtype), **kwds)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/group.py", line 105, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 76, in make_new_dset
    if isinstance(chunks, tuple) and (-numpy.array([ i>=j for i,j in zip(tmp_shape,chunks) if i is not None])).any():
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.
```

**Comment by vallsv** [comment]
An update of `numpy` + `h5py` was needed to fix the problem

Before
```
In [3]: h5py.version.version
Out[3]: '2.6.0'

In [4]: numpy.version.version
Out[4]: '1.13.0'
```

After
```
In [3]: h5py.version.version
Out[3]: '2.7.0'

In [4]: numpy.version.version
Out[4]: '1.13.1'
```
