### ISSUE TITLE
Test fail on prepro (Windows 64bit Python 2.7)

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#632]
```
======================================================================
ERROR: test_opencl (pyFAI.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\valls\pyFAI_release\py2.7\build\lib.win-amd64-2.7\pyFAI\test\test_preproc.py", line
 154, in test_opencl
    self.one_test(ocl_preproc)
  File "C:\Users\valls\pyFAI_release\py2.7\build\lib.win-amd64-2.7\pyFAI\test\test_preproc.py", line
 97, in one_test
    res = preproc.preproc(raw, dark, polarization=flat, dummy=dummy, mask=mask, normalization_factor
=scale)
  File "C:\Users\valls\pyFAI_release\py2.7\build\lib.win-amd64-2.7\pyFAI\opencl\preproc.py", line 49
8, in preproc
    devicetype="all")
  File "C:\Users\valls\pyFAI_release\py2.7\build\lib.win-amd64-2.7\pyFAI\opencl\preproc.py", line 12
8, in __init__
    self.send_buffer(dark, "dark")
  File "C:\Users\valls\pyFAI_release\py2.7\build\lib.win-amd64-2.7\pyFAI\opencl\preproc.py", line 33
7, in send_buffer
    kernel = getattr(self.program, self.mapping[data.dtype.type])
AttributeError: 'NoneType' object has no attribute 's32_to_float'

Stderr:
0.003MB are needed on device which has 2147.484MB
Compiling file ['preprocess.cl'] with options -D NIMAGE=64
build program: kernel 'corrections' was part of a lengthy source build resulting from a binary cache
 miss (0.39 s)
0.003MB are needed on device which has 2147.484MB
Compiling file ['preprocess.cl'] with options -D NIMAGE=64
0.003MB are needed on device which has 2147.484MB
Compiling file ['preprocess.cl'] with options -D NIMAGE=64
0.003MB are needed on device which has 2147.484MB
```

**Comment by vallsv** [comment]
Fixed
