### ISSUE TITLE
sphinx errors or warning during the debian package build

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#642]
Hello, I will put all the informations about the sphinx compilation here.

make[1] : on entre dans le répertoire « /home/picca/Debian/pyfai/pyfai »
PYBUILD_SYSTEM=custom \
PYBUILD_BUILD_ARGS="cd doc && PYTHONPATH={build_dir} http_proxy='127.0.0.1:9' {interpreter} -m sphinx -N -bhtml source build/html" dh_auto_build  # HTML generator
I: pybuild base:184: cd doc && PYTHONPATH=/home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y_2.7/build http_proxy='127.0.0.1:9' python2.7 -m sphinx -N -bhtml source build/html
Running Sphinx v1.4.9
making output directory...
WARNING:pyFAI.opencl.common:Unable to import pyOpenCl. Please install it from: http://pypi.python.org/pypi/pyopencl
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 52 source files that are out of date
updating environment: 52 added, 0 changed, 0 removed
reading sources... [  1%] api/modules
reading sources... [  3%] api/pyFAI
reading sources... [  5%] biblio
reading sources... [  7%] calibration
reading sources... [  9%] changelog
reading sources... [ 11%] coverage
reading sources... [ 13%] design/ai
reading sources... [ 15%] design/index
reading sources... [ 17%] detector
reading sources... [ 19%] ecosystem
reading sources... [ 21%] geometry
reading sources... [ 23%] glossary
reading sources... [ 25%] index
reading sources... [ 26%] man/MX-calibrate
reading sources... [ 28%] man/check_calib
reading sources... [ 30%] man/detector2nexus
reading sources... [ 32%] man/diff_map
reading sources... [ 34%] man/diff_tomo
reading sources... [ 36%] man/pyFAI-average
reading sources... [ 38%] man/pyFAI-calib
reading sources... [ 40%] man/pyFAI-drawmask
reading sources... [ 42%] man/pyFAI-integrate
reading sources... [ 44%] man/pyFAI-recalib
reading sources... [ 46%] man/pyFAI-saxs
reading sources... [ 48%] man/pyFAI-waxs
reading sources... [ 50%] man/scripts
reading sources... [ 51%] operations/index
reading sources... [ 53%] operations/linux
reading sources... [ 55%] operations/macosx
reading sources... [ 57%] operations/windows
reading sources... [ 59%] project
reading sources... [ 61%] publications
reading sources... [ 63%] pyFAI
reading sources... [ 65%] usage/cookbook/calibrate
reading sources... [ 67%] usage/cookbook/index
reading sources... [ 69%] usage/cookbook/integration_with_python
reading sources... [ 71%] usage/cookbook/integration_with_scripts
reading sources... [ 73%] usage/cookbook/integration_with_the_gui
reading sources... [ 75%] usage/tutorial/CCD_Calibration/CCD_calibration
reading sources... [ 76%] usage/tutorial/Calibrant/Calibrant
reading sources... [ 78%] usage/tutorial/Distortion/Distortion
reading sources... [ 80%] usage/tutorial/Geometry/geometry
reading sources... [ 82%] usage/tutorial/Goniometer/Rotation-Pilatus100k/Multi120_Pilatus100k
reading sources... [ 84%] usage/tutorial/Goniometer/Rotation-XPADS540/D2AM-15
reading sources... [ 86%] usage/tutorial/Goniometer/Translation-Pilatus6M/TTcalibration
reading sources... [ 88%] usage/tutorial/Goniometer/index
reading sources... [ 90%] usage/tutorial/Inpainting/Inpainting
reading sources... [ 92%] usage/tutorial/Introduction/introduction
reading sources... [ 94%] usage/tutorial/MakeCalibrant/make_calibrant
reading sources... [ 96%] usage/tutorial/MultiGeometry/MultiGeometry
reading sources... [ 98%] usage/tutorial/index
reading sources... [100%] usage/tutorial/multi-geometry

/home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y_2.7/build/pyFAI/io.py:docstring of pyFAI.io.DefaultAiWriter.save1D:22: WARNING: Field list ends without a blank line; unexpected unindent.
docstring of pyFAI.utils.bayes.BayesianBackground:10: ERROR: Unexpected indentation.
/home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y_2.7/build/pyFAI/utils/shell.py:docstring of pyFAI.utils.shell.ProgressBar.__init__:9: ERROR: Unknown directive type "codeblock".

.. codeblock::

    Title [??????      ]  50%  Message
/home/picca/Debian/pyfai/pyfai/doc/source/api/pyFAI.rst:202: WARNING: autodoc: failed to import module u'pyFAI.utils.string'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
ImportError: No module named string
/home/picca/Debian/pyfai/pyfai/doc/source/api/pyFAI.rst:247: WARNING: autodoc: failed to import module u'pyFAI.opencl.azim_hist'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
  File "/home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y_2.7/build/pyFAI/opencl/azim_hist.py", line 58, in <module>
    raise ImportError("pyopencl is not installed")
ImportError: pyopencl is not installed
/home/picca/Debian/pyfai/pyfai/doc/source/api/pyFAI.rst:255: WARNING: autodoc: failed to import module u'pyFAI.opencl.azim_lut'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
  File "/home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y_2.7/build/pyFAI/opencl/azim_lut.py", line 49, in <module>
    raise ImportError("pyopencl is not installed")
ImportError: pyopencl is not installed
/home/picca/Debian/pyfai/pyfai/doc/source/api/pyFAI.rst:263: WARNING: autodoc: failed to import module u'pyFAI.opencl.azim_csr'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
  File "/home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y_2.7/build/pyFAI/opencl/azim_csr.py", line 45, in <module>
    raise ImportError("pyopencl is not installed")
ImportError: pyopencl is not installed
docstring of pyFAI.ext.bilinear.Bilinear.f_cy:7: WARNING: Field list ends without a blank line; unexpected unindent.
docstring of pyFAI.ext.watershed.Bilinear.f_cy:7: WARNING: Field list ends without a blank line; unexpected unindent.
/home/picca/Debian/pyfai/pyfai/doc/source/man/detector2nexus.rst:34: WARNING: Option list ends without a blank line; unexpected unindent.
/home/picca/Debian/pyfai/pyfai/doc/source/man/detector2nexus.rst:37: ERROR: Unexpected indentation.
/home/picca/Debian/pyfai/pyfai/doc/source/man/detector2nexus.rst:38: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/picca/Debian/pyfai/pyfai/doc/source/usage/tutorial/Geometry/geometry.rst:503: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/picca/Debian/pyfai/pyfai/doc/source/usage/tutorial/Goniometer/Rotation-XPADS540/D2AM-15.rst:110: ERROR: Unknown target name: "16dec08d5".
/home/picca/Debian/pyfai/pyfai/doc/source/usage/tutorial/Introduction/introduction.rst:400: WARNING: Inline strong start-string without end-string.
/home/picca/Debian/pyfai/pyfai/doc/source/usage/tutorial/MakeCalibrant/make_calibrant.rst:94: WARNING: Line block ends without a blank line.
/home/picca/Debian/pyfai/pyfai/doc/source/usage/tutorial/index.rst:9: WARNING: duplicate label tutorials, other instance in /home/picca/Debian/pyfai/pyfai/doc/source/usage/tutorial/Goniometer/index.rst
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  1%] api/modules
writing output... [  3%] api/pyFAI
/home/picca/Debian/pyfai/pyfai/doc/source/api/pyFAI.rst:19: WARNING: Could not lex literal_block as "mathematica". Highlighting skipped.
writing output... [  5%] biblio
writing output... [  7%] calibration
writing output... [  9%] changelog
writing output... [ 11%] coverage
writing output... [ 13%] design/ai
writing output... [ 15%] design/index
writing output... [ 17%] detector
writing output... [ 19%] ecosystem
writing output... [ 21%] geometry
writing output... [ 23%] glossary
writing output... [ 25%] index
writing output... [ 26%] man/MX-calibrate
writing output... [ 28%] man/check_calib
writing output... [ 30%] man/detector2nexus
writing output... [ 32%] man/diff_map
writing output... [ 34%] man/diff_tomo
writing output... [ 36%] man/pyFAI-average
writing output... [ 38%] man/pyFAI-calib
writing output... [ 40%] man/pyFAI-drawmask
writing output... [ 42%] man/pyFAI-integrate
writing output... [ 44%] man/pyFAI-recalib
writing output... [ 46%] man/pyFAI-saxs
writing output... [ 48%] man/pyFAI-waxs
writing output... [ 50%] man/scripts
writing output... [ 51%] operations/index
writing output... [ 53%] operations/linux
writing output... [ 55%] operations/macosx
writing output... [ 57%] operations/windows
writing output... [ 59%] project
writing output... [ 61%] publications
writing output... [ 63%] pyFAI
writing output... [ 65%] usage/cookbook/calibrate
writing output... [ 67%] usage/cookbook/index
writing output... [ 69%] usage/cookbook/integration_with_python
writing output... [ 71%] usage/cookbook/integration_with_scripts
writing output... [ 73%] usage/cookbook/integration_with_the_gui
writing output... [ 75%] usage/tutorial/CCD_Calibration/CCD_calibration
writing output... [ 76%] usage/tutorial/Calibrant/Calibrant
writing output... [ 78%] usage/tutorial/Distortion/Distortion
writing output... [ 80%] usage/tutorial/Geometry/geometry
writing output... [ 82%] usage/tutorial/Goniometer/Rotation-Pilatus100k/Multi120_Pilatus100k
writing output... [ 84%] usage/tutorial/Goniometer/Rotation-XPADS540/D2AM-15
writing output... [ 86%] usage/tutorial/Goniometer/Translation-Pilatus6M/TTcalibration
writing output... [ 88%] usage/tutorial/Goniometer/index
writing output... [ 90%] usage/tutorial/Inpainting/Inpainting
writing output... [ 92%] usage/tutorial/Introduction/introduction
writing output... [ 94%] usage/tutorial/MakeCalibrant/make_calibrant
writing output... [ 96%] usage/tutorial/MultiGeometry/MultiGeometry
writing output... [ 98%] usage/tutorial/index
writing output... [100%] usage/tutorial/multi-geometry

generating indices... genindex py-modindex
writing additional pages... search
copying images... [  5%] man/../img/integrate.png
copying images... [ 11%] usage/tutorial/Geometry/../../../img/PONI.png
copying images... [ 16%] usage/cookbook/fabio_viewer.png
copying images... [ 22%] man/../img/diffmap_running.png
copying images... [ 27%] api/../img/quad_model.svg
copying images... [ 33%] img/notebook.png
copying images... [ 38%] man/../img/diffmap_integrate.png
copying images... [ 44%] usage/cookbook/pyFAI-calib_3.png
copying images... [ 50%] man/../img/pyFAI-drawmask.png
copying images... [ 55%] usage/cookbook/pyFAI-calib_1.png
copying images... [ 61%] man/../img/diffmap_main.png
copying images... [ 66%] img/2DwithSplit.png
copying images... [ 72%] img/benchmark.png
copying images... [ 77%] usage/cookbook/pyFAI-calib_5.png
copying images... [ 83%] usage/cookbook/pyFAI-calib_4.png
copying images... [ 88%] usage/cookbook/pyFAI-calib_2.png
copying images... [ 94%] img/2Dhistogram.png
copying images... [100%] img/PONI.png

copying static files... WARNING: html_static_path entry u'/home/picca/Debian/pyfai/pyfai/doc/source/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 19 warnings.

**Comment by picca** [comment]
There is at least three kind of problems during this build

- sphinx ERROR
- sphinx WARNING
- ImportError (I do not know yet how to fix this...)

**Comment by picca** [comment]
If I look at the ImportError only one seems problematic for me, the one with the string

Indeed the module name is stringutil and not string.

**Comment by vallsv** [comment]
Here is the fix for `stringutil` https://github.com/silx-kit/pyFAI/pull/643. Thanks for the catch.

**Comment by picca** [comment]
Hello, with the latest 0.14.2, I get only one warning now :)

```
writing output... [  3%] api/pyFAI
/<<BUILDDIR>>/pyfai-0.14.2+dfsg/doc/source/api/pyFAI.rst:19: WARNING: Could not lex literal_block as "mathematica". Highlighting skipped.
```

thanks a lot

**Comment by picca** [comment]
Sorry I found a few more

```
/<<BUILDDIR>>/pyfai-0.14.2+dfsg/.pybuild/pythonX.Y_3.5/build/pyFAI/azimuthalIntegrator.py:docstring of pyFAI.azimuthalIntegrator.AzimuthalIntegrator.xrpd_CSR_OCL:41: WARNING: Field list ends without a blank line
; unexpected unindent.
/<<BUILDDIR>>/pyfai-0.14.2+dfsg/.pybuild/pythonX.Y_3.5/build/pyFAI/geometry.py:docstring of pyFAI.geometry.Geometry.cornerArray:6: WARNING: Inline emphasis start-string without end-string.
/<<BUILDDIR>>/pyfai-0.14.2+dfsg/.pybuild/pythonX.Y_3.5/build/pyFAI/geometry.py:docstring of pyFAI.geometry.Geometry.cornerQArray:6: WARNING: Inline emphasis start-string without end-string.
/<<BUILDDIR>>/pyfai-0.14.2+dfsg/.pybuild/pythonX.Y_3.5/build/pyFAI/geometry.py:docstring of pyFAI.geometry.Geometry.cornerRArray:6: WARNING: Inline emphasis start-string without end-string.
/<<BUILDDIR>>/pyfai-0.14.2+dfsg/.pybuild/pythonX.Y_3.5/build/pyFAI/geometry.py:docstring of pyFAI.geometry.Geometry.cornerRd2Array:6: WARNING: Inline emphasis start-string without end-string.
/<<BUILDDIR>>/pyfai-0.14.2+dfsg/doc/source/api/pyFAI.rst:137: WARNING: error while formatting arguments for pyFAI.calibrant.calibrant_factory: 'function' object has no attribute '__mro__'
/<<BUILDDIR>>/pyfai-0.14.2+dfsg/doc/source/usage/tutorial/Goniometer/Rotation-XPADS540/D2AM-15.rst:110: ERROR: Unknown target name: "16dec08d5".
/<<BUILDDIR>>/pyfai-0.14.2+dfsg/doc/source/usage/tutorial/Introduction/introduction.rst:400: WARNING: Inline strong start-string without end-string.
/<<BUILDDIR>>/pyfai-0.14.2+dfsg/doc/source/usage/tutorial/MakeCalibrant/make_calibrant.rst:94: WARNING: Line block ends without a blank line.

```

**Comment by kif** [comment]
On Tue, 19 Sep 2017 08:53:44 +0000 (UTC)
picca <notifications@github.com> wrote:

> Sorry I found a few more
> 
> ```
> /<<BUILDDIR>>/pyfai-0.14.2+dfsg/.pybuild/pythonX.Y_3.5/build/pyFAI/azimuthalIntegrator.py:docstring of pyFAI.azimuthalIntegrator.AzimuthalIntegrator.xrpd_CSR_OCL:41: WARNING: Field list ends without a blank line
> ; unexpected unindent.
> /<<BUILDDIR>>/pyfai-0.14.2+dfsg/.pybuild/pythonX.Y_3.5/build/pyFAI/geometry.py:docstring of pyFAI.geometry.Geometry.cornerArray:6: WARNING: Inline emphasis start-string without end-string.
> /<<BUILDDIR>>/pyfai-0.14.2+dfsg/.pybuild/pythonX.Y_3.5/build/pyFAI/geometry.py:docstring of pyFAI.geometry.Geometry.cornerQArray:6: WARNING: Inline emphasis start-string without end-string.
> /<<BUILDDIR>>/pyfai-0.14.2+dfsg/.pybuild/pythonX.Y_3.5/build/pyFAI/geometry.py:docstring of pyFAI.geometry.Geometry.cornerRArray:6: WARNING: Inline emphasis start-string without end-string.
> /<<BUILDDIR>>/pyfai-0.14.2+dfsg/.pybuild/pythonX.Y_3.5/build/pyFAI/geometry.py:docstring of pyFAI.geometry.Geometry.cornerRd2Array:6: WARNING: Inline emphasis start-string without end-string.
> /<<BUILDDIR>>/pyfai-0.14.2+dfsg/doc/source/api/pyFAI.rst:137: WARNING: error while formatting arguments for pyFAI.calibrant.calibrant_factory: 'function' object has no attribute '__mro__'
> /<<BUILDDIR>>/pyfai-0.14.2+dfsg/doc/source/usage/tutorial/Goniometer/Rotation-XPADS540/D2AM-15.rst:110: ERROR: Unknown target name: "16dec08d5".
> /<<BUILDDIR>>/pyfai-0.14.2+dfsg/doc/source/usage/tutorial/Introduction/introduction.rst:400: WARNING: Inline strong start-string without end-string.
> /<<BUILDDIR>>/pyfai-0.14.2+dfsg/doc/source/usage/tutorial/MakeCalibrant/make_calibrant.rst:94: WARNING: Line block ends without a blank line.

Hi Fred,

For the tutorials, they are auto-generated by jupyter notebooks, and I
cannot do much about it.

Remains the 4 in the doc-strings of geometry and the one in the root. We will address it

Cheers,

**Comment by vallsv** [comment]
I dont think i have this warning here. Which version of sphinx do you use?

> Could not lex literal_block as "mathematica"
i guess, for this one, you have a missing sphinx extension?

**Comment by picca** [comment]
```
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinxcontrib.programoutput',
    'sphinx.ext.mathjax'
]
```

I have these extensions something else is necessary ?
