### ISSUE TITLE
[test] faillure during the Debian process

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#652]
Hello here the errors reported on my stretch machine whcih has 2Go of memory...

```
Test pyFAI 0.14.0 from /home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y_2.7/build/pyFAI
........................................................................................................................................................................................................................................................ssssssss.....................................E.............................F
Stderr:
Pixel splitting desactivated !
...............................E
Stderr:
MemoryError: falling back on forward implementation
.......ssssssss............................................ss
======================================================================
ERROR: test_pos_lut (pyFAI.test.test_distortion.TestHalfCCD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y_2.7/build/pyFAI/test/test_distortion.py", line 99, in test_pos_lut
    self.dis.calc_LUT(False)
  File "/home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y_2.7/build/pyFAI/distortion.py", line 286, in calc_LUT
    self.lut = _distortion.calc_LUT(self.pos, self._shape_out, self.bin_size, max_pixel_size=(self.delta1, self.delta2))
  File "pyFAI/ext/_distortion.pyx", line 514, in pyFAI.ext._distortion.calc_LUT (pyFAI/ext/_distortion.c:12668)
    return numpy.core.records.array(tmp_ary.view(dtype=dtype_lut),
  File "/usr/lib/python2.7/dist-packages/numpy/core/records.py", line 845, in array
    new = new.copy()
MemoryError

======================================================================
ERROR: test_bug170 (pyFAI.test.test_bug_regression.TestBug170)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y_2.7/build/pyFAI/test/test_bug_regression.py", line 89, in test_bug170
    ai.integrate1d(self.data, 2000)
  File "/home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y_2.7/build/pyFAI/azimuthalIntegrator.py", line 2550, in integrate1d
    dpos0 = self.array_from_unit(shape, "delta", unit, scale=False)
  File "/home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y_2.7/build/pyFAI/geometry.py", line 985, in array_from_unit
    out = Geometry.__dict__[meth_name](self, shape)
  File "/home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y_2.7/build/pyFAI/geometry.py", line 917, in deltaQ
    delta = abs(corners[..., 0] - numpy.atleast_3d(center))
MemoryError

Stderr:
MemoryError: falling back on forward implementation

======================================================================
FAIL: test_2d_nosplit (pyFAI.test.test_csr.Test_CSR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/picca/Debian/pyfai/pyfai/.pybuild/pythonX.Y_2.7/build/pyFAI/test/test_csr.py", line 154, in test_2d_nosplit
    self.assertLess(((img - img_csr) > 1).sum(), 6, " img are almost the same")
AssertionError:  img are almost the same

Stderr:
Pixel splitting desactivated !

----------------------------------------------------------------------
Ran 417 tests in 623.853s

FAILED (failures=1, errors=2, skipped=18)
```

I think that it would be nice to have a low memory env in porder to skip test to hungry :)

**Comment by kif** [comment]
Hi Fred,

Is your build computer still a 32bits computer ? The tests were passing on a Raspberry Pi-2, I am checking this is still the case.

There is a memory profiling tool to spot the tests consuming most
memory:

python run_tests.py -m -i 2>&1 |cut -f3 -d\: |sort -n 

Those are the tests consuming >100Mb:
 127.160 Mb	pyFAI.test.test_azimuthal_integrator.TestAzimHalfFrelon.test_numpy_vs_fit2d
 181.300 Mb	pyFAI.test.test_azimuthal_integrator.TestAzimHalfFrelon.test_cython_vs_numpy
 184.500 Mb	pyFAI.test.test_openCL.TestMask.test_OpenCL_CSR
 211.936 Mb	pyFAI.test.test_azimuthal_integrator.TestAzimHalfFrelon.test_cythonSP_vs_fit2d
 245.568 Mb	pyFAI.test.test_azimuthal_integrator.TestAzimHalfFrelon.test_medfilt1d
 248.064 Mb	pyFAI.test.test_azimuthal_integrator.TestAzimHalfFrelon.test_radial
 276.632 Mb	pyFAI.test.test_azimuthal_integrator.TestAzimHalfFrelon.test_separate
 285.788 Mb	pyFAI.test.test_geometry.TestSolidAngle.testSolidAngle
 326.284 Mb	pyFAI.test.test_openCL.TestMask.test_OpenCL
 539.464 Mb	pyFAI.test.test_openCL.TestMask.test_OpenCL_LUT
 602.412 Mb     pyFAI.test.test_azimuthal_integrator.TestAzimPilatus.test_separate

I will try to limit the memory occupation of those tests

**Comment by picca** [comment]
> Is your build computer still a 32bits computer ? The tests were passing on a Raspberry Pi-2, I am checking this is still the case.

Yes my computer is 32bits. quite old... 2005 :)) but with 2Go of ram

> I will try to limit the memory occupation of those tests

if you add the same LOW_MEM env it would be great especially for embeded devices.

Cheers
