### ISSUE TITLE
[pyFAI-calib2] Buggy on PyQt5

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#656]
From a feedback from Samuele Lilliu (sheffield.ac.uk).
Confirmed on our machines.

This exception occur after loading the image on the GUI.

```
ERROR:pyFAI.gui.calibration.ExperimentTask:__exit__
ERROR:pyFAI-calib2.UNCAUGHT:SystemError: <class 'PyQt5.QtCore.QChildEvent'> returned a result with an error set
```

**Comment by vallsv** [comment]
```
ERROR:pyFAI-calib2.UNCAUGHT:__exit__
Traceback (most recent call last):
  File "./bootstrap.py", line 200, in <module>
    run_entry_point(target, argv)
  File "./bootstrap.py", line 125, in run_entry_point
    func()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/app/calib2.py", line 408, in main
    setup(widget.model())
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/app/calib2.py", line 293, in setup
    with fabio.open(image_file) as image:
AttributeError: __exit__
```

**Comment by vallsv** [comment]
`fabio 0.4` do not have context manager, while `fabio 0.5` have a context manager on the method `open`.

**Comment by vallsv** [comment]
The error message containing `QChildEvent` looks to have no influences on the application.

**Comment by vallsv** [comment]
I create https://github.com/silx-kit/pyFAI/issues/668 for `fabio`, and i was not able to find the source of the `QChildEvent` warning, then i close this issue.
