### ISSUE TITLE
in setup_CSR     assert mask.shape == shape

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#685]
Hello, if I do not give a mask it cause some troubles.

It should not ;)
```
picca@diffabs6:/nfs/ruche-diffabs/diffabs-soleil/com-diffabs/2017/Run4B/malard_MarCCD/EM10_5000h_1_MAR_14$ pyFAI-waxs -p ../CeO2_3 -n 9000 *.mccd
Detector MAR165	 PixelSize= 3.950e-05, 3.950e-05 m
Wavelength= 6.887674e-11m
SampleDetDist= 1.313168e-01m	PONI= 9.667070e-02, 5.898540e-02m	rot1=-0.004212  rot2= -0.012081  rot3= 0.000000 rad
DirectBeamDist= 131.328mm	Center: x=1507.305, y=2407.193 pix	Tilt=0.733 deg  tiltPlanRotation= -70.780 deg
Mask: None	Method: full_csr
INFO:pyFAI.azimuthalIntegrator:AI.integrate1d: Resetting integrator because init
Integrating EM10_5000h_1_0.mccd --> Traceback (most recent call last):
  File "/usr/bin/pyFAI-waxs", line 11, in <module>
    load_entry_point('pyFAI==0.14.0', 'console_scripts', 'pyFAI-waxs')()
  File "/usr/lib/python2.7/dist-packages/pyFAI/app/waxs.py", line 179, in main
    metadata=fabimg.header
  File "/usr/lib/python2.7/dist-packages/pyFAI/azimuthalIntegrator.py", line 2421, in integrate1d
    unit=unit, split=split)
  File "/usr/lib/python2.7/dist-packages/pyFAI/azimuthalIntegrator.py", line 1166, in setup_CSR
    assert mask.shape == shape
AssertionError
```

**Comment by kif** [comment]
On Fri, 08 Sep 2017 16:03:06 +0000 (UTC)
picca <notifications@github.com> wrote:

> Hello, if I do not give a mask it cause some troubles.
> 
> It should not ;)

I suspect an automatic binning issue. Could you confirm me the size of the mask, the size of the image and the size of the detector ?

Thanks

Jerome

**Comment by picca** [comment]
Hello Jerome,

this is SX165 detector and the images are 

```
$ file L395_1000h_B4C_1_omega0.1_60s_1.mccd
L395_1000h_B4C_1_omega0.1_60s_1.mccd: MAR Area Detector Image, Compressed(1003), 2048 x 2048, 16 bits/pixel
```
the problem is when there is no mask at all.
If we add a mask with the same size there is no issue.

**Comment by kif** [comment]
Did you check the results are valid ? 
Is the pixel size 7.9e-5 (for binning 2x2) or 3.950e-05 (without binning)

You can run it with "python -i",  retrieve the AzimuthalIntegrator, then the detector and check for its size.
