### ISSUE TITLE
[mx-calib] Exception if the calibrant is not specified

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#699]
That's a small thing which can be avoided.
```
ERROR:pyFAI.calibration:The calibrant is mandatory: please use the -c option
Traceback (most recent call last):
  File "./bootstrap.py", line 202, in <module>
    run_entry_point(target, argv)
  File "./bootstrap.py", line 127, in run_entry_point
    func()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/app/mx_calibrate.py", line 66, in main
    c.read_dSpacingFile()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/calibration.py", line 2025, in read_dSpacingFile
    elif os.path.isfile(self.calibrant):
  File "/usr/lib/python2.7/genericpath.py", line 29, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by vallsv** [comment]
Who cares.
