### ISSUE TITLE
done is crashing in pyFAI-calib...

### ISSUE THREAD

**Issue by jonwright** [silx-kit/pyFAI#701]
```
rnice8-0307:~/id11/CeO2_calib1_dist1_ % pwd
/data/visitor/ch5141/id11/CeO2_calib1_dist1_

rnice8-0307:~/id11/CeO2_calib1_dist1_ % pyFAI-calib CeO2_calib1_dist1_0mean_180_files.edf -c CeO2 -p 50 -w 0.3088 -s f4mnew.spline

...

Fixed: wavelength
Modify parameters (or ? for help)?	 done
Traceback (most recent call last):
  File "/usr/bin/pyFAI-calib", line 9, in <module>
    load_entry_point('pyFAI==0.14.2', 'console_scripts', 'pyFAI-calib')()
  File "/usr/lib/python2.7/dist-packages/pyFAI/app/calib.py", line 67, in main
    c.gui_peakPicker()
  File "/usr/lib/python2.7/dist-packages/pyFAI/calibration.py", line 1498, in gui_peakPicker
    self.set_data(self.peakPicker.finish(self.pointfile))
  File "/usr/lib/python2.7/dist-packages/pyFAI/calibration.py", line 1318, in set_data
    self.refine()
  File "/usr/lib/python2.7/dist-packages/pyFAI/calibration.py", line 1595, in refine
    AbstractCalibration.refine(self)
  File "/usr/lib/python2.7/dist-packages/pyFAI/calibration.py", line 770, in refine
    finished = self.prompt()
  File "/usr/lib/python2.7/dist-packages/pyFAI/calibration.py", line 957, in prompt
    self.postProcess()
  File "/usr/lib/python2.7/dist-packages/pyFAI/calibration.py", line 1144, in postProcess
    self.geoRef.mask = self.mask
  File "/usr/lib/python2.7/dist-packages/pyFAI/geometry.py", line 2039, in set_mask
    self.detector.set_mask(mask)
  File "/usr/lib/python2.7/dist-packages/pyFAI/detectors.py", line 690, in set_mask
    self.guess_binning(mask)
  File "/usr/lib/python2.7/dist-packages/pyFAI/detectors.py", line 639, in guess_binning
    shape = tuple(data[:2])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by kif** [comment]
On Thu, 28 Sep 2017 15:00:02 +0000 (UTC)
Jon Wright <notifications@github.com> wrote:

> rnice8-0307:~/id11/CeO2_calib1_dist1_ % pwd
> /data/visitor/ch5141/id11/CeO2_calib1_dist1_
> 
> rnice8-0307:~/id11/CeO2_calib1_dist1_ % pyFAI-calib CeO2_calib1_dist1_0mean_180_files.edf -c CeO2 -p 50 -w 0.3088 -s f4mnew.spline

Thanks for the report,

Just to confirm, could you tell me the size of the image?

**Comment by jonwright** [comment]
Image is 2048x2048 FloatValue written by pyFAI-average. I guess the problem is not using a mask?

**Comment by kif** [comment]
On Thu, 28 Sep 2017 17:27:23 +0000 (UTC)
Jon Wright <notifications@github.com> wrote:

> Image is 2048x2048 FloatValue written by pyFAI-average. I guess the problem is not using a mask?

I have to investigate why data was still None at this stage ...

**Comment by kif** [comment]
Hi Jon, 
could you send me the images ?
I did not manage to reproduce the bug.
Is the file actually available ? why do you specify both the pixel size AND the spline ?
What is the size of the detector described in the spline ?

**Comment by jonwright** [comment]
Files are on /tmp_14_days/wright/pyFAI_701

You can drop the pixel size from the command line and it reproduces. That seems to need an error or warning if a spline is provided?

The problem goes away when a mask is provided. It just reproduced on rnice8 using this:

```
% pyFAI-calib -c CeO2 -e 40 -s f4mnew.spline CeO2_calib1_dist1_0mean_180_files.edf  <<EOF

0
done

EOF

```

**Comment by kif** [comment]
On Fri, 29 Sep 2017 08:04:41 +0000 (UTC)
Jon Wright <notifications@github.com> wrote:

> Files are on /tmp_14_days/wright/pyFAI_701

OK the bug is when one wants to integrate...

-- 
Jérôme Kieffer
tel +33 476 882 445
