### ISSUE TITLE
problem when importing from  pyFAI.gui jupyter

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#709]
Hello guyes,

Here a difference between python2 and python3 with the 0.14.2 pyFAI.
it doesn not work with python2 but it works with python3

```
picca@diffabs6:~/jupyter/mars/20160800/published-data$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyFAI.gui import jupyter
WARNING:pyFAI.opencl.common:Unable to import pyOpenCl. Please install it from: http://pypi.python.org/pypi/pyopencl
WARNING:pyFAI.gui.matplotlib:matplotlib already loaded, setting its backend may not work
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pyFAI/gui/jupyter.py", line 44, in <module>
    from matplotlib import lines
ImportError: cannot import name lines
>>> 
picca@diffabs6:~/jupyter/mars/20160800/published-data$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyFAI.gui import jupyter
WARNING:pyFAI.opencl.common:Unable to import pyOpenCl. Please install it from: http://pypi.python.org/pypi/pyopencl
>>> 
```

**Comment by kif** [comment]
Apparently Valentin fixed it ... 
see #713
