### ISSUE TITLE
Use context manager for average

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#719]
```
ERROR:fabio.openimage:[Errno 24] Too many open files: 'ID15/dt_0418.cbf': File probably does not exist
Traceback (most recent call last):
  File "/usr/bin/pyFAI-average", line 11, in <module>
  File "/usr/lib/python2.7/dist-packages/pyFAI/app/average.py", line 315, in main
  File "/usr/lib/python2.7/dist-packages/pyFAI/average.py", line 803, in set_images
  File "/usr/lib/python2.7/dist-packages/fabio/openimage.py", line 136, in openimage
  File "/usr/lib/python2.7/dist-packages/fabio/openimage.py", line 187, in _openimage
IOError: [Errno 24] Too many open files: 'ID15/dt_0418.cbf'
```

**Comment by vallsv** [comment]
For that there is things to rework, but it is anyway a good idea to remove FabioImage from the intermediate data structure.

Is it possible to have a way to test it? How many files did you open?

**Comment by kif** [comment]
On Tue, 31 Oct 2017 07:58:04 +0000 (UTC)
Valentin Valls <notifications@github.com> wrote:

> For that there is things to rework, but it is anyway a good idea to remove FabioImage from the intermediate data structure.
> 
> Is it possible to have a way to test it? How many files did you open?

1202 in my test case (the limit is ~1000)

-- 
Jérôme Kieffer
