### ISSUE TITLE
Debian CI: many ascii errors... plus one OpenCL

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#738]
```
======================================================================
ERROR: test_OpenCL (pyFAI.test.test_openCL.TestMask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyFAI/test/test_openCL.py", line 123, in test_OpenCL
    res = ai.xrpd_OpenCL(data, self.N, devicetype="all", platformid=ids[0], deviceid=ids[1], useFp64=True)
  File "/usr/lib/python2.7/dist-packages/pyFAI/decorators.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyFAI/azimuthalIntegrator.py", line 960, in xrpd_OpenCL
    useFp64=useFp64)
  File "/usr/lib/python2.7/dist-packages/pyFAI/opencl/azim_hist.py", line 689, in init
    self.devicetype = pyopencl.device_type.to_string(device.type)
  File "/usr/lib/python2.7/dist-packages/pyopencl/cffi_cl.py", line 310, in to_string
    % (value, cls.__name__))
ValueError: a name for value 3 was not found in device_type

======================================================================
ERROR: test_integrate_counter_monitor (pyFAI.test.test_integrate_app.TestIntegrateApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyFAI/test/test_integrate_app.py", line 161, in test_integrate_counter_monitor
    pyFAI.app.integrate.integrate_shell(options, [datapath])
  File "/usr/lib/python2.7/dist-packages/pyFAI/app/integrate.py", line 146, in integrate_shell
    progress_bar.update(i + 1, message=message)
  File "/usr/lib/python2.7/dist-packages/pyFAI/utils/shell.py", line 126, in update
    sys.stdout.write(line + " " * clean_size + "\r")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-37: ordinal not in range(128)

======================================================================
ERROR: test_integrate_default_output_azim (pyFAI.test.test_integrate_app.TestIntegrateApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyFAI/test/test_integrate_app.py", line 106, in test_integrate_default_output_azim
    pyFAI.app.integrate.integrate_shell(options, [datapath])
  File "/usr/lib/python2.7/dist-packages/pyFAI/app/integrate.py", line 146, in integrate_shell
    progress_bar.update(i + 1, message=message)
  File "/usr/lib/python2.7/dist-packages/pyFAI/utils/shell.py", line 126, in update
    sys.stdout.write(line + " " * clean_size + "\r")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-37: ordinal not in range(128)

======================================================================
ERROR: test_integrate_default_output_dat (pyFAI.test.test_integrate_app.TestIntegrateApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyFAI/test/test_integrate_app.py", line 96, in test_integrate_default_output_dat
    pyFAI.app.integrate.integrate_shell(options, [datapath])
  File "/usr/lib/python2.7/dist-packages/pyFAI/app/integrate.py", line 146, in integrate_shell
    progress_bar.update(i + 1, message=message)
  File "/usr/lib/python2.7/dist-packages/pyFAI/utils/shell.py", line 126, in update
    sys.stdout.write(line + " " * clean_size + "\r")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-37: ordinal not in range(128)

======================================================================
ERROR: test_integrate_file_output_dat (pyFAI.test.test_integrate_app.TestIntegrateApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyFAI/test/test_integrate_app.py", line 118, in test_integrate_file_output_dat
    pyFAI.app.integrate.integrate_shell(options, [datapath])
  File "/usr/lib/python2.7/dist-packages/pyFAI/app/integrate.py", line 146, in integrate_shell
    progress_bar.update(i + 1, message=message)
  File "/usr/lib/python2.7/dist-packages/pyFAI/utils/shell.py", line 126, in update
    sys.stdout.write(line + " " * clean_size + "\r")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-37: ordinal not in range(128)

======================================================================
ERROR: test_integrate_monitor (pyFAI.test.test_integrate_app.TestIntegrateApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyFAI/test/test_integrate_app.py", line 146, in test_integrate_monitor
    pyFAI.app.integrate.integrate_shell(options, [datapath])
  File "/usr/lib/python2.7/dist-packages/pyFAI/app/integrate.py", line 146, in integrate_shell
    progress_bar.update(i + 1, message=message)
  File "/usr/lib/python2.7/dist-packages/pyFAI/utils/shell.py", line 126, in update
    sys.stdout.write(line + " " * clean_size + "\r")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-37: ordinal not in range(128)

======================================================================
ERROR: test_integrate_no_monitor (pyFAI.test.test_integrate_app.TestIntegrateApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyFAI/test/test_integrate_app.py", line 131, in test_integrate_no_monitor
    pyFAI.app.integrate.integrate_shell(options, [datapath])
  File "/usr/lib/python2.7/dist-packages/pyFAI/app/integrate.py", line 146, in integrate_shell
    progress_bar.update(i + 1, message=message)
  File "/usr/lib/python2.7/dist-packages/pyFAI/utils/shell.py", line 126, in update
    sys.stdout.write(line + " " * clean_size + "\r")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-37: ordinal not in range(128)

======================================================================
ERROR: test_coverage (pyFAI.test.test_utils_shell.TestUtilShell)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyFAI/test/test_utils_shell.py", line 51, in test_coverage
    progressbar.update(10.5, "toto")
  File "/usr/lib/python2.7/dist-packages/pyFAI/utils/shell.py", line 126, in update
    sys.stdout.write(line + " " * clean_size + "\r")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-23: ordinal not in range(128)
```

**Comment by vallsv** [comment]
Do you have access to the encodage of your shell? It can be interesting to check.

**Comment by kif** [comment]
The openCL bug is related to the device type which value is 3 which correspond to "default+CPU"
I guess this bug has to be reported to Andreas @inducer

**Comment by kif** [comment]
Fixed upstream for the pyopencl part.
@picca, did you see the comment of Valentin ?

**Comment by picca** [comment]
No, I have no idea, there is an autopkgttest-amd64-sid chroot, but I do not know the shell encoding.
I think that we should discuss abotu this on the 

debian-qa@lists.debain.org

**Comment by vallsv** [comment]
We are using a Unicode character for the shell progress bar. But only of it is supported by the shell.

To check if it is supported we are using:
```
        encoding = None
        if hasattr(sys.stdout, "encoding"):
            encoding = sys.stdout.encoding
        if encoding is None:
            import locale
            _lang, encoding = locale.getdefaultlocale()
        try:
            self.progress_char = u'\u25A0'
            _byte = codecs.encode(self.progress_char, encoding)
        except (ValueError, TypeError, LookupError):
            # In case the char is not supported by the encoding,
            # or if the encoding does not exists
            self.progress_char = '#'
```

I guess that is the problem, but i have no idea.

**Comment by picca** [comment]
Maybe this is just because the `UnicodeEncodeError` exception is not catched in your code ?

**Comment by vallsv** [comment]
I don't think so. The code i should you is part of the constructor, and the exception is not raised in this part of the code.

The point here is `stdout` do not have the encoding expected. Then maybe it does not provide `sys.stdout.encoding`, maybe `getdefaultlocale` returns a dirty thing, maybe there is another way to reach the encoding. From https://stackoverflow.com/questions/492483/setting-the-correct-encoding-when-piping-stdout-in-python people also use `getfilesystemencoding`, and `PYTHONIOENCODING`. 

I would expect a cleaner API... That is why i would like a little more information.

**Comment by vallsv** [comment]
Would it be possible to execute a script of the computer? To check the result?
```
import os
import sys
import locale

if hasattr(sys.stdout, "encoding"):
    print(sys.stdout.encoding)
print(sys.stdout.isatty())
print(locale.getpreferredencoding())
print(sys.getfilesystemencoding())
print(os.environ["PYTHONIOENCODING"])
```

**Comment by vallsv** [comment]
Trying to fix the tests is a nightmare, then i have patched the source code.
Hope this fix the issue.

**Comment by picca** [comment]
Hello here the log for 0.15 :), There is only 12 test which dos not pass.

https://ci.debian.net/data/autopkgtest/unstable/amd64/p/pyfai/20180204_095852/log.gz

They seems to be all OpenCL related.

**Comment by kif** [comment]
On Sun, 04 Feb 2018 12:43:33 +0000 (UTC)
picca <notifications@github.com> wrote:

> Hello here the log for 0.15 :), There is only 12 test which dos not pass.
> 
> https://ci.debian.net/data/autopkgtest/unstable/amd64/p/pyfai/20180204_095852/log.gz
> 
> They seems to be all OpenCL related.

They are all related to one single function which is the bitonic sort.
I know it does not pass on POCL. It needs investigation as this piece
of code is the most complicated on in pyFAI.

The strange is it passes with most other drivers (AMD, Intel, NVidia, Beignet, ...)

**Comment by vallsv** [comment]
The other problem looks to be unclosed text files. I will open an issue for this one.

**Comment by kif** [comment]
unclosed files have been closed ...
