### ISSUE TITLE
[calib2] guess binning sometime wrong

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#760]
```
Traceback (most recent call last):
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/gui/calibration/PeakPickingTask.py", line 808, in __autoExtractRings
    detector = self.model().experimentSettingsModel().detector()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/gui/calibration/model/ExperimentSettingsModel.py", line 91, in detector
    detector.guess_binning(image)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/detectors.py", line 1978, in guess_binning
    self._pixel1 = self.BINNED_PIXEL_SIZE[bin1]
KeyError: 0
```

**Comment by vallsv** [comment]
```
In [1]: import pyFAI.detectors

In [2]: detector = pyFAI.detectors.RayonixLx255()

In [3]: import numpy

In [5]: image = numpy.zeros(shape=(3072, 3072))

In [6]: image
Out[6]: 
array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [7]: detector.guess_binning(image)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/workspace/valls/pyfai.git/bootstrap.py in <module>()
----> 1 detector.guess_binning(image)

/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/detectors.pyc in guess_binning(self, data)
   1976         self.shape = shape
   1977         self.max_shape = shape
-> 1978         self._pixel1 = self.BINNED_PIXEL_SIZE[bin1]
   1979         self._pixel2 = self.BINNED_PIXEL_SIZE[bin2]
   1980         self._mask = False

KeyError: 0

**Comment by vallsv** [comment]
Ok, that's normal, the image size is just not compatible with this detector.
It would be good to return a right exception.

**Comment by vallsv** [comment]
```
max_shape = (1920, 5760)
image shape = (3072, 3072)
bin1, bin2 = 0 1
```

**Comment by vallsv** [comment]
There is a lot of Rayonix detector sizes, it is quite easy to select the wrong one.

**Comment by vallsv** [comment]
This one is still not good i guess:
```
In [4]: if True:
   ...:     import numpy
   ...:     import pyFAI.detectors
   ...:     detector = pyFAI.detectors.RayonixMx225hs()
   ...:     image = numpy.zeros(shape=(3072, 3072))
   ...:     detector.guess_binning(image)
   ...:     
(5760, 5760)
(3072, 3072)
1 1
```

This one is fine
```
In [5]: if True:
   ...:     import numpy
   ...:     import pyFAI.detectors
   ...:     detector = pyFAI.detectors.RayonixMx225()
   ...:     image = numpy.zeros(shape=(3072, 3072))
   ...:     detector.guess_binning(image)
   ...:     
(6144, 6144)
(3072, 3072)
2 2
```

The GUI should show that issue.

**Comment by vallsv** [comment]
The bug is here
```
import numpy
import pyFAI.detectors
detector = pyFAI.detectors.RayonixMx225()
image = numpy.zeros(shape=(3072, 3072))
```

The bug is here:
```
detector.guess_binning(image)
detector.get_binning()
# Out[7]: (2, 2)
detector.guess_binning(image)
detector.get_binning()
# Out[7]: (1, 1)
```
`max_size` is patched on `guess_binning`, then the next guess became wrong.
