### ISSUE TITLE
testing scripts fails with python 3.5

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#766]
The failing test is:
pyFAI.test.test_bug_regression.TestBug211
```
Traceback (most recent call last):
  File "/users/kieffer/workspace-400/pyFAI/build/lib.linux-x86_64-3.5/pyFAI/test/test_bug_regression.py", line 149, in test_quantile
    self.fail()
AssertionError: None
```
which means this command failed: 
```/usr/bin/python3 /usr/bin/pyFAI-average --quiet -q 0.2-0.8 ...```
with:
```
Traceback (most recent call last):
  File "/usr/bin/pyFAI-average", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyFAI==0.15.0a1' distribution was not found and is required by the application
```
On the other hand:
```/usr/bin/pyFAI-average --quiet -q 0.2-0.8 ...```
works.

Is this test still valid ? because the tested script is not the right one.

**Comment by kif** [comment]
apparently this is related to the installed version ... 
After upgrading "blindly" the test passes again.
not very reliable as test.

**Comment by vallsv** [comment]
I will rework this part.

- Fix this problem
- Still test scripts
- Avoid stdout logs on script tests
