### ISSUE TITLE
Icon issue in calib2

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#810]
```ERROR:pyFAI-calib2.UNCAUGHT:Not an icon name: remove-peak
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyFAI/gui/calibration/PeakPickingTask.py", line 436, in createEditor
    remove.setIcon(icons.getQIcon("remove-peak"))
  File "/usr/lib/python2.7/dist-packages/silx/gui/icons.py", line 330, in getQIcon
    qfile = getQFile(name)
  File "/usr/lib/python2.7/dist-packages/silx/gui/icons.py", line 399, in getQFile
    raise ValueError('Not an icon name: %s' % name)
```

**Comment by kif** [comment]
duplicate of 800
