### ISSUE TITLE
installation error for development version '0.16.0-dev0'

### ISSUE THREAD

**Issue by TheGrim1** [silx-kit/pyFAI#824]
I was able to install the then latest development version successfully in a venv on 06.04.18:
pyFAI.version =  '0.16.0-dev0'

However, now (18.04.18) it fails. I know its the dev version, but I wanted to use the nice new ai.setChiDiskZero(). I did:

virtualenv -p /usr/bin/python2.7 --system-site-packages ./ 
source bin/activate
# setting of proxys
python -m pip install --upgrade pip
pip install --upgrade pip
pip install setuptools --upgrade
pip install wheel --upgrade
pip install ipython --upgrade
pip install numpy --upgrade
pip install scipy --upgrade
pip install h5py
pip install appdirs --upgrade
pip install silx --upgrade
git clone https://github.com/silx-kit/pyFAI.git
cd pyFAI
python setup.py build bdist_wheel
pip install . --upgrade

on both 'nanofocus' (/data/id13/inhouse6/COMMON_DEVELOP/py_andreas/test_venv) and 'lid13gpu1' 

and get the Traceback:
Exception:
Traceback (most recent call last):
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/test_venv/local/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/test_venv/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/test_venv/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/test_venv/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/test_venv/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/test_venv/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 322, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/test_venv/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 126, in prep_for_dist
    build_requirements, isolate = self.req.get_pep_518_info()
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/test_venv/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 448, in get_pep_518_info
    pp_toml = pytoml.load(f)
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/test_venv/local/lib/python2.7/site-packages/pip/_vendor/pytoml/parser.py", line 10, in load
    return loads(fin.read(), translate=translate, filename=getattr(fin, 'name', repr(fin)))
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/test_venv/local/lib/python2.7/site-packages/pip/_vendor/pytoml/parser.py", line 23, in loads
    ast = _p_toml(src)
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/test_venv/local/lib/python2.7/site-packages/pip/_vendor/pytoml/parser.py", line 352, in _p_toml
    s.expect_eof()
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/test_venv/local/lib/python2.7/site-packages/pip/_vendor/pytoml/parser.py", line 124, in expect_eof
    return self._expect(self.consume_eof())
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/test_venv/local/lib/python2.7/site-packages/pip/_vendor/pytoml/parser.py", line 164, in _expect
    raise TomlError('msg', self._pos[0], self._pos[1], self._filename)
TomlError: /tmp/pip-req-build-SND362/pyproject.toml(2, 1): msg

**Comment by vallsv** [comment]
Hi.

Could you please check to install the wheel you just compiled? Instead of installing from "."?

Maybe something like
```
pip install --upgrade dist/*.whl
```

**Comment by vallsv** [comment]
Anyway, no idea what this messages mean.

**Comment by vallsv** [comment]
Here i installed the last pip (10.0.0) and it looks to be buggy

**Comment by TheGrim1** [comment]
>> pip install --upgrade dist/*.whl

this works!

**Comment by vallsv** [comment]
You could also test
```
pip install --user --upgrade-strategy=only-if-needed .
```
or
```
pip install --user --no-deps .
```
As it looks like the problem come from `pytoml`, and pyfai do not expect this package, AFAIK.

**Comment by vallsv** [comment]
Here on debian8 i can reproduce the problem.
That's right that now it matches... we added recnedly a toml file in pyfai. I will check that.

**Comment by vallsv** [comment]
Problem found, it was a typo on the file.
Thanks a lot for the feedback.
