### ISSUE TITLE
[calib2] Matplotlib issue happend while creating a zoom rectangle on the first plot

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#891]
Dev version of calib2

Something is maybe important inside.
```
Traceback (most recent call last):
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 388, in process
    proxy(*args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 228, in __call__
    return mtd(*args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 977, in _onMouseRelease
    self._MPL_TO_PLOT_BUTTONS[event.button])
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotWidget.py", line 2866, in onMouseRelease
    self._eventHandler.handleEvent('release', xPixel, yPixel, btn)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotInteraction.py", line 1603, in handleEvent
    self._eventHandler.handleEvent(event, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/Interaction.py", line 192, in handleEvent
    return handler(*args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/Interaction.py", line 260, in onRelease
    self.machine.endDrag(self.initPos, (x, y))
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotInteraction.py", line 1405, in endDrag
    return self._zoom.endDrag(startPos, endPos)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotInteraction.py", line 378, in endDrag
    self.plot.setLimits(xMin, xMax, yMin, yMax, y2Min, y2Max)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotWidget.py", line 2005, in setLimits
    self._notifyLimitsChanged()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotWidget.py", line 1916, in _notifyLimitsChanged
    xRange = self._xAxis.getLimits()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/items/axis.py", line 120, in getLimits
    return self._internalGetLimits()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/items/axis.py", line 405, in _internalGetLimits
    return self._getBackend().getGraphXLimits()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 709, in getGraphXLimits
    self.replot()  # makes sure we get the right limits
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1108, in replot
    self.draw()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1062, in draw
    FigureCanvasQTAgg.draw(self)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 433, in draw
    self.figure.draw(self.renderer)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 2607, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/matplotlib/ModestImage.py", line 174, in draw
    super(ModestImage, self).draw(renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 593, in draw
    renderer, renderer.get_image_magnification())
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 841, in make_image
    unsampled=unsampled)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 305, in _make_image
    raise RuntimeError("_make_image must get a non-empty image. "
RuntimeError: _make_image must get a non-empty image. Your Artist's draw method must filter before this method is called.
ERROR:pyFAI-calib2.UNCAUGHT:_make_image must get a non-empty image. Your Artist's draw method must filter before this method is called.
Traceback (most recent call last):
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/backends/BackendBase.py", line 316, in postRedisplay
    plot.replot()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotWidget.py", line 2503, in replot
    self._backend.replot()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1108, in replot
    self.draw()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1062, in draw
    FigureCanvasQTAgg.draw(self)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 433, in draw
    self.figure.draw(self.renderer)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 2607, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/matplotlib/ModestImage.py", line 174, in draw
    super(ModestImage, self).draw(renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 593, in draw
    renderer, renderer.get_image_magnification())
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 841, in make_image
    unsampled=unsampled)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 305, in _make_image
    raise RuntimeError("_make_image must get a non-empty image. "
RuntimeError: _make_image must get a non-empty image. Your Artist's draw method must filter before this method is called.
Traceback (most recent call last):
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 388, in process
    proxy(*args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 228, in __call__
    return mtd(*args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 977, in _onMouseRelease
    self._MPL_TO_PLOT_BUTTONS[event.button])
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotWidget.py", line 2866, in onMouseRelease
    self._eventHandler.handleEvent('release', xPixel, yPixel, btn)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotInteraction.py", line 1603, in handleEvent
    self._eventHandler.handleEvent(event, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/Interaction.py", line 192, in handleEvent
    return handler(*args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/Interaction.py", line 260, in onRelease
    self.machine.endDrag(self.initPos, (x, y))
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotInteraction.py", line 1405, in endDrag
    return self._zoom.endDrag(startPos, endPos)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotInteraction.py", line 378, in endDrag
    self.plot.setLimits(xMin, xMax, yMin, yMax, y2Min, y2Max)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotWidget.py", line 2005, in setLimits
    self._notifyLimitsChanged()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotWidget.py", line 1916, in _notifyLimitsChanged
    xRange = self._xAxis.getLimits()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/items/axis.py", line 120, in getLimits
    return self._internalGetLimits()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/items/axis.py", line 405, in _internalGetLimits
    return self._getBackend().getGraphXLimits()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 709, in getGraphXLimits
    self.replot()  # makes sure we get the right limits
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1108, in replot
    self.draw()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1062, in draw
    FigureCanvasQTAgg.draw(self)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 433, in draw
    self.figure.draw(self.renderer)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 2607, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/matplotlib/ModestImage.py", line 174, in draw
    super(ModestImage, self).draw(renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 593, in draw
    renderer, renderer.get_image_magnification())
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 841, in make_image
    unsampled=unsampled)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 305, in _make_image
    raise RuntimeError("_make_image must get a non-empty image. "
RuntimeError: _make_image must get a non-empty image. Your Artist's draw method must filter before this method is called.
Traceback (most recent call last):
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 388, in process
    proxy(*args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 228, in __call__
    return mtd(*args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 977, in _onMouseRelease
    self._MPL_TO_PLOT_BUTTONS[event.button])
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotWidget.py", line 2866, in onMouseRelease
    self._eventHandler.handleEvent('release', xPixel, yPixel, btn)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotInteraction.py", line 1603, in handleEvent
    self._eventHandler.handleEvent(event, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/Interaction.py", line 192, in handleEvent
    return handler(*args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/Interaction.py", line 260, in onRelease
    self.machine.endDrag(self.initPos, (x, y))
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotInteraction.py", line 1405, in endDrag
    return self._zoom.endDrag(startPos, endPos)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotInteraction.py", line 378, in endDrag
    self.plot.setLimits(xMin, xMax, yMin, yMax, y2Min, y2Max)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotWidget.py", line 2005, in setLimits
    self._notifyLimitsChanged()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/PlotWidget.py", line 1916, in _notifyLimitsChanged
    xRange = self._xAxis.getLimits()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/items/axis.py", line 120, in getLimits
    return self._internalGetLimits()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/items/axis.py", line 405, in _internalGetLimits
    return self._getBackend().getGraphXLimits()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 709, in getGraphXLimits
    self.replot()  # makes sure we get the right limits
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1108, in replot
    self.draw()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1062, in draw
    FigureCanvasQTAgg.draw(self)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 433, in draw
    self.figure.draw(self.renderer)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 2607, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/matplotlib/ModestImage.py", line 174, in draw
    super(ModestImage, self).draw(renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 593, in draw
    renderer, renderer.get_image_magnification())
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 841, in make_image
    unsampled=unsampled)
  File "/home/valls/.local/lib/python3.5/site-packages/matplotlib/image.py", line 305, in _make_image
    raise RuntimeError("_make_image must get a non-empty image. "
RuntimeError: _make_image must get a non-empty image. Your Artist's draw method must filter before this method is called.
```

**Comment by vallsv** [comment]
Reproducible when creating a zoom rect outside of the displayed image

**Comment by vallsv** [comment]
It looks to be specific to pyfai. Maybe a special configuration of the plot...

**Comment by vallsv** [comment]
Reproducible with silx only. I create https://github.com/silx-kit/silx/issues/2073

**Comment by vallsv** [comment]
Looks to be fixed on silx by https://github.com/silx-kit/silx/pull/2092
