### ISSUE TITLE
[calib2] pixel coordinate issue when using a spline file

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#924]
```
ERROR:pyFAI-calib2.UNCAUGHT:invalid index to scalar variable.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyFAI/gui/calibration/GeometryTask.py", line 527, in __mouseMoved
    chi = geometry.chi(ay, ax)[0]
  File "/usr/lib/python2.7/dist-packages/pyFAI/geometry.py", line 516, in chi
    p1, p2, p3 = self._calc_cartesian_positions(d1, d2, self._poni1, self._poni2)
  File "/usr/lib/python2.7/dist-packages/pyFAI/geometry.py", line 218, in _calc_cartesian_positions
    p1, p2, p3 = self.detector.calc_cartesian_positions(d1, d2)
  File "/usr/lib/python2.7/dist-packages/pyFAI/detectors/_common.py", line 599, in calc_cartesian_positions
    self._splineCache[keyX] = self.spline.splineFuncX(d2c, d1c, True).astype(numpy.float64)
  File "/usr/lib/python2.7/dist-packages/pyFAI/spline.py", line 376, in splineFuncX
    return xDispArray[x_unordered, y_unordered]
IndexError: invalid index to scalar variable.
```

**Comment by kif** [comment]
to reproduce:
```
d = pyFAI.detector_factory("Frelon", {"splineFile": "/users/kieffer/workspace-400/pyFAI/testimages/halfccd.spline"})
ai = pyFAI.AzimuthalIntegrator(detctor=d)
ai.chi(numpy.array([10]),numpy.array([10]))
```
The problem is apparently within the spline code.

**Comment by vallsv** [comment]
Already done
