### ISSUE TITLE
[calib2] Small things

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#933]
- [x] The displayed RMS is not updated correctly when the fit do not change anything
- [x] Import/export mask have to be propagated to the application model
- [x] Problem when file from comment line do not exists
- [x] `ds` extension also have to be used for calibrant files
- [x] Mouse cursor have to be set to a waiting icon when processing.
- [x] The rendering of the detector dialog have to be fixed (underscore font looks to be not available everywhere, or there is another glitch)
- [x] It could be nice to move the load/save peaks close the the list of the peaks
- [x] Problem to update the zoom on the cake (the first automatically done is wrong)
- [x] #928
- [x] #929

**Comment by vallsv** [comment]
Check this logs
```
ERROR:pyFAI.massif:You picked a background point at [1198, 512]
INFO:pyFAI.massif:Image size is (2167, 2070)
INFO:pyFAI.massif:Binning size is [1, 1]
INFO:pyFAI.massif:Labeling found 41561 massifs.
INFO:pyFAI.massif:Labeling found 41561 massifs.
INFO:pyFAI.massif:Image size is (2167, 2070)
INFO:pyFAI.massif:Binning size is [1, 1]
INFO:pyFAI.massif:Labeling found 41561 massifs.
INFO:pyFAI.massif:Labeling found 41561 massifs.
^CERROR:pyFAI-calib2.UNCAUGHT:
Traceback (most recent call last):
  File "/mntdirect/_bliss/users/valls/env/pyfai-gui-py35/lib/python3.5/site-packages/pyFAI/gui/calibration/PeakPickingTask.py", line 844, in __autoExtractRings
    pointPerDegree=pointPerDegree)
  File "/mntdirect/_bliss/users/valls/env/pyfai-gui-py35/lib/python3.5/site-packages/pyFAI/gui/calibration/RingExtractor.py", line 134, in extract
    geoRef = self.__createGeoRef(peaks, fixed=fixed)
  File "/mntdirect/_bliss/users/valls/env/pyfai-gui-py35/lib/python3.5/site-packages/pyFAI/gui/calibration/RingExtractor.py", line 93, in __createGeoRef
    geoRef.refine2(1000000, fix=fixed)
  File "/mntdirect/_bliss/users/valls/env/pyfai-gui-py35/lib/python3.5/site-packages/pyFAI/geometryRefinement.py", line 342, in refine2
    iprint=(logger.getEffectiveLevel() <= logging.INFO))
  File "/usr/lib/python3/dist-packages/scipy/optimize/slsqp.py", line 207, in fmin_slsqp
    constraints=cons, **opts)
  File "/usr/lib/python3/dist-packages/scipy/optimize/slsqp.py", line 367, in _minimize_slsqp
    fx = func(x)
  File "/usr/lib/python3/dist-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "/mntdirect/_bliss/users/valls/env/pyfai-gui-py35/lib/python3.5/site-packages/pyFAI/geometryRefinement.py", line 279, in residu2
    t = self.residu1(param, d1, d2, rings)
  File "/mntdirect/_bliss/users/valls/env/pyfai-gui-py35/lib/python3.5/site-packages/pyFAI/geometryRefinement.py", line 271, in residu1
    return self.tth(d1, d2, param) - self.calc_2th(rings, self.wavelength)
  File "/mntdirect/_bliss/users/valls/env/pyfai-gui-py35/lib/python3.5/site-packages/pyFAI/geometry.py", line 311, in tth
    pos3=p3)
  File "pyFAI/ext/_geometry.pyx", line 297, in pyFAI.ext._geometry.calc_tth (pyFAI/ext/_geometry.c:5362)
  File "/usr/lib/python3/dist-packages/numpy/core/numeric.py", line 463, in asarray
    def asarray(a, dtype=None, order=None):
KeyboardInterrupt: 




^CERROR:pyFAI-calib2.UNCAUGHT:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/silx/gui/icons.py", line 213, in __increaseFrame
    def __increaseFrame(self):
KeyboardInterrupt: 
^CERROR:pyFAI-calib2.UNCAUGHT:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/silx/gui/icons.py", line 213, in __increaseFrame
    def __increaseFrame(self):
KeyboardInterrupt: 
^CERROR:pyFAI-calib2.UNCAUGHT:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/silx/gui/icons.py", line 213, in __increaseFrame
    def __increaseFrame(self):
KeyboardInterrupt: 
^CERROR:pyFAI-calib2.UNCAUGHT:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/silx/gui/icons.py", line 213, in __increaseFrame
    def __increaseFrame(self):
KeyboardInterrupt: 
^CERROR:pyFAI-calib2.UNCAUGHT:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/silx/gui/icons.py", line 213, in __increaseFrame
    def __increaseFrame(self):
KeyboardInterrupt: 
^CERROR:pyFAI-calib2.UNCAUGHT:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/silx/gui/icons.py", line 213, in __increaseFrame
    def __increaseFrame(self):
KeyboardInterrupt: 
^CERROR:pyFAI-calib2.UNCAUGHT:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/silx/gui/icons.py", line 213, in __increaseFrame
    def __increaseFrame(self):
KeyboardInterrupt: 
```
