### ISSUE TITLE
[debian 10][i386] unit test error

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#974]
Hello, I have an FTBFS on i386 architecture.

result are close to the exepcted values.
So maybe this is precision issue on 32 bit arch, but it works on the armhf architecture :)

```
mkdir -p /<<BUILDDIR>>/pyfai-0.16.0+dfsg1/.cache/ # create POCL cachedir in order to avoid an FTBFS in sbuild
PYBUILD_SYSTEM=custom \
PYBUILD_TEST_ARGS="PYTHONPATH={build_dir} http_proxy='127.0.0.1:9' PYFAI_TESTIMAGES=testimages PYFAI_DATA=/<<BUILDDIR>>/pyfai-0.16.0+dfsg1 xvfb-run -a --server-args=\"-screen 0 1024x768x24\" {interpreter} ./run_tests.py --low-mem --installed" dh_auto_test
I: pybuild base:217: PYTHONPATH=/<<BUILDDIR>>/pyfai-0.16.0+dfsg1/.pybuild/cpython2_2.7_pyfai/build http_proxy='127.0.0.1:9' PYFAI_TESTIMAGES=testimages PYFAI_DATA=/<<BUILDDIR>>/pyfai-0.16.0+dfsg1 xvfb-run -a --server-args="-screen 0 1024x768x24" python2.7 ./run_tests.py --low-mem --installed
INFO:pyFAI.setup:Use setuptools
INFO:pyFAI.setup:Use setuptools.setup
WARNING:pyFAI.directories:testimage directory testimages does not exist
WARNING:run_tests:Test pyFAI 0.16.0 from /<<BUILDDIR>>/pyfai-0.16.0+dfsg1/.pybuild/cpython2_2.7_pyfai/build/pyFAI
WARNING:py.warnings:/usr/lib/python2.7/dist-packages/scipy/spatial/__init__.py:96: ImportWarning: Not importing directory '/usr/lib/python2.7/dist-packages/scipy/spatial/qhull': missing __init__.py
  from .qhull import *

WARNING:py.warnings:/usr/lib/python2.7/dist-packages/scipy/optimize/_minimize.py:37: ImportWarning: Not importing directory '/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb': missing __init__.py
  from .lbfgsb import _minimize_lbfgsb

WARNING:py.warnings:/usr/lib/python2.7/dist-packages/qtconsole/rich_ipython_widget.py:2: DeprecationWarning: qtconsole.rich_ipython_widget is deprecated. use qtconsole.rich_jupyter_widget
  warnings.warn("qtconsole.rich_ipython_widget is deprecated. use qtconsole.rich_jupyter_widget", DeprecationWarning)

QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/2952', please create it with 0700 permissions.
sssss..................ss.................s..s....ssssssssss.s...............ssssssssssssssss.....F
Stderr:
WARNING:silx.opencl.common:Last chance to get an OpenCL device ... probably not the one requested
F
Stderr:
WARNING:silx.opencl.common:Last chance to get an OpenCL device ... probably not the one requested
ssssssssssssss.......ssssss...ssss..................ss...................................ss.s....sss....................................ss.....................
======================================================================
FAIL: test_dot16 (pyFAI.test.test_openCL.TestKahan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<BUILDDIR>>/pyfai-0.16.0+dfsg1/.pybuild/cpython2_2.7_pyfai/build/pyFAI/test/test_openCL.py", line 456, in test_dot16
    self.assertEqual(ref64, res)
AssertionError: 1431655765.0 != 1431655808.0

Stderr:
WARNING:silx.opencl.common:Last chance to get an OpenCL device ... probably not the one requested

======================================================================
FAIL: test_kahan (pyFAI.test.test_openCL.TestKahan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<BUILDDIR>>/pyfai-0.16.0+dfsg1/.pybuild/cpython2_2.7_pyfai/build/pyFAI/test/test_openCL.py", line 375, in test_kahan
    self.assertEqual(ref64, res)
AssertionError: 67108863.0 != 67108864.0

Stderr:
WARNING:silx.opencl.common:Last chance to get an OpenCL device ... probably not the one requested
```

**Comment by kif** [comment]
On Mon, 29 Oct 2018 18:16:37 +0000 (UTC)
picca <notifications@github.com> wrote:

> result are close to the exepcted values.
> So maybe this is precision issue on 32 bit arch, but it works on the armhf architecture :)

That's interesting ... I may dig out an i386 computer to actually test
on.

This test specifically tests the error compensation mechanisme used in
pyFAI to allow calculation in 32bits with a 48 bit precision. 
You will not be surprised if I ask you which OpenCL driver you used (and which
version)

Cheers,

Jerome

**Comment by kif** [comment]
On Tue, 30 Oct 2018 01:25:40 -0700
Valentin Valls <notifications@github.com> wrote:

> Hi Frederic. AFAIK pyFAI is not supposed to work on 32bits architectures. But I can be wrong.

indeed we never clained it was.

**Comment by kif** [comment]
We found the bug: the calculation performed on x87 registers have far to much precision which kills the error compensation mechanism. The workaround is to declare certain variables as "volatile" to enforce the variable to be actually stored in 32bits. Once done the compensation mechanism works again. 

Putting "volatile" has probably a cost as it writes the data to the memory. I will try to find a way to address this properly.

This is directly related to 
https://github.com/pocl/pocl/issues/680
