### ISSUE TITLE
[calib2] ZeroDivisionError when wavelength is set to 0

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#978]
It does not lock the application, but could be managed in a better way. Maybe.

A validator avoiding zero?

```
Traceback (most recent call last):
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/widgets/QuantityEdit.py", line 140, in keyPressEvent
    self.__returnPressed()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/widgets/QuantityEdit.py", line 158, in __returnPressed
    self.__applyText()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/widgets/QuantityEdit.py", line 184, in __applyText
    value = self.__convertToModel(value)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/widgets/QuantityEdit.py", line 168, in __convertToModel
    return units.convert(value, displayedUnit, internalUnit)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/utils/units.py", line 125, in convert
    return converter(value)
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/utils/units.py", line 101, in <lambda>
    _converters[(Unit.ENERGY, Unit.METER_WL)] = lambda v: (units.hc / v) / 1e10
ZeroDivisionError: float division by zero
```

**Comment by vallsv** [comment]
- Maybe the better solution to add constraints to this model and consider 0 as a wrong value.
- Another option is to add constraints on the widget validator.
