### ISSUE TITLE
[debian-ci][0.16] Here the errors during the ci test on Debian unstable

### ISSUE THREAD

**Issue by picca** [silx-kit/pyFAI#987]
Hello guyes, here the error reported by the Debian ci during the as installed unittest.

https://ci.debian.net/data/autopkgtest/unstable/amd64/p/pyfai/1241085/log.gz

cheers

Fred.

**Comment by kif** [comment]
On Sat, 03 Nov 2018 01:34:06 -0700
picca <notifications@github.com> wrote:

> Hello guyes, here the error reported by the Debian ci during the as installed unittest.
> 
> https://ci.debian.net/data/autopkgtest/unstable/amd64/p/pyfai/1241085/log.gz


thanks for the feed back ...

There has been one "out of memory", how large is the memory on this instance. apparently 6G, should be more than ennough

======================================================================
ERROR: test_writer (pyFAI.test.test_io.testFabIOWriter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyFAI/test/test_io.py", line 149, in test_writer
    writer.init({"nbpt_azim": shape[0], "nbpt_rad": shape[1], "prefix": "test"})
  File "/usr/lib/python2.7/dist-packages/pyFAI/io.py", line 800, in init
    self.directory = directory
NameError: global name 'directory' is not defined

Worth investigating ... I never had an issue on this.

======================================================================
ERROR: test (pyFAI.test.test_distortion.TestManual)
----------------------------------------------------------------------

I recently discovered this "pseudo test" was executed and was not intended to ...
we should either delete it or fix it.

**Comment by picca** [comment]
Maybe this is because I am using this command line in order to run the tests.

just tell me if I need to change the command line.

autopkgtest [15:30:16]: test command1: set -efu ; for py in $(pyversions -r 2>/dev/null) ; do cd "$AUTOPKGTEST_TMP" ; echo "Testing with $py:" ; xvfb-run -a --server-args="-screen 0 1024x768x24" $py -m unittest discover pyFAI 2>&1 ;

**Comment by kif** [comment]
On Sat, 03 Nov 2018 03:31:22 -0700
picca <notifications@github.com> wrote:

> Maybe this is because I am using this command line in order to run the tests.
> 
> just tell me if I need to change the command line.
> 
> autopkgtest [15:30:16]: test command1: set -efu ; for py in $(pyversions -r 2>/dev/null) ; do cd "$AUTOPKGTEST_TMP" ; echo "Testing with $py:" ; xvfb-run -a --server-args="-screen 0 1024x768x24" $py -m unittest discover pyFAI 2>&1 ; 

There are (at least) 2 alternatives:
* if the source directory is available, the easiest is to use "... $py run_tests.py --installed"
* else use ... $py -c "import pyFAI.test; pyFAI.test.run_tests()"

Cheers,

Jerome
