### ISSUE TITLE
[calib2] Segfault when fill rot2 with -90 deg

### ISSUE THREAD

**Issue by vallsv** [silx-kit/pyFAI#988]
Looks to be a problem inside bilinear.

```
[Thread 0x7fff6b7f6700 (LWP 5040) exited]
f1= -1.3767504060871606e+19
f2= 646.0

Program received signal SIGSEGV, Segmentation fault.
__pyx_pf_5pyFAI_3ext_8bilinear_6calc_cartesian_positions._omp_fn.4 () at pyFAI/ext/bilinear.c:5945
5945	                            __pyx_v_A1 = (*((float *) ( /* dim=3 */ ((char *) (((float *) ( /* dim=2 */ (( /* dim=1 */ (( /* dim=0 */ (__pyx_v_pos.data + __pyx_t_24 * __pyx_v_pos.strides[0]) ) + __pyx_t_25 * __pyx_v_pos.strides[1]) ) + __pyx_t_26 * __pyx_v_pos.strides[2]) )) + __pyx_t_27)) )));
(gdb) bt
#0  __pyx_pf_5pyFAI_3ext_8bilinear_6calc_cartesian_positions._omp_fn.4 () at pyFAI/ext/bilinear.c:5945
#1  0x00007fffa5c6c7df in GOMP_parallel () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007fffa554e71b in __pyx_pf_5pyFAI_3ext_8bilinear_6calc_cartesian_positions (__pyx_self=<optimized out>, __pyx_v_is_flat=<optimized out>, __pyx_v_pos=..., 
    __pyx_v_d2=..., __pyx_v_d1=...) at pyFAI/ext/bilinear.c:5434
#3  __pyx_fuse_1__pyx_pw_5pyFAI_3ext_8bilinear_7calc_cartesian_positions (__pyx_self=0x7920, __pyx_args=0x8ee7c0, __pyx_kwds=0x7fff745363f0) at pyFAI/ext/bilinear.c:5024
#4  0x00007fffa553d0e2 in __Pyx_CyFunction_Call (kw=0x7fff7459e248, arg=0x7fff756739d8, func=0x7fffa577bba8) at pyFAI/ext/bilinear.c:32569
#5  __pyx_FusedFunction_callfunction (kw=0x7fff7459e248, args=0x7fff756739d8, func=0x7fffa577bba8) at pyFAI/ext/bilinear.c:32844
#6  __pyx_FusedFunction_call (func=0x7fffa577bba8, args=0x7fff756739d8, kw=0x7fff7459e248) at pyFAI/ext/bilinear.c:32930
#7  0x0000000000437c6e in PyObject_Call (func=func@entry=0x7fffa577bc78, arg=arg@entry=0x7fff756739d8, kw=kw@entry=0x7fff7459e248) at Objects/abstract.c:2165
#8  0x00000000004f5d7f in do_call (nk=<optimized out>, na=<optimized out>, pp_stack=0x7fffffffb060, func=0x7fffa577bc78) at Python/ceval.c:4936
#9  call_function (oparg=<optimized out>, pp_stack=0x7fffffffb060) at Python/ceval.c:4732
#10 PyEval_EvalFrameEx (f=0x44e6718, throwflag=<optimized out>) at Python/ceval.c:3236
#11 0x00000000004fe510 in _PyEval_EvalCodeWithName (_co=0x7920, globals=0x13cf7e482930, locals=0x1, locals@entry=0x0, args=0x43, argcount=12, argcount@entry=3, 
    kws=0x7fff7e47b010, kwcount=0, defs=0x7fffa6758c40, defcount=4, kwdefs=0x0, closure=0x0, name=0x7fffcb047940, qualname=0x7fffcb0091e8) at Python/ceval.c:4018
#12 0x00000000004fb6fc in fast_function (nk=<optimized out>, na=3, n=<optimized out>, pp_stack=0x7fffffffb240, func=0x7fffa578c840) at Python/ceval.c:4813
#13 call_function (oparg=<optimized out>, pp_stack=0x7fffffffb240) at Python/ceval.c:4730
#14 PyEval_EvalFrameEx (f=0x7fff75e88dd8, throwflag=<optimized out>) at Python/ceval.c:3236
#15 0x00000000004fe510 in _PyEval_EvalCodeWithName (_co=0x7920, globals=0x13cf7e482930, locals=0x1, locals@entry=0x0, args=0x43, argcount=12, argcount@entry=5, 
    kws=0x7fff7e47b010, kwcount=0, defs=0x7fff820e33a0, defcount=2, kwdefs=0x0, closure=0x0, name=0x7fff820c1990, qualname=0x7fff8803fd98) at Python/ceval.c:4018
#16 0x00000000004fb6fc in fast_function (nk=<optimized out>, na=5, n=<optimized out>, pp_stack=0x7fffffffb420, func=0x7fff820e98c8) at Python/ceval.c:4813
#17 call_function (oparg=<optimized out>, pp_stack=0x7fffffffb420) at Python/ceval.c:4730
#18 PyEval_EvalFrameEx (f=0x44d4498, throwflag=<optimized out>) at Python/ceval.c:3236
#19 0x00000000004fe510 in _PyEval_EvalCodeWithName (_co=0x7920, globals=0x13cf7e482930, locals=0x1, locals@entry=0x0, args=0x43, argcount=12, argcount@entry=3, 
---Type <return> to continue, or q <return> to quit---
    kws=0x7fff7e47b010, kwcount=0, defs=0x7fff820e3e60, defcount=2, kwdefs=0x0, closure=0x0, name=0x7fffcb021f48, qualname=0x7fff820c64f0) at Python/ceval.c:4018
#20 0x00000000004fb6fc in fast_function (nk=<optimized out>, na=3, n=<optimized out>, pp_stack=0x7fffffffb600, func=0x7fff820e99d8) at Python/ceval.c:4813
#21 call_function (oparg=<optimized out>, pp_stack=0x7fffffffb600) at Python/ceval.c:4730
#22 PyEval_EvalFrameEx (f=f@entry=0x58f9bc8, throwflag=throwflag@entry=0) at Python/ceval.c:3236
#23 0x00000000004fc862 in fast_function (nk=<optimized out>, na=1, n=1, pp_stack=0x7fffffffb700, func=0x7fff7dc76d08) at Python/ceval.c:4803
#24 call_function (oparg=<optimized out>, pp_stack=0x7fffffffb700) at Python/ceval.c:4730
#25 PyEval_EvalFrameEx (f=f@entry=0x44c38a8, throwflag=throwflag@entry=0) at Python/ceval.c:3236
#26 0x00000000004fc862 in fast_function (nk=<optimized out>, na=1, n=1, pp_stack=0x7fffffffb800, func=0x7fff7d9e0950) at Python/ceval.c:4803
#27 call_function (oparg=<optimized out>, pp_stack=0x7fffffffb800) at Python/ceval.c:4730
#28 PyEval_EvalFrameEx (f=0x7fff75f7c5e8, throwflag=<optimized out>) at Python/ceval.c:3236
#29 0x00000000004fe510 in _PyEval_EvalCodeWithName (_co=0x7920, globals=0x13cf7e482930, locals=0x1, locals@entry=0x0, args=0x43, argcount=12, kws=0x7fff7e47b010, 
    kws@entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4018
#30 0x00000000004fe5d3 in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x7fff74502338, 
    argcount=<optimized out>, kws=kws@entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4039
#31 0x000000000059e056 in function_call (func=0x7fff7d9e08c8, arg=0x7fff74502320, kw=0x0) at Objects/funcobject.c:627
#32 0x0000000000437c6e in PyObject_Call (func=func@entry=0x7fff7d9e08c8, arg=arg@entry=0x7fff74502320, kw=kw@entry=0x0) at Objects/abstract.c:2165
#33 0x000000000059133d in method_call (func=0x7fff7d9e08c8, arg=0x7fff74502320, kw=0x0) at Objects/classobject.c:330
#34 0x0000000000437c6e in PyObject_Call (func=func@entry=0x7fff74500848, arg=arg@entry=0x7ffff7e00048, kw=<optimized out>) at Objects/abstract.c:2165
#35 0x00000000004f4b27 in PyEval_CallObjectWithKeywords (func=0x7fff74500848, arg=0x7ffff7e00048, kw=<optimized out>) at Python/ceval.c:4580
#36 0x00007fffa5200af5 in PyQtSlot::call(_object*, _object*) const () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtCore.so
#37 0x00007fffa5201000 in PyQtSlot::invoke(void**, _object*, void*, bool) const () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtCore.so
#38 0x00007fffa520127b in PyQtSlotProxy::unislot(void**) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtCore.so
#39 0x00007fffa5202267 in PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtCore.so
```

**Comment by vallsv** [comment]
Looks to be the same with rot1 or rot2 == 90 or -90
