### ISSUE TITLE
[calib2] Bounds in energy

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#996]
as ```E = hc/lambda`, the order in the bounds is inverted and crashed with:
```
ERROR:pyFAI-calib2.UNCAUGHT:SLSQP Error: lb > ub in bounds 6.
Traceback (most recent call last):
  File "/users/kieffer/workspace-400/pyFAI/build/lib.linux-x86_64-3.5/pyFAI/gui/calibration/GeometryTask.py", line 928, in __fitGeometry
    calibration.refine()
  File "/users/kieffer/workspace-400/pyFAI/build/lib.linux-x86_64-3.5/pyFAI/gui/calibration/RingCalibration.py", line 172, in refine
    residual = self.__refine(10000, fix=self.__fixed)
  File "/users/kieffer/workspace-400/pyFAI/build/lib.linux-x86_64-3.5/pyFAI/gui/calibration/RingCalibration.py", line 154, in __refine
    return self.__geoRef.refine2_wavelength(maxiter, fix)
  File "/users/kieffer/workspace-400/pyFAI/build/lib.linux-x86_64-3.5/pyFAI/geometryRefinement.py", line 399, in refine2_wavelength
    iprint=(logger.getEffectiveLevel() <= logging.INFO))
  File "/usr/lib/python3/dist-packages/scipy/optimize/slsqp.py", line 207, in fmin_slsqp
    constraints=cons, **opts)
  File "/usr/lib/python3/dist-packages/scipy/optimize/slsqp.py", line 344, in _minimize_slsqp
    ', '.join(str(b) for b in bnderr))
ValueError: SLSQP Error: lb > ub in bounds 6.
^CERROR:pyFAI-calib2.UNCAUGHT:
```

**Comment by kif** [comment]
the question is: should this be addressed in GeometryRefinement or in the GUI ?

**Comment by vallsv** [comment]
That's user entry. If it fails the optimizer, it have to be fixed in the GUI. At least it have to be catched by the GUI.
